//
//  AlcoholicDrinksData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 17.10.2023.
//

import Foundation

let alcoholicDrinks = [AlcoholicDrinks(name: "Absinthe", type: .alcoholicDrinks, calories: "246"),
                       AlcoholicDrinks(name: "Aged port wine for 10 years", type: .alcoholicDrinks, calories: "186"),
                       AlcoholicDrinks(name: "Aged port wine for 20 years", type: .alcoholicDrinks, calories: "195"),
                       AlcoholicDrinks(name: "Aged port wine for 30 years", type: .alcoholicDrinks, calories: "198"),
                       AlcoholicDrinks(name: "Aged whiskey", type: .alcoholicDrinks, calories: "250"),
                       AlcoholicDrinks(name: "Aligote wine (Aligote)", type: .alcoholicDrinks, calories: "82"),
                       AlcoholicDrinks(name: "Almond liqueur", type: .alcoholicDrinks, calories: "286"),
                       AlcoholicDrinks(name: "Amaretto Liqueur", type: .alcoholicDrinks, calories: "308"),
                       AlcoholicDrinks(name: "Amaro", type: .alcoholicDrinks, calories: "284"),
                       AlcoholicDrinks(name: "Amarula Liqueur (Amarula)", type: .alcoholicDrinks, calories: "348"),
                       AlcoholicDrinks(name: "Amontillado Sherry", type: .alcoholicDrinks, calories: "139"),
                       AlcoholicDrinks(name: "Angostura bitter", type: .alcoholicDrinks, calories: "148"),
                       AlcoholicDrinks(name: "Anise liqueur", type: .alcoholicDrinks, calories: "353"),
                       AlcoholicDrinks(name: "Aniseed vodka", type: .alcoholicDrinks, calories: "250"),
                       AlcoholicDrinks(name: "Apple Sambuka", type: .alcoholicDrinks, calories: "347"),
                       AlcoholicDrinks(name: "Apple cider", type: .alcoholicDrinks, calories: "49"),
                       AlcoholicDrinks(name: "Apple liqueur", type: .alcoholicDrinks, calories: "324"),
                       AlcoholicDrinks(name: "Apple wine", type: .alcoholicDrinks, calories: "49"),
                       AlcoholicDrinks(name: "Apricot liqueur", type: .alcoholicDrinks, calories: "232"),
                       AlcoholicDrinks(name: "Arak vodka", type: .alcoholicDrinks, calories: "328"),
                       AlcoholicDrinks(name: "Ararat Cognac", type: .alcoholicDrinks, calories: "234"),
                       AlcoholicDrinks(name: "Armagnac", type: .alcoholicDrinks, calories: "220"),
                       AlcoholicDrinks(name: "Baileys Liqueur", type: .alcoholicDrinks, calories: "327"),
                       AlcoholicDrinks(name: "Balm", type: .alcoholicDrinks, calories: "33"),
                       AlcoholicDrinks(name: "Banana liqueur", type: .alcoholicDrinks, calories: "321"),
                       AlcoholicDrinks(name: "Banana liqueur green", type: .alcoholicDrinks, calories: "320"),
                       AlcoholicDrinks(name: "Banana sambuca", type: .alcoholicDrinks, calories: "376"),
                       AlcoholicDrinks(name: "Beaujolais Nouveau wine (Beaujolais nouveau)", type: .alcoholicDrinks, calories: "68"),
                       AlcoholicDrinks(name: "Beer", type: .alcoholicDrinks, calories: "43"),
                       AlcoholicDrinks(name: "Beer Lager", type: .alcoholicDrinks, calories: "41"),
                       AlcoholicDrinks(name: "Beer Porter", type: .alcoholicDrinks, calories: "64"),
                       AlcoholicDrinks(name: "Beer ale", type: .alcoholicDrinks, calories: "43"),
                       AlcoholicDrinks(name: "Beer stout", type: .alcoholicDrinks, calories: "45"),
                       AlcoholicDrinks(name: "Benedictine", type: .alcoholicDrinks, calories: "292"),
                       AlcoholicDrinks(name: "Berry liqueur", type: .alcoholicDrinks, calories: "268"),
                       AlcoholicDrinks(name: "Bitter walnut", type: .alcoholicDrinks, calories: "345"),
                       AlcoholicDrinks(name: "Blackberry liqueur", type: .alcoholicDrinks, calories: "320"),
                       AlcoholicDrinks(name: "Blackcurrant liqueur", type: .alcoholicDrinks, calories: "302"),
                       AlcoholicDrinks(name: "Blackcurrant vodka", type: .alcoholicDrinks, calories: "224"),
                       AlcoholicDrinks(name: "Bloody Mary Cocktail", type: .alcoholicDrinks, calories: "41"),
                       AlcoholicDrinks(name: "Blue Curacao Liqueur", type: .alcoholicDrinks, calories: "324"),
                       AlcoholicDrinks(name: "Blueberry liqueur", type: .alcoholicDrinks, calories: "324"),
                       AlcoholicDrinks(name: "Booze drink", type: .alcoholicDrinks, calories: "271"),
                       AlcoholicDrinks(name: "Bordeaux wines (Bordeaux)", type: .alcoholicDrinks, calories: "68"),
                       AlcoholicDrinks(name: "Bourbon", type: .alcoholicDrinks, calories: "239"),
                       AlcoholicDrinks(name: "Boza Drink", type: .alcoholicDrinks, calories: "42"),
                       AlcoholicDrinks(name: "Brandy", type: .alcoholicDrinks, calories: "231"),
                       AlcoholicDrinks(name: "Brogans Liqueur (Brogans)", type: .alcoholicDrinks, calories: "305"),
                       AlcoholicDrinks(name: "Brut champagne", type: .alcoholicDrinks, calories: "73"),
                       AlcoholicDrinks(name: "Bulgarian vodka rakia", type: .alcoholicDrinks, calories: "244"),
                       AlcoholicDrinks(name: "Cabernet Sauvignon wine (Cabernet Sauvignon)", type: .alcoholicDrinks, calories: "83"),
                       AlcoholicDrinks(name: "Cahors Wine (Cahors)", type: .alcoholicDrinks, calories: "83"),
                       AlcoholicDrinks(name: "Calvados", type: .alcoholicDrinks, calories: "250"),
                       AlcoholicDrinks(name: "Campari Liqueur (Campari)", type: .alcoholicDrinks, calories: "225"),
                       AlcoholicDrinks(name: "Cask beer", type: .alcoholicDrinks, calories: "44"),
                       AlcoholicDrinks(name: "Celery bitter", type: .alcoholicDrinks, calories: "47"),
                       AlcoholicDrinks(name: "Chablis wine (Chablis)", type: .alcoholicDrinks, calories: "83"),
                       AlcoholicDrinks(name: "Chacha", type: .alcoholicDrinks, calories: "326"),
                       AlcoholicDrinks(name: "Champagne", type: .alcoholicDrinks, calories: "76"),
                       AlcoholicDrinks(name: "Chardonnay white wine", type: .alcoholicDrinks, calories: "83"),
                       AlcoholicDrinks(name: "Chartreuse Liqueur", type: .alcoholicDrinks, calories: "276"),
                       AlcoholicDrinks(name: "Cherry Sambuka", type: .alcoholicDrinks, calories: "320"),
                       AlcoholicDrinks(name: "Cherry liqueur", type: .alcoholicDrinks, calories: "321"),
                       AlcoholicDrinks(name: "Chianti wine (Chianti)", type: .alcoholicDrinks, calories: "83"),
                       AlcoholicDrinks(name: "Chocolate Bitter", type: .alcoholicDrinks, calories: "42"),
                       AlcoholicDrinks(name: "Chocolate Tequila", type: .alcoholicDrinks, calories: "65"),
                       AlcoholicDrinks(name: "Chocolate liqueur", type: .alcoholicDrinks, calories: "368"),
                       AlcoholicDrinks(name: "Cider", type: .alcoholicDrinks, calories: "43"),
                       AlcoholicDrinks(name: "Cinnamon Liqueur", type: .alcoholicDrinks, calories: "328"),
                       AlcoholicDrinks(name: "Citron Vodka", type: .alcoholicDrinks, calories: "235"),
                       AlcoholicDrinks(name: "Cloudberry liqueur", type: .alcoholicDrinks, calories: "250"),
                       AlcoholicDrinks(name: "Clove Bitter", type: .alcoholicDrinks, calories: "43"),
                       AlcoholicDrinks(name: "Cocoa brown liqueur", type: .alcoholicDrinks, calories: "327"),
                       AlcoholicDrinks(name: "Cocoa liqueur light", type: .alcoholicDrinks, calories: "327"),
                       AlcoholicDrinks(name: "Coconut liqueur", type: .alcoholicDrinks, calories: "394"),
                       AlcoholicDrinks(name: "Coffee liqueur", type: .alcoholicDrinks, calories: "308"),
                       AlcoholicDrinks(name: "Cognac", type: .alcoholicDrinks, calories: "239"),
                       AlcoholicDrinks(name: "Cointreau Liqueur", type: .alcoholicDrinks, calories: "325"),
                       AlcoholicDrinks(name: "Cranberry bitter", type: .alcoholicDrinks, calories: "42"),
                       AlcoholicDrinks(name: "Cranberry liqueur", type: .alcoholicDrinks, calories: "327"),
                       AlcoholicDrinks(name: "Cream liqueur", type: .alcoholicDrinks, calories: "325"),
                       AlcoholicDrinks(name: "Creamy liqueur", type: .alcoholicDrinks, calories: "317"),
                       AlcoholicDrinks(name: "Cuba libre Cocktail (Cuba libre)", type: .alcoholicDrinks, calories: "58"),
                       AlcoholicDrinks(name: "Daiquiri Cocktail (Daiquiri)", type: .alcoholicDrinks, calories: "113"),
                       AlcoholicDrinks(name: "Dark Rum", type: .alcoholicDrinks, calories: "231"),
                       AlcoholicDrinks(name: "Dark beer", type: .alcoholicDrinks, calories: "66"),
                       AlcoholicDrinks(name: "Dessert fortified wines", type: .alcoholicDrinks, calories: "159"),
                       AlcoholicDrinks(name: "Dom Pérignon Champagne (Dom Pérignon)", type: .alcoholicDrinks, calories: "69"),
                       AlcoholicDrinks(name: "Drambuie Liqueur (Drambuie)", type: .alcoholicDrinks, calories: "272"),
                       AlcoholicDrinks(name: "Drink Akvavit (Akvavit)", type: .alcoholicDrinks, calories: "70"),
                       AlcoholicDrinks(name: "Dry champagne", type: .alcoholicDrinks, calories: "70"),
                       AlcoholicDrinks(name: "Dry red wine", type: .alcoholicDrinks, calories: "83"),
                       AlcoholicDrinks(name: "Dry vermouth", type: .alcoholicDrinks, calories: "165"),
                       AlcoholicDrinks(name: "Dry white wine", type: .alcoholicDrinks, calories: "83"),
                       AlcoholicDrinks(name: "Egg liqueur", type: .alcoholicDrinks, calories: "320"),
                       AlcoholicDrinks(name: "Egg-nog", type: .alcoholicDrinks, calories: "88"),
                       AlcoholicDrinks(name: "Elderflower liqueur", type: .alcoholicDrinks, calories: "326"),
                       AlcoholicDrinks(name: "Ethyl alcohol", type: .alcoholicDrinks, calories: "244"),
                       AlcoholicDrinks(name: "Falernum Liqueur", type: .alcoholicDrinks, calories: "274"),
                       AlcoholicDrinks(name: "Fortified dry white wine", type: .alcoholicDrinks, calories: "161"),
                       AlcoholicDrinks(name: "Fortified red wine", type: .alcoholicDrinks, calories: "172"),
                       AlcoholicDrinks(name: "Fortified white wine", type: .alcoholicDrinks, calories: "155"),
                       AlcoholicDrinks(name: "Frangelico Liqueur (Frangelico)", type: .alcoholicDrinks, calories: "327"),
                       AlcoholicDrinks(name: "Fruit and berry wine", type: .alcoholicDrinks, calories: "83"),
                       AlcoholicDrinks(name: "Galliano", type: .alcoholicDrinks, calories: "325"),
                       AlcoholicDrinks(name: "Galliano Liqueur", type: .alcoholicDrinks, calories: "325"),
                       AlcoholicDrinks(name: "Genever", type: .alcoholicDrinks, calories: "253"),
                       AlcoholicDrinks(name: "Gin", type: .alcoholicDrinks, calories: "263"),
                       AlcoholicDrinks(name: "Gin and tonic", type: .alcoholicDrinks, calories: "74"),
                       AlcoholicDrinks(name: "Golden Rum", type: .alcoholicDrinks, calories: "231"),
                       AlcoholicDrinks(name: "Golden Tequila", type: .alcoholicDrinks, calories: "231"),
                       AlcoholicDrinks(name: "Grand Marnier Liqueur", type: .alcoholicDrinks, calories: "289"),
                       AlcoholicDrinks(name: "Grapefruit bitter", type: .alcoholicDrinks, calories: "37"),
                       AlcoholicDrinks(name: "Grappa grape", type: .alcoholicDrinks, calories: "273"),
                       AlcoholicDrinks(name: "Greek vodka Ouzo (Ouzo)", type: .alcoholicDrinks, calories: "342"),
                       AlcoholicDrinks(name: "Grog", type: .alcoholicDrinks, calories: "78"),
                       AlcoholicDrinks(name: "Honey wine", type: .alcoholicDrinks, calories: "215"),
                       AlcoholicDrinks(name: "Horseradish drink", type: .alcoholicDrinks, calories: "76"),
                       AlcoholicDrinks(name: "Irish Cream Liqueur", type: .alcoholicDrinks, calories: "327"),
                       AlcoholicDrinks(name: "Irish Mist Liqueur (Irish Mist)", type: .alcoholicDrinks, calories: "331"),
                       AlcoholicDrinks(name: "Irish whiskey", type: .alcoholicDrinks, calories: "264"),
                       AlcoholicDrinks(name: "Jaguar Drink", type: .alcoholicDrinks, calories: "105"),
                       AlcoholicDrinks(name: "Jerez Pedro Jimenez", type: .alcoholicDrinks, calories: "166"),
                       AlcoholicDrinks(name: "Julep", type: .alcoholicDrinks, calories: "53"),
                       AlcoholicDrinks(name: "Kahlua Liqueur", type: .alcoholicDrinks, calories: "309"),
                       AlcoholicDrinks(name: "Kashasa", type: .alcoholicDrinks, calories: "231"),
                       AlcoholicDrinks(name: "Khvanchkara wine", type: .alcoholicDrinks, calories: "79"),
                       AlcoholicDrinks(name: "Killepich", type: .alcoholicDrinks, calories: "69"),
                       AlcoholicDrinks(name: "Kindzmarauli wine", type: .alcoholicDrinks, calories: "79"),
                       AlcoholicDrinks(name: "Kirschwasser", type: .alcoholicDrinks, calories: "327"),
                       AlcoholicDrinks(name: "Lemon Bitter", type: .alcoholicDrinks, calories: "37"),
                       AlcoholicDrinks(name: "Lemon liqueur", type: .alcoholicDrinks, calories: "300"),
                       AlcoholicDrinks(name: "Lemongrass liqueur", type: .alcoholicDrinks, calories: "324"),
                       AlcoholicDrinks(name: "Light Sambuka", type: .alcoholicDrinks, calories: "322"),
                       AlcoholicDrinks(name: "Light beer", type: .alcoholicDrinks, calories: "29"),
                       AlcoholicDrinks(name: "Limoncello", type: .alcoholicDrinks, calories: "326"),
                       AlcoholicDrinks(name: "Limoncello Liqueur", type: .alcoholicDrinks, calories: "328"),
                       AlcoholicDrinks(name: "Liqueur", type: .alcoholicDrinks, calories: "326"),
                       AlcoholicDrinks(name: "Liqueur Marie Brizard (Marie Brizard)", type: .alcoholicDrinks, calories: "324"),
                       AlcoholicDrinks(name: "Liquor", type: .alcoholicDrinks, calories: "324"),
                       AlcoholicDrinks(name: "Liquor Advocate (Advocaat)", type: .alcoholicDrinks, calories: "328"),
                       AlcoholicDrinks(name: "Liquor Becherovka", type: .alcoholicDrinks, calories: "234"),
                       AlcoholicDrinks(name: "Liquor Jagermeister (Jagermeister)", type: .alcoholicDrinks, calories: "243"),
                       AlcoholicDrinks(name: "Live beer", type: .alcoholicDrinks, calories: "42"),
                       AlcoholicDrinks(name: "Lychee liqueur", type: .alcoholicDrinks, calories: "320"),
                       AlcoholicDrinks(name: "Madeira wine", type: .alcoholicDrinks, calories: "147"),
                       AlcoholicDrinks(name: "Madras Wine (Madrasa)", type: .alcoholicDrinks, calories: "106"),
                       AlcoholicDrinks(name: "Malaga Wine", type: .alcoholicDrinks, calories: "157"),
                       AlcoholicDrinks(name: "Malibu", type: .alcoholicDrinks, calories: "51"),
                       AlcoholicDrinks(name: "Malibu Liqueur", type: .alcoholicDrinks, calories: "303"),
                       AlcoholicDrinks(name: "Mandarin vodka", type: .alcoholicDrinks, calories: "230"),
                       AlcoholicDrinks(name: "Mango Liqueur", type: .alcoholicDrinks, calories: "320"),
                       AlcoholicDrinks(name: "Maraschino Liqueur", type: .alcoholicDrinks, calories: "316"),
                       AlcoholicDrinks(name: "Marsala Wine", type: .alcoholicDrinks, calories: "81"),
                       AlcoholicDrinks(name: "Martini", type: .alcoholicDrinks, calories: "130"),
                       AlcoholicDrinks(name: "Mead", type: .alcoholicDrinks, calories: "300"),
                       AlcoholicDrinks(name: "Melon liqueur", type: .alcoholicDrinks, calories: "287"),
                       AlcoholicDrinks(name: "Melon syrup", type: .alcoholicDrinks, calories: "312"),
                       AlcoholicDrinks(name: "Mezcal", type: .alcoholicDrinks, calories: "261"),
                       AlcoholicDrinks(name: "Midori Liqueur", type: .alcoholicDrinks, calories: "80"),
                       AlcoholicDrinks(name: "Milk liqueur", type: .alcoholicDrinks, calories: "110"),
                       AlcoholicDrinks(name: "Mint Bitter", type: .alcoholicDrinks, calories: "37"),
                       AlcoholicDrinks(name: "Mint liqueur", type: .alcoholicDrinks, calories: "303"),
                       AlcoholicDrinks(name: "Mint tincture", type: .alcoholicDrinks, calories: "324"),
                       AlcoholicDrinks(name: "Mojito Cocktail (Mojito)", type: .alcoholicDrinks, calories: "60"),
                       AlcoholicDrinks(name: "Moldovan wine Feteasca (Fetească)", type: .alcoholicDrinks, calories: "83"),
                       AlcoholicDrinks(name: "Moonshine", type: .alcoholicDrinks, calories: "222"),
                       AlcoholicDrinks(name: "Mozart Liqueur", type: .alcoholicDrinks, calories: "327"),
                       AlcoholicDrinks(name: "Mulled wine", type: .alcoholicDrinks, calories: "83"),
                       AlcoholicDrinks(name: "Muscat Wine (Muscat)", type: .alcoholicDrinks, calories: "160"),
                       AlcoholicDrinks(name: "Nut liqueur", type: .alcoholicDrinks, calories: "339"),
                       AlcoholicDrinks(name: "Oloroso Sherry", type: .alcoholicDrinks, calories: "185"),
                       AlcoholicDrinks(name: "Orange Bitter", type: .alcoholicDrinks, calories: "44"),
                       AlcoholicDrinks(name: "Orange liqueur", type: .alcoholicDrinks, calories: "303"),
                       AlcoholicDrinks(name: "Oruho", type: .alcoholicDrinks, calories: "284"),
                       AlcoholicDrinks(name: "Pacharan", type: .alcoholicDrinks, calories: "230"),
                       AlcoholicDrinks(name: "Passion fruit liqueur", type: .alcoholicDrinks, calories: "326"),
                       AlcoholicDrinks(name: "Pastis (Pastis)", type: .alcoholicDrinks, calories: "288"),
                       AlcoholicDrinks(name: "Peach Bitter", type: .alcoholicDrinks, calories: "36"),
                       AlcoholicDrinks(name: "Peach liqueur", type: .alcoholicDrinks, calories: "279"),
                       AlcoholicDrinks(name: "Peach schnapps", type: .alcoholicDrinks, calories: "237"),
                       AlcoholicDrinks(name: "Pear liqueur", type: .alcoholicDrinks, calories: "326"),
                       AlcoholicDrinks(name: "Pear vodka", type: .alcoholicDrinks, calories: "231"),
                       AlcoholicDrinks(name: "Pepper vodka", type: .alcoholicDrinks, calories: "231"),
                       AlcoholicDrinks(name: "Pimento dram liqueur", type: .alcoholicDrinks, calories: "274"),
                       AlcoholicDrinks(name: "Pina Colada Cocktail", type: .alcoholicDrinks, calories: "127"),
                       AlcoholicDrinks(name: "Pink Champagne", type: .alcoholicDrinks, calories: "84"),
                       AlcoholicDrinks(name: "Pink Vermouth", type: .alcoholicDrinks, calories: "130"),
                       AlcoholicDrinks(name: "Pisco", type: .alcoholicDrinks, calories: "250"),
                       AlcoholicDrinks(name: "Pisho bitter", type: .alcoholicDrinks, calories: "37"),
                       AlcoholicDrinks(name: "Plum Bitter", type: .alcoholicDrinks, calories: "37"),
                       AlcoholicDrinks(name: "Plum Gin", type: .alcoholicDrinks, calories: "247"),
                       AlcoholicDrinks(name: "Plum wine", type: .alcoholicDrinks, calories: "82"),
                       AlcoholicDrinks(name: "Port Wine", type: .alcoholicDrinks, calories: "166"),
                       AlcoholicDrinks(name: "Port Wine special reserve", type: .alcoholicDrinks, calories: "176"),
                       AlcoholicDrinks(name: "Prosecco wine (Prosecco)", type: .alcoholicDrinks, calories: "65"),
                       AlcoholicDrinks(name: "Punch", type: .alcoholicDrinks, calories: "120"),
                       AlcoholicDrinks(name: "Raspberry Sambuka", type: .alcoholicDrinks, calories: "345"),
                       AlcoholicDrinks(name: "Raspberry liqueur", type: .alcoholicDrinks, calories: "312"),
                       AlcoholicDrinks(name: "Raspberry vodka", type: .alcoholicDrinks, calories: "269"),
                       AlcoholicDrinks(name: "Red Vermouth", type: .alcoholicDrinks, calories: "140"),
                       AlcoholicDrinks(name: "Red dessert wine", type: .alcoholicDrinks, calories: "165"),
                       AlcoholicDrinks(name: "Red grapefruit liqueur", type: .alcoholicDrinks, calories: "265"),
                       AlcoholicDrinks(name: "Red wine Merlot (Merlot)", type: .alcoholicDrinks, calories: "83"),
                       AlcoholicDrinks(name: "Rhubarb bitter", type: .alcoholicDrinks, calories: "37"),
                       AlcoholicDrinks(name: "Rhubarb liqueur", type: .alcoholicDrinks, calories: "297"),
                       AlcoholicDrinks(name: "Riesling white wine", type: .alcoholicDrinks, calories: "83"),
                       AlcoholicDrinks(name: "Rose wine", type: .alcoholicDrinks, calories: "83"),
                       AlcoholicDrinks(name: "Rum", type: .alcoholicDrinks, calories: "231"),
                       AlcoholicDrinks(name: "Rum-151", type: .alcoholicDrinks, calories: "276"),
                       AlcoholicDrinks(name: "Sake", type: .alcoholicDrinks, calories: "134"),
                       AlcoholicDrinks(name: "Sambuca Liqueur", type: .alcoholicDrinks, calories: "345"),
                       AlcoholicDrinks(name: "Sambuca orange-mango", type: .alcoholicDrinks, calories: "345"),
                       AlcoholicDrinks(name: "Sangria", type: .alcoholicDrinks, calories: "93"),
                       AlcoholicDrinks(name: "Schnapps", type: .alcoholicDrinks, calories: "83"),
                       AlcoholicDrinks(name: "Scotch whiskey", type: .alcoholicDrinks, calories: "250"),
                       AlcoholicDrinks(name: "Semi-dry champagne", type: .alcoholicDrinks, calories: "75"),
                       AlcoholicDrinks(name: "Semi-dry red wine", type: .alcoholicDrinks, calories: "83"),
                       AlcoholicDrinks(name: "Semi-dry white wine", type: .alcoholicDrinks, calories: "83"),
                       AlcoholicDrinks(name: "Semisweet champagne", type: .alcoholicDrinks, calories: "81"),
                       AlcoholicDrinks(name: "Sheridan's Liqueur", type: .alcoholicDrinks, calories: "304"),
                       AlcoholicDrinks(name: "Sherry Fino", type: .alcoholicDrinks, calories: "140"),
                       AlcoholicDrinks(name: "Sherry wine", type: .alcoholicDrinks, calories: "140"),
                       AlcoholicDrinks(name: "Silver Tequila", type: .alcoholicDrinks, calories: "250"),
                       AlcoholicDrinks(name: "Single malt whiskey", type: .alcoholicDrinks, calories: "250"),
                       AlcoholicDrinks(name: "Slivovitsa", type: .alcoholicDrinks, calories: "240"),
                       AlcoholicDrinks(name: "Sour cherry liqueur", type: .alcoholicDrinks, calories: "320"),
                       AlcoholicDrinks(name: "Southern Comfort Liqueur", type: .alcoholicDrinks, calories: "305"),
                       AlcoholicDrinks(name: "Soviet champagne", type: .alcoholicDrinks, calories: "85"),
                       AlcoholicDrinks(name: "Sparkling wines", type: .alcoholicDrinks, calories: "83"),
                       AlcoholicDrinks(name: "Spicy rum", type: .alcoholicDrinks, calories: "225"),
                       AlcoholicDrinks(name: "Strawberry liqueur", type: .alcoholicDrinks, calories: "324"),
                       AlcoholicDrinks(name: "Tangerine liqueur", type: .alcoholicDrinks, calories: "327"),
                       AlcoholicDrinks(name: "Tequila", type: .alcoholicDrinks, calories: "231"),
                       AlcoholicDrinks(name: "Tincture", type: .alcoholicDrinks, calories: "323"),
                       AlcoholicDrinks(name: "Toffee liqueur", type: .alcoholicDrinks, calories: "328"),
                       AlcoholicDrinks(name: "Tokay wines", type: .alcoholicDrinks, calories: "157"),
                       AlcoholicDrinks(name: "Tony's Port", type: .alcoholicDrinks, calories: "87"),
                       AlcoholicDrinks(name: "Tsipuro", type: .alcoholicDrinks, calories: "263"),
                       AlcoholicDrinks(name: "Vana Tallinn Liqueur", type: .alcoholicDrinks, calories: "263"),
                       AlcoholicDrinks(name: "Vanilla liqueur", type: .alcoholicDrinks, calories: "312"),
                       AlcoholicDrinks(name: "Vanilla vodka", type: .alcoholicDrinks, calories: "225"),
                       AlcoholicDrinks(name: "Vermouth", type: .alcoholicDrinks, calories: "140"),
                       AlcoholicDrinks(name: "Vermouth Cinzano (Cinzano)", type: .alcoholicDrinks, calories: "140"),
                       AlcoholicDrinks(name: "Veuve Clicquot Champagne (Veuve Clicquot)", type: .alcoholicDrinks, calories: "84"),
                       AlcoholicDrinks(name: "Vintage port", type: .alcoholicDrinks, calories: "87"),
                       AlcoholicDrinks(name: "Violet liqueur", type: .alcoholicDrinks, calories: "274"),
                       AlcoholicDrinks(name: "Vodka", type: .alcoholicDrinks, calories: "231"),
                       AlcoholicDrinks(name: "Whiskey", type: .alcoholicDrinks, calories: "250"),
                       AlcoholicDrinks(name: "White dessert wine", type: .alcoholicDrinks, calories: "165"),
                       AlcoholicDrinks(name: "White rum", type: .alcoholicDrinks, calories: "231"),
                       AlcoholicDrinks(name: "White vermouth", type: .alcoholicDrinks, calories: "140"),
                       AlcoholicDrinks(name: "Wild Africa Liqueur", type: .alcoholicDrinks, calories: "308"),
                       AlcoholicDrinks(name: "Wine", type: .alcoholicDrinks, calories: "83"),
                       AlcoholicDrinks(name: "Xuxu Liqueur (XuXu)", type: .alcoholicDrinks, calories: "222")]

