//
//  EggsAndDairyProductsData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 10.10.2023.
//

import Foundation

let eggsAndDairyProducts = [EggsAndDairyProducts(name: "Acidophilic paste", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Acidophilus", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Adyghe cheese", type: .eggsAndDairyProducts, calories: "255"),
                          EggsAndDairyProducts(name: "Almette cheese", type: .eggsAndDairyProducts, calories: "200"),
                          EggsAndDairyProducts(name: "Altai cheese", type: .eggsAndDairyProducts, calories: "300"),
                          EggsAndDairyProducts(name: "Amadeus cheese", type: .eggsAndDairyProducts, calories: "380"),
                          EggsAndDairyProducts(name: "Anari cheese", type: .eggsAndDairyProducts, calories: "198"),
                          EggsAndDairyProducts(name: "Asiago cheese", type: .eggsAndDairyProducts, calories: "390"),
                          EggsAndDairyProducts(name: "Ayran", type: .eggsAndDairyProducts, calories: "22"),
                          EggsAndDairyProducts(name: "Baltic cheese", type: .eggsAndDairyProducts, calories: "330"),
                          EggsAndDairyProducts(name: "Banon Cheese", type: .eggsAndDairyProducts, calories: "338"),
                          EggsAndDairyProducts(name: "Beaufort cheese", type: .eggsAndDairyProducts, calories: "399"),
                          EggsAndDairyProducts(name: "Bifacil", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Bifitat", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Blue cheese with mold", type: .eggsAndDairyProducts, calories: "354"),
                          EggsAndDairyProducts(name: "Boiled eggs", type: .eggsAndDairyProducts, calories: "155"),
                          EggsAndDairyProducts(name: "Brine cheese", type: .eggsAndDairyProducts, calories: "300"),
                          EggsAndDairyProducts(name: "Brocchio", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Buffalo milk", type: .eggsAndDairyProducts, calories: "100"),
                          EggsAndDairyProducts(name: "Buko Cheese", type: .eggsAndDairyProducts, calories: "286"),
                          EggsAndDairyProducts(name: "Burata Cheese", type: .eggsAndDairyProducts, calories: "249"),
                          EggsAndDairyProducts(name: "Butter", type: .eggsAndDairyProducts, calories: "717"),
                          EggsAndDairyProducts(name: "Buttermilk", type: .eggsAndDairyProducts, calories: "40"),
                          EggsAndDairyProducts(name: "Cambozola cheese", type: .eggsAndDairyProducts, calories: "345"),
                          EggsAndDairyProducts(name: "Camel milk", type: .eggsAndDairyProducts, calories: "43"),
                          EggsAndDairyProducts(name: "Camembert cheese", type: .eggsAndDairyProducts, calories: "299"),
                          EggsAndDairyProducts(name: "Canned cheese", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Canned eggs", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Canned milk", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Cantal Cheese", type: .eggsAndDairyProducts, calories: "388"),
                          EggsAndDairyProducts(name: "Chal", type: .eggsAndDairyProducts, calories: "109"),
                          EggsAndDairyProducts(name: "Cheddar cheese", type: .eggsAndDairyProducts, calories: "403"),
                          EggsAndDairyProducts(name: "Cheese", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Cheese Abondance (Abondance)", type: .eggsAndDairyProducts, calories: "384"),
                          EggsAndDairyProducts(name: "Cheese Athlete (Atleet)", type: .eggsAndDairyProducts, calories: "347"),
                          EggsAndDairyProducts(name: "Cheese Bavaria blue", type: .eggsAndDairyProducts, calories: "353"),
                          EggsAndDairyProducts(name: "Cheese Vats", type: .eggsAndDairyProducts, calories: "374"),
                          EggsAndDairyProducts(name: "Cheese cheese", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Cheese with mold", type: .eggsAndDairyProducts, calories: "354"),
                          EggsAndDairyProducts(name: "Cheese with red mold", type: .eggsAndDairyProducts, calories: "368"),
                          EggsAndDairyProducts(name: "Cheese with white mold", type: .eggsAndDairyProducts, calories: "364"),
                          EggsAndDairyProducts(name: "Chicken egg", type: .eggsAndDairyProducts, calories: "68"),
                          EggsAndDairyProducts(name: "Chocolate milk", type: .eggsAndDairyProducts, calories: "66"),
                          EggsAndDairyProducts(name: "Concentrated milk", type: .eggsAndDairyProducts, calories: "131"),
                          EggsAndDairyProducts(name: "Condensed cream", type: .eggsAndDairyProducts, calories: "292"),
                          EggsAndDairyProducts(name: "Condensed milk", type: .eggsAndDairyProducts, calories: "321"),
                          EggsAndDairyProducts(name: "Cottage cheese", type: .eggsAndDairyProducts, calories: "98"),
                          EggsAndDairyProducts(name: "Cottage cheese cream", type: .eggsAndDairyProducts, calories: "236"),
                          EggsAndDairyProducts(name: "Cottage cheese grain", type: .eggsAndDairyProducts, calories: "98"),
                          EggsAndDairyProducts(name: "Cottage cheese in bold", type: .eggsAndDairyProducts, calories: "138"),
                          EggsAndDairyProducts(name: "Cottage cheese quark", type: .eggsAndDairyProducts, calories: "71"),
                          EggsAndDairyProducts(name: "Cow's milk", type: .eggsAndDairyProducts, calories: "61"),
                          EggsAndDairyProducts(name: "Cream", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Cream 10% fat content", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Cream 20% fat content", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Cream 35% fat content", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Cream cheese", type: .eggsAndDairyProducts, calories: "342"),
                          EggsAndDairyProducts(name: "Creamy ice cream", type: .eggsAndDairyProducts, calories: "237"),
                          EggsAndDairyProducts(name: "Curd", type: .eggsAndDairyProducts, calories: "98"),
                          EggsAndDairyProducts(name: "Curd mass", type: .eggsAndDairyProducts, calories: "84"),
                          EggsAndDairyProducts(name: "Curd whey", type: .eggsAndDairyProducts, calories: "28"),
                          EggsAndDairyProducts(name: "Danablu Cheese", type: .eggsAndDairyProducts, calories: "353"),
                          EggsAndDairyProducts(name: "Danbo cheese", type: .eggsAndDairyProducts, calories: "373"),
                          EggsAndDairyProducts(name: "Dor Blue Cheese", type: .eggsAndDairyProducts, calories: "356"),
                          EggsAndDairyProducts(name: "Drinking cream", type: .eggsAndDairyProducts, calories: "343"),
                          EggsAndDairyProducts(name: "Dry cream", type: .eggsAndDairyProducts, calories: "449"),
                          EggsAndDairyProducts(name: "Dry egg yolk", type: .eggsAndDairyProducts, calories: "665"),
                          EggsAndDairyProducts(name: "Duck egg", type: .eggsAndDairyProducts, calories: "185"),
                          EggsAndDairyProducts(name: "Dutch Cheese", type: .eggsAndDairyProducts, calories: "357"),
                          EggsAndDairyProducts(name: "Edam Cheese", type: .eggsAndDairyProducts, calories: "357"),
                          EggsAndDairyProducts(name: "Egg white", type: .eggsAndDairyProducts, calories: "52"),
                          EggsAndDairyProducts(name: "Egg yolk", type: .eggsAndDairyProducts, calories: "322"),
                          EggsAndDairyProducts(name: "Emmental cheese", type: .eggsAndDairyProducts, calories: "381"),
                          EggsAndDairyProducts(name: "Estonian cheese", type: .eggsAndDairyProducts, calories: "354"),
                          EggsAndDairyProducts(name: "Fat cottage cheese", type: .eggsAndDairyProducts, calories: "98"),
                          EggsAndDairyProducts(name: "Fermented milk", type: .eggsAndDairyProducts, calories: "61"),
                          EggsAndDairyProducts(name: "Fermented milk products", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Feta cheese", type: .eggsAndDairyProducts, calories: "264"),
                          EggsAndDairyProducts(name: "Fetaki cheese", type: .eggsAndDairyProducts, calories: "290"),
                          EggsAndDairyProducts(name: "Fetaxa cheese", type: .eggsAndDairyProducts, calories: "295"),
                          EggsAndDairyProducts(name: "Fontina cheese", type: .eggsAndDairyProducts, calories: "389"),
                          EggsAndDairyProducts(name: "Fresh cream", type: .eggsAndDairyProducts, calories: "343"),
                          EggsAndDairyProducts(name: "Fresh milk", type: .eggsAndDairyProducts, calories: "42"),
                          EggsAndDairyProducts(name: "Fruit yogurt", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Ginger milk", type: .eggsAndDairyProducts, calories: "45"),
                          EggsAndDairyProducts(name: "Goat cheese", type: .eggsAndDairyProducts, calories: "364"),
                          EggsAndDairyProducts(name: "Goat cottage cheese", type: .eggsAndDairyProducts, calories: "98"),
                          EggsAndDairyProducts(name: "Goat kefir", type: .eggsAndDairyProducts, calories: "58"),
                          EggsAndDairyProducts(name: "Goat's milk", type: .eggsAndDairyProducts, calories: "68"),
                          EggsAndDairyProducts(name: "Goose eggs", type: .eggsAndDairyProducts, calories: "185"),
                          EggsAndDairyProducts(name: "Gorgonzola Cheese", type: .eggsAndDairyProducts, calories: "353"),
                          EggsAndDairyProducts(name: "Gouda cheese", type: .eggsAndDairyProducts, calories: "356"),
                          EggsAndDairyProducts(name: "Greek yogurt", type: .eggsAndDairyProducts, calories: "73"),
                          EggsAndDairyProducts(name: "Green Pesto cheese", type: .eggsAndDairyProducts, calories: "400"),
                          EggsAndDairyProducts(name: "Green cheese", type: .eggsAndDairyProducts, calories: "300"),
                          EggsAndDairyProducts(name: "Gruyere cheese", type: .eggsAndDairyProducts, calories: "413"),
                          EggsAndDairyProducts(name: "Guinea fowl eggs", type: .eggsAndDairyProducts, calories: "190"),
                          EggsAndDairyProducts(name: "Halumi cheese", type: .eggsAndDairyProducts, calories: "326"),
                          EggsAndDairyProducts(name: "Hard cheese", type: .eggsAndDairyProducts, calories: "371"),
                          EggsAndDairyProducts(name: "Hermelin cheese (Hermelín)", type: .eggsAndDairyProducts, calories: "317"),
                          EggsAndDairyProducts(name: "Homemade cheese", type: .eggsAndDairyProducts, calories: "300"),
                          EggsAndDairyProducts(name: "Homemade mayonnaise", type: .eggsAndDairyProducts, calories: "680"),
                          EggsAndDairyProducts(name: "Homemade yogurt", type: .eggsAndDairyProducts, calories: "61"),
                          EggsAndDairyProducts(name: "Ice cream Sundae", type: .eggsAndDairyProducts, calories: "207"),
                          EggsAndDairyProducts(name: "Jarlsberg cheese", type: .eggsAndDairyProducts, calories: "370"),
                          EggsAndDairyProducts(name: "Katyk", type: .eggsAndDairyProducts, calories: "56"),
                          EggsAndDairyProducts(name: "Kaymak", type: .eggsAndDairyProducts, calories: "290"),
                          EggsAndDairyProducts(name: "Kefir", type: .eggsAndDairyProducts, calories: "41"),
                          EggsAndDairyProducts(name: "Kefir 2.5% fat content", type: .eggsAndDairyProducts, calories: "50"),
                          EggsAndDairyProducts(name: "Kefir 3.2% fat content", type: .eggsAndDairyProducts, calories: "59"),
                          EggsAndDairyProducts(name: "Komte Cheese", type: .eggsAndDairyProducts, calories: "403"),
                          EggsAndDairyProducts(name: "Kostroma cheese", type: .eggsAndDairyProducts, calories: "290"),
                          EggsAndDairyProducts(name: "Koumiss", type: .eggsAndDairyProducts, calories: "46"),
                          EggsAndDairyProducts(name: "Kurt cheese", type: .eggsAndDairyProducts, calories: "328"),
                          EggsAndDairyProducts(name: "Latvian cheese", type: .eggsAndDairyProducts, calories: "385"),
                          EggsAndDairyProducts(name: "Limburger Cheese", type: .eggsAndDairyProducts, calories: "327"),
                          EggsAndDairyProducts(name: "Lithuanian cheese", type: .eggsAndDairyProducts, calories: "340"),
                          EggsAndDairyProducts(name: "Livaro Cheese", type: .eggsAndDairyProducts, calories: "343"),
                          EggsAndDairyProducts(name: "Low-fat cottage cheese", type: .eggsAndDairyProducts, calories: "72"),
                          EggsAndDairyProducts(name: "Low-fat kefir", type: .eggsAndDairyProducts, calories: "33"),
                          EggsAndDairyProducts(name: "Maasdam cheese", type: .eggsAndDairyProducts, calories: "357"),
                          EggsAndDairyProducts(name: "Manchego cheese", type: .eggsAndDairyProducts, calories: "368"),
                          EggsAndDairyProducts(name: "Marble cheese", type: .eggsAndDairyProducts, calories: "361"),
                          EggsAndDairyProducts(name: "Mare's milk", type: .eggsAndDairyProducts, calories: "58"),
                          EggsAndDairyProducts(name: "Mascarpone cheese", type: .eggsAndDairyProducts, calories: "431"),
                          EggsAndDairyProducts(name: "Melted butter", type: .eggsAndDairyProducts, calories: "717"),
                          EggsAndDairyProducts(name: "Melted chocolate cheese", type: .eggsAndDairyProducts, calories: "332"),
                          EggsAndDairyProducts(name: "Melted milk", type: .eggsAndDairyProducts, calories: "371"),
                          EggsAndDairyProducts(name: "Mexican cheese", type: .eggsAndDairyProducts, calories: "61"),
                          EggsAndDairyProducts(name: "Milk", type: .eggsAndDairyProducts, calories: "44"),
                          EggsAndDairyProducts(name: "Milk drink", type: .eggsAndDairyProducts, calories: "42"),
                          EggsAndDairyProducts(name: "Milk whey", type: .eggsAndDairyProducts, calories: "42"),
                          EggsAndDairyProducts(name: "Moscow cheese", type: .eggsAndDairyProducts, calories: "44"),
                          EggsAndDairyProducts(name: "Mozzarella cheese", type: .eggsAndDairyProducts, calories: "322"),
                          EggsAndDairyProducts(name: "Munster cheese", type: .eggsAndDairyProducts, calories: "280"),
                          EggsAndDairyProducts(name: "Nocerino Cheese", type: .eggsAndDairyProducts, calories: "351"),
                          EggsAndDairyProducts(name: "Nut milk", type: .eggsAndDairyProducts, calories: "123"),
                          EggsAndDairyProducts(name: "Oil spread", type: .eggsAndDairyProducts, calories: "102"),
                          EggsAndDairyProducts(name: "Oltermanni cheese", type: .eggsAndDairyProducts, calories: "153"),
                          EggsAndDairyProducts(name: "Ossetian cheese", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Ostrich eggs", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Paneer cheese", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Parmesan cheese", type: .eggsAndDairyProducts, calories: "403"),
                          EggsAndDairyProducts(name: "Partridge eggs", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Pasteurized milk", type: .eggsAndDairyProducts, calories: "61"),
                          EggsAndDairyProducts(name: "Pecorino Cheese", type: .eggsAndDairyProducts, calories: "403"),
                          EggsAndDairyProducts(name: "Philadelphia Cheese", type: .eggsAndDairyProducts, calories: "225"),
                          EggsAndDairyProducts(name: "Pickled cheese", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Pickled chicken eggs", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Pickled quail eggs", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Popsicle ice cream", type: .eggsAndDairyProducts, calories: "80"),
                          EggsAndDairyProducts(name: "Poshekhonsky cheese", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Powdered milk", type: .eggsAndDairyProducts, calories: "496"),
                          EggsAndDairyProducts(name: "Processed cheese", type: .eggsAndDairyProducts, calories: "304"),
                          EggsAndDairyProducts(name: "Protein milk", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Provolone cheese", type: .eggsAndDairyProducts, calories: "351"),
                          EggsAndDairyProducts(name: "Quail eggs", type: .eggsAndDairyProducts, calories: "158"),
                          EggsAndDairyProducts(name: "Reblochon cheese", type: .eggsAndDairyProducts, calories: "360"),
                          EggsAndDairyProducts(name: "Rennet cheese", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Ricotta cheese", type: .eggsAndDairyProducts, calories: "174"),
                          EggsAndDairyProducts(name: "Rocamadour cheese", type: .eggsAndDairyProducts, calories: "319"),
                          EggsAndDairyProducts(name: "Roquefort cheese", type: .eggsAndDairyProducts, calories: "369"),
                          EggsAndDairyProducts(name: "Rougett Cheese", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Russian cheese", type: .eggsAndDairyProducts, calories: "368"),
                          EggsAndDairyProducts(name: "Ryazhenka", type: .eggsAndDairyProducts, calories: "53"),
                          EggsAndDairyProducts(name: "Saler cheese (Salers)", type: .eggsAndDairyProducts, calories: "372"),
                          EggsAndDairyProducts(name: "Sausage cheese", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Sbrinz cheese (Sbrinz)", type: .eggsAndDairyProducts, calories: "456"),
                          EggsAndDairyProducts(name: "Shubat", type: .eggsAndDairyProducts, calories: "64"),
                          EggsAndDairyProducts(name: "Skimmed milk", type: .eggsAndDairyProducts, calories: "35"),
                          EggsAndDairyProducts(name: "Skimmed milk powder", type: .eggsAndDairyProducts, calories: "359"),
                          EggsAndDairyProducts(name: "Smoked cheese", type: .eggsAndDairyProducts, calories: "367"),
                          EggsAndDairyProducts(name: "Smoked pigtail cheese", type: .eggsAndDairyProducts, calories: "315"),
                          EggsAndDairyProducts(name: "Smoked suluguni cheese", type: .eggsAndDairyProducts, calories: "311"),
                          EggsAndDairyProducts(name: "Soft cheeses", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Soft goat cheese", type: .eggsAndDairyProducts, calories: "103"),
                          EggsAndDairyProducts(name: "Soft kaymak cheese", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Sour cream", type: .eggsAndDairyProducts, calories: "198"),
                          EggsAndDairyProducts(name: "Sour cream 10% fat content", type: .eggsAndDairyProducts, calories: "115"),
                          EggsAndDairyProducts(name: "Sour cream 15% fat content", type: .eggsAndDairyProducts, calories: "185"),
                          EggsAndDairyProducts(name: "Sour cream 30% fat content", type: .eggsAndDairyProducts, calories: "322"),
                          EggsAndDairyProducts(name: "Sour milk", type: .eggsAndDairyProducts, calories: "47"),
                          EggsAndDairyProducts(name: "Sour milk cheese", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Soviet cheese", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Sterilized milk", type: .eggsAndDairyProducts, calories: "64"),
                          EggsAndDairyProducts(name: "Stilton Cheese", type: .eggsAndDairyProducts, calories: "375"),
                          EggsAndDairyProducts(name: "Suluguni Cheese", type: .eggsAndDairyProducts, calories: "314"),
                          EggsAndDairyProducts(name: "Suzma", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Swiss cheese", type: .eggsAndDairyProducts, calories: "380"),
                          EggsAndDairyProducts(name: "Tan drink", type: .eggsAndDairyProducts, calories: "40"),
                          EggsAndDairyProducts(name: "Tarak", type: .eggsAndDairyProducts, calories: "60"),
                          EggsAndDairyProducts(name: "Tilsiter cheese", type: .eggsAndDairyProducts, calories: "350"),
                          EggsAndDairyProducts(name: "Tofu cheese", type: .eggsAndDairyProducts, calories: "140"),
                          EggsAndDairyProducts(name: "Turkey egg", type: .eggsAndDairyProducts, calories: "135"),
                          EggsAndDairyProducts(name: "Turtle Eggs", type: .eggsAndDairyProducts, calories: "-"),
                          EggsAndDairyProducts(name: "Uglich cheese", type: .eggsAndDairyProducts, calories: "320"),
                          EggsAndDairyProducts(name: "Varenets", type: .eggsAndDairyProducts, calories: "110"),
                          EggsAndDairyProducts(name: "Whole milk powder", type: .eggsAndDairyProducts, calories: "500"),
                          EggsAndDairyProducts(name: "Yaroslavl cheese", type: .eggsAndDairyProducts, calories: "350"),
                          EggsAndDairyProducts(name: "Yogurt", type: .eggsAndDairyProducts, calories: "60")]

