//
//  EggsAndDairyProductsData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 10.10.2023.
//

import Foundation

let eggsAndDairyProducts = [EggsAndDairyProducts(name: "Acidophilic paste", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Acidophilus", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Adyghe cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Almette cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Altai cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Amadeus cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Anari cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Asiago cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Ayran", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Baltic cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Banon Cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Beaufort cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Bifacil", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Bifitat", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Blue cheese with mold", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Boiled eggs", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Brine cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Brocchio", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Buffalo milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Buko Cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Burata Cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Butter", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Buttermilk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cambozola cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Camel milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Camembert cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Canned cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Canned eggs", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Canned milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cantal Cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Chal", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cheddar cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cheese Abondance (Abondance)", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cheese Athlete (Atleet)", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cheese Bavaria blue", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cheese Vats", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cheese cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cheese with mold", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cheese with red mold", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cheese with white mold", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Chicken egg", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Chocolate milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Concentrated milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Condensed cream", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Condensed milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cottage cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cottage cheese cream", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cottage cheese grain", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cottage cheese in bold", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cottage cheese quark", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cow's milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cream", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cream 10% fat content", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cream 20% fat content", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cream 35% fat content", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Cream cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Creamy ice cream", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Curd", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Curd mass", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Curd whey", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Danablu Cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Danbo cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Dor Blue Cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Drinking cream", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Dry cream", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Dry egg yolk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Duck egg", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Dutch Cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Edam Cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Egg white", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Egg yolk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Emmental cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Estonian cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Fat cottage cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Fermented milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Fermented milk products", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Feta cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Fetaki cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Fetaxa cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Fontina cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Fresh cream", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Fresh milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Fruit yogurt", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Ginger milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Goat cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Goat cottage cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Goat kefir", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Goat's milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Goose eggs", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Gorgonzola Cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Gouda cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Greek yogurt", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Green Pesto cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Green cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Gruyere cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Guinea fowl eggs", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Halumi cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Hard cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Hermelin cheese (Hermelín)", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Homemade cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Homemade mayonnaise", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Homemade yogurt", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Ice cream Sundae", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Jarlsberg cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Katyk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Kaymak", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Kefir", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Kefir 2.5% fat content", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Kefir 3.2% fat content", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Komte Cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Kostroma cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Koumiss", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Kurt cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Latvian cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Limburger Cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Lithuanian cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Livaro Cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Low-fat cottage cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Low-fat kefir", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Maasdam cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Manchego cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Marble cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Mare's milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Mascarpone cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Melted butter", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Melted chocolate cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Melted milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Mexican cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Milk drink", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Milk whey", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Moscow cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Mozzarella cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Munster cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Nocerino Cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Nut milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Oil spread", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Oltermanni cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Ossetian cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Ostrich eggs", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Paneer cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Parmesan cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Partridge eggs", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Pasteurized milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Pecorino Cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Philadelphia Cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Pickled cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Pickled chicken eggs", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Pickled quail eggs", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Popsicle ice cream", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Poshekhonsky cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Powdered milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Processed cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Protein milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Provolone cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Quail eggs", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Reblochon cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Rennet cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Ricotta cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Rocamadour cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Roquefort cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Rougett Cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Russian cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Ryazhenka", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Saler cheese (Salers)", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Sausage cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Sbrinz cheese (Sbrinz)", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Shubat", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Skimmed milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Skimmed milk powder", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Smoked cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Smoked pigtail cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Smoked suluguni cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Soft cheeses", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Soft goat cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Soft kaymak cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Sour cream", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Sour cream 10% fat content", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Sour cream 15% fat content", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Sour cream 30% fat content", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Sour milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Sour milk cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Soviet cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Sterilized milk", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Stilton Cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Suluguni Cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Suzma", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Swiss cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Tan drink", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Tarak", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Tilsiter cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Tofu cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Turkey egg", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Turtle Eggs", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Uglich cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Varenets", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Whole milk powder", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Yaroslavl cheese", type: .eggsAndDairyProducts),
                            EggsAndDairyProducts(name: "Yogurt", type: .eggsAndDairyProducts)]

