//
//  FishAndSeafoodData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 15.10.2023.
//

import Foundation

let fishAndSeafood = [FoodRealm(name: "Algae", type: .fishAndSeafood, calories: "35"),
                      FoodRealm(name: "Algae dals", type: .fishAndSeafood, calories: "15"),
                      FoodRealm(name: "Algae kanten", type: .fishAndSeafood, calories: "10"),
                      FoodRealm(name: "Algae umi budo", type: .fishAndSeafood, calories: "30"),
                      FoodRealm(name: "Amur fish", type: .fishAndSeafood, calories: "100"),
                      FoodRealm(name: "Anchovies", type: .fishAndSeafood, calories: "155"),
                      FoodRealm(name: "Anchovy paste", type: .fishAndSeafood, calories: "165"),
                      FoodRealm(name: "Anglerfish (sea devil)", type: .fishAndSeafood, calories: "80"),
                      FoodRealm(name: "Artificial caviar", type: .fishAndSeafood, calories: "275"),
                      FoodRealm(name: "Artificial red caviar", type: .fishAndSeafood, calories: "325"),
                      FoodRealm(name: "Asp", type: .fishAndSeafood, calories: "100"),
                      FoodRealm(name: "Balyk from fish", type: .fishAndSeafood, calories: "78"),
                      FoodRealm(name: "Barabulka fish (sultanka)", type: .fishAndSeafood, calories: "78"),
                      FoodRealm(name: "Beldyuga fish", type: .fishAndSeafood, calories: "97"),
                      FoodRealm(name: "Beluga", type: .fishAndSeafood, calories: "120"),
                      FoodRealm(name: "Beluga caviar", type: .fishAndSeafood, calories: "250"),
                      FoodRealm(name: "Berix fish", type: .fishAndSeafood, calories: "85"),
                      FoodRealm(name: "Bester fish", type: .fishAndSeafood, calories: "110"),
                      FoodRealm(name: "Black Caviar", type: .fishAndSeafood, calories: "290"),
                      FoodRealm(name: "Black Cod (Coal fish)", type: .fishAndSeafood, calories: "90"),
                      FoodRealm(name: "Black Sea flounder", type: .fishAndSeafood, calories: "80"),
                      FoodRealm(name: "Black caviar sturgeon", type: .fishAndSeafood, calories: "270"),
                      FoodRealm(name: "Black mullet fish (loban)", type: .fishAndSeafood, calories: "105"),
                      FoodRealm(name: "Blue Crab", type: .fishAndSeafood, calories: "95"),
                      FoodRealm(name: "Bops", type: .fishAndSeafood, calories: "70"),
                      FoodRealm(name: "Bream caviar", type: .fishAndSeafood, calories: "115"),
                      FoodRealm(name: "Brown seaweed", type: .fishAndSeafood, calories: "40"),
                      FoodRealm(name: "Bullfish", type: .fishAndSeafood, calories: "75"),
                      FoodRealm(name: "Burbot fish", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Burbot liver", type: .fishAndSeafood, calories: "130"),
                      FoodRealm(name: "Canned anchovies", type: .fishAndSeafood, calories: "158"),
                      FoodRealm(name: "Canned carp", type: .fishAndSeafood, calories: "109"),
                      FoodRealm(name: "Canned caviar", type: .fishAndSeafood, calories: "260"),
                      FoodRealm(name: "Canned cod", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Canned fish", type: .fishAndSeafood, calories: "120"),
                      FoodRealm(name: "Canned herring", type: .fishAndSeafood, calories: "146"),
                      FoodRealm(name: "Canned mackerel", type: .fishAndSeafood, calories: "144"),
                      FoodRealm(name: "Canned mussels", type: .fishAndSeafood, calories: "75"),
                      FoodRealm(name: "Canned pink salmon", type: .fishAndSeafood, calories: "136"),
                      FoodRealm(name: "Canned salmon (salmon)", type: .fishAndSeafood, calories: "167"),
                      FoodRealm(name: "Canned sardines", type: .fishAndSeafood, calories: "149"),
                      FoodRealm(name: "Canned saury", type: .fishAndSeafood, calories: "111"),
                      FoodRealm(name: "Canned seaweed", type: .fishAndSeafood, calories: "35"),
                      FoodRealm(name: "Canned shrimp", type: .fishAndSeafood, calories: "90"),
                      FoodRealm(name: "Canned sprat", type: .fishAndSeafood, calories: "129"),
                      FoodRealm(name: "Canned sprats", type: .fishAndSeafood, calories: "208"),
                      FoodRealm(name: "Canned squid", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Canned trout", type: .fishAndSeafood, calories: "128"),
                      FoodRealm(name: "Canned tuna", type: .fishAndSeafood, calories: "116"),
                      FoodRealm(name: "Capelin caviar", type: .fishAndSeafood, calories: "143"),
                      FoodRealm(name: "Capelin fish", type: .fishAndSeafood, calories: "93"),
                      FoodRealm(name: "Carp", type: .fishAndSeafood, calories: "126"),
                      FoodRealm(name: "Carp caviar", type: .fishAndSeafood, calories: "115"),
                      FoodRealm(name: "Carp fish", type: .fishAndSeafood, calories: "126"),
                      FoodRealm(name: "Caviar", type: .fishAndSeafood, calories: "270"),
                      FoodRealm(name: "Char", type: .fishAndSeafood, calories: "97"),
                      FoodRealm(name: "Chinook fish", type: .fishAndSeafood, calories: "157"),
                      FoodRealm(name: "Chub fish", type: .fishAndSeafood, calories: "96"),
                      FoodRealm(name: "Chuka seaweed", type: .fishAndSeafood, calories: "10"),
                      FoodRealm(name: "Chukuchan fish", type: .fishAndSeafood, calories: "144"),
                      FoodRealm(name: "Cod caviar", type: .fishAndSeafood, calories: "143"),
                      FoodRealm(name: "Cod fish", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Cod liver", type: .fishAndSeafood, calories: "96"),
                      FoodRealm(name: "Crab meat", type: .fishAndSeafood, calories: "95"),
                      FoodRealm(name: "Crab sausage", type: .fishAndSeafood, calories: "150"),
                      FoodRealm(name: "Crab sticks", type: .fishAndSeafood, calories: "230"),
                      FoodRealm(name: "Crayfish river", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Croaker fish", type: .fishAndSeafood, calories: "97"),
                      FoodRealm(name: "Crucian carp", type: .fishAndSeafood, calories: "105"),
                      FoodRealm(name: "Cucumaria", type: .fishAndSeafood, calories: "55"),
                      FoodRealm(name: "Cuttlefish", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Cuttlefish Ink", type: .fishAndSeafood, calories: "20"),
                      FoodRealm(name: "Dorado fish", type: .fishAndSeafood, calories: "240"),
                      FoodRealm(name: "Dried Squid rings", type: .fishAndSeafood, calories: "335"),
                      FoodRealm(name: "Dried anchovies", type: .fishAndSeafood, calories: "310"),
                      FoodRealm(name: "Dried fish", type: .fishAndSeafood, calories: "240"),
                      FoodRealm(name: "Dried octopus", type: .fishAndSeafood, calories: "380"),
                      FoodRealm(name: "Dried roach", type: .fishAndSeafood, calories: "315"),
                      FoodRealm(name: "Dried sea cabbage", type: .fishAndSeafood, calories: "102"),
                      FoodRealm(name: "Dried squid", type: .fishAndSeafood, calories: "335"),
                      FoodRealm(name: "Dried squid tentacles", type: .fishAndSeafood, calories: "290"),
                      FoodRealm(name: "Dried yellow tabby", type: .fishAndSeafood, calories: "305"),
                      FoodRealm(name: "Fangfish", type: .fishAndSeafood, calories: "90"),
                      FoodRealm(name: "Fish", type: .fishAndSeafood, calories: "110"),
                      FoodRealm(name: "Fish Argentina", type: .fishAndSeafood, calories: "105"),
                      FoodRealm(name: "Fish Chehon", type: .fishAndSeafood, calories: "195"),
                      FoodRealm(name: "Fish Eel", type: .fishAndSeafood, calories: "200"),
                      FoodRealm(name: "Fish Sea Dragon", type: .fishAndSeafood, calories: "85"),
                      FoodRealm(name: "Fish Sea cock", type: .fishAndSeafood, calories: "95"),
                      FoodRealm(name: "Fish Sea language", type: .fishAndSeafood, calories: "90"),
                      FoodRealm(name: "Fish Spike", type: .fishAndSeafood, calories: "110"),
                      FoodRealm(name: "Fish Stingray", type: .fishAndSeafood, calories: "100"),
                      FoodRealm(name: "Fish Tench", type: .fishAndSeafood, calories: "105"),
                      FoodRealm(name: "Fish black cupid", type: .fishAndSeafood, calories: "110"),
                      FoodRealm(name: "Fish bream", type: .fishAndSeafood, calories: "155"),
                      FoodRealm(name: "Fish burgers", type: .fishAndSeafood, calories: "150"),
                      FoodRealm(name: "Fish catfish", type: .fishAndSeafood, calories: "115"),
                      FoodRealm(name: "Fish chir (shchokur)", type: .fishAndSeafood, calories: "79"),
                      FoodRealm(name: "Fish congrio (king clip)", type: .fishAndSeafood, calories: "105"),
                      FoodRealm(name: "Fish fillet", type: .fishAndSeafood, calories: "120"),
                      FoodRealm(name: "Fish fish", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Fish flounder-ruff", type: .fishAndSeafood, calories: "95"),
                      FoodRealm(name: "Fish grouper (merow)", type: .fishAndSeafood, calories: "110"),
                      FoodRealm(name: "Fish hake", type: .fishAndSeafood, calories: "85"),
                      FoodRealm(name: "Fish kumzha", type: .fishAndSeafood, calories: "157"),
                      FoodRealm(name: "Fish loofah", type: .fishAndSeafood, calories: "07"),
                      FoodRealm(name: "Fish mahi-mahi (coryphena)", type: .fishAndSeafood, calories: "110"),
                      FoodRealm(name: "Fish milk", type: .fishAndSeafood, calories: "900"),
                      FoodRealm(name: "Fish oil", type: .fishAndSeafood, calories: "900"),
                      FoodRealm(name: "Fish perch", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Fish ram", type: .fishAndSeafood, calories: "79"),
                      FoodRealm(name: "Fish roll", type: .fishAndSeafood, calories: "185"),
                      FoodRealm(name: "Fish rotan", type: .fishAndSeafood, calories: "105"),
                      FoodRealm(name: "Fish salmon (salmon)", type: .fishAndSeafood, calories: "167"),
                      FoodRealm(name: "Fish sea bream", type: .fishAndSeafood, calories: "110"),
                      FoodRealm(name: "Fish semi-finished products", type: .fishAndSeafood, calories: "150"),
                      FoodRealm(name: "Fish steak", type: .fishAndSeafood, calories: "145"),
                      FoodRealm(name: "Fish straws", type: .fishAndSeafood, calories: "380"),
                      FoodRealm(name: "Fish terpug", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Flying fish", type: .fishAndSeafood, calories: "190"),
                      FoodRealm(name: "Flying fish caviar (Tobiko caviar)", type: .fishAndSeafood, calories: "270"),
                      FoodRealm(name: "Frozen crab meat", type: .fishAndSeafood, calories: "95"),
                      FoodRealm(name: "Frozen fish sticks", type: .fishAndSeafood, calories: "230"),
                      FoodRealm(name: "Frozen sea cocktail", type: .fishAndSeafood, calories: "120"),
                      FoodRealm(name: "Fucus seaweed", type: .fishAndSeafood, calories: "30"),
                      FoodRealm(name: "Grayling fish", type: .fishAndSeafood, calories: "97 "),
                      FoodRealm(name: "Green seaweed", type: .fishAndSeafood, calories: "35 "),
                      FoodRealm(name: "Grouper fish", type: .fishAndSeafood, calories: "110 "),
                      FoodRealm(name: "Gustera fish", type: .fishAndSeafood, calories: "82 "),
                      FoodRealm(name: "Haddock fish", type: .fishAndSeafood, calories: "82 "),
                      FoodRealm(name: "Hake fillet", type: .fishAndSeafood, calories: "85 "),
                      FoodRealm(name: "Halibut caviar", type: .fishAndSeafood, calories: "290 "),
                      FoodRealm(name: "Halibut fish", type: .fishAndSeafood, calories: "90 "),
                      FoodRealm(name: "Hamsa fish", type: .fishAndSeafood, calories: "135 "),
                      FoodRealm(name: "Hawk caviar", type: .fishAndSeafood, calories: "270 "),
                      FoodRealm(name: "Herring fish", type: .fishAndSeafood, calories: "146 "),
                      FoodRealm(name: "Hokkigai mollusk", type: .fishAndSeafood, calories: "40 "),
                      FoodRealm(name: "Horse mackerel fish", type: .fishAndSeafood, calories: "144 "),
                      FoodRealm(name: "Ice fish", type: .fishAndSeafood, calories: "100 "),
                      FoodRealm(name: "Ide fish", type: .fishAndSeafood, calories: "111 "),
                      FoodRealm(name: "Irish moss carrageenan", type: .fishAndSeafood, calories: "10 "),
                      FoodRealm(name: "Kamchatka crab", type: .fishAndSeafood, calories: "100 "),
                      FoodRealm(name: "Keta", type: .fishAndSeafood, calories: "157 "),
                      FoodRealm(name: "King Prawns", type: .fishAndSeafood, calories: "120 "),
                      FoodRealm(name: "Kizhuch", type: .fishAndSeafood, calories: "157 "),
                      FoodRealm(name: "Kombu algae", type: .fishAndSeafood, calories: "35 "),
                      FoodRealm(name: "Krill meat", type: .fishAndSeafood, calories: "86 "),
                      FoodRealm(name: "Lamprey fish", type: .fishAndSeafood, calories: "105"),
                      FoodRealm(name: "Langoustine", type: .fishAndSeafood, calories: "90"),
                      FoodRealm(name: "Langust", type: .fishAndSeafood, calories: "95"),
                      FoodRealm(name: "Lemongrass fish", type: .fishAndSeafood, calories: "110"),
                      FoodRealm(name: "Letrin fish", type: .fishAndSeafood, calories: "85"),
                      FoodRealm(name: "Limu Seaweed", type: .fishAndSeafood, calories: "20"),
                      FoodRealm(name: "Lobster - lobster", type: .fishAndSeafood, calories: "95"),
                      FoodRealm(name: "Mackerel fish", type: .fishAndSeafood, calories: "144"),
                      FoodRealm(name: "Makrurus fish", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Marlin fish", type: .fishAndSeafood, calories: "110"),
                      FoodRealm(name: "Masago Caviar", type: .fishAndSeafood, calories: "330"),
                      FoodRealm(name: "Meat of the trumpeter", type: .fishAndSeafood, calories: "115"),
                      FoodRealm(name: "Minced fish", type: .fishAndSeafood, calories: "140"),
                      FoodRealm(name: "Mini octopuses", type: .fishAndSeafood, calories: "80"),
                      FoodRealm(name: "Mollusc tridacna (sea cicada)", type: .fishAndSeafood, calories: "110"),
                      FoodRealm(name: "Molva fish (sea pike)", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Muksun fish", type: .fishAndSeafood, calories: "79"),
                      FoodRealm(name: "Mullet", type: .fishAndSeafood, calories: "105"),
                      FoodRealm(name: "Mussels", type: .fishAndSeafood, calories: "75"),
                      FoodRealm(name: "Navaga fish", type: .fishAndSeafood, calories: "80"),
                      FoodRealm(name: "Nelma fish", type: .fishAndSeafood, calories: "144"),
                      FoodRealm(name: "Nori chips", type: .fishAndSeafood, calories: "410"),
                      FoodRealm(name: "Nori seaweed", type: .fishAndSeafood, calories: "35"),
                      FoodRealm(name: "Notesreferences", type: .fishAndSeafood, calories: "-"),
                      FoodRealm(name: "Octopus", type: .fishAndSeafood, calories: "80"),
                      FoodRealm(name: "Oil fish", type: .fishAndSeafood, calories: "167"),
                      FoodRealm(name: "Omul fish", type: .fishAndSeafood, calories: "157"),
                      FoodRealm(name: "Oyster", type: .fishAndSeafood, calories: "65"),
                      FoodRealm(name: "Pangasius fillet", type: .fishAndSeafood, calories: "110"),
                      FoodRealm(name: "Pangasius fish", type: .fishAndSeafood, calories: "105"),
                      FoodRealm(name: "Parrot fish", type: .fishAndSeafood, calories: "115"),
                      FoodRealm(name: "Pelamida fish", type: .fishAndSeafood, calories: "127"),
                      FoodRealm(name: "Pelengas fish", type: .fishAndSeafood, calories: "93"),
                      FoodRealm(name: "Pickled capelin", type: .fishAndSeafood, calories: "158"),
                      FoodRealm(name: "Pickled carp", type: .fishAndSeafood, calories: "119"),
                      FoodRealm(name: "Pickled catfish", type: .fishAndSeafood, calories: "130"),
                      FoodRealm(name: "Pickled crucian carp", type: .fishAndSeafood, calories: "120"),
                      FoodRealm(name: "Pickled fish", type: .fishAndSeafood, calories: "130"),
                      FoodRealm(name: "Pickled herring", type: .fishAndSeafood, calories: "180"),
                      FoodRealm(name: "Pickled lamprey", type: .fishAndSeafood, calories: "155"),
                      FoodRealm(name: "Pickled mackerel", type: .fishAndSeafood, calories: "170"),
                      FoodRealm(name: "Pickled mussels", type: .fishAndSeafood, calories: "110"),
                      FoodRealm(name: "Pickled octopuses", type: .fishAndSeafood, calories: "145"),
                      FoodRealm(name: "Pickled pike", type: .fishAndSeafood, calories: "139"),
                      FoodRealm(name: "Pickled salmon (salmon)", type: .fishAndSeafood, calories: "180"),
                      FoodRealm(name: "Pickled shrimp", type: .fishAndSeafood, calories: "120"),
                      FoodRealm(name: "Pickled silver carp", type: .fishAndSeafood, calories: "119"),
                      FoodRealm(name: "Pickled squid", type: .fishAndSeafood, calories: "140"),
                      FoodRealm(name: "Pickled trout", type: .fishAndSeafood, calories: "175"),
                      FoodRealm(name: "Pike caviar", type: .fishAndSeafood, calories: "270"),
                      FoodRealm(name: "Pike fish", type: .fishAndSeafood, calories: "94"),
                      FoodRealm(name: "Pike perch fish", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Pink salmon", type: .fishAndSeafood, calories: "136"),
                      FoodRealm(name: "Pink salmon caviar", type: .fishAndSeafood, calories: "270"),
                      FoodRealm(name: "Pollock caviar", type: .fishAndSeafood, calories: "143"),
                      FoodRealm(name: "Pollock fillet", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Pollock fish", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Pollock liver", type: .fishAndSeafood, calories: "96"),
                      FoodRealm(name: "Porphyry algae", type: .fishAndSeafood, calories: "15"),
                      FoodRealm(name: "Puffer fish", type: .fishAndSeafood, calories: "110"),
                      FoodRealm(name: "Rainbow trout fish", type: .fishAndSeafood, calories: "128"),
                      FoodRealm(name: "Rapana clam", type: .fishAndSeafood, calories: "115"),
                      FoodRealm(name: "Red caviar", type: .fishAndSeafood, calories: "270"),
                      FoodRealm(name: "Red caviar of chum salmon", type: .fishAndSeafood, calories: "290"),
                      FoodRealm(name: "Red seaweed", type: .fishAndSeafood, calories: "25"),
                      FoodRealm(name: "Red-eyed fish", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Roach fish", type: .fishAndSeafood, calories: "94"),
                      FoodRealm(name: "Rudd fish", type: .fishAndSeafood, calories: "105"),
                      FoodRealm(name: "Ruff", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Ryapushka fish", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Saber Fish", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Saida fish", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Salmon bellies", type: .fishAndSeafood, calories: "180"),
                      FoodRealm(name: "Salmon minced meat", type: .fishAndSeafood, calories: "135"),
                      FoodRealm(name: "Salmon ridges", type: .fishAndSeafood, calories: "190"),
                      FoodRealm(name: "Salmon steak (salmon)", type: .fishAndSeafood, calories: "167"),
                      FoodRealm(name: "Salted capelin", type: .fishAndSeafood, calories: "158"),
                      FoodRealm(name: "Salted fish", type: .fishAndSeafood, calories: "150"),
                      FoodRealm(name: "Salted hamsa", type: .fishAndSeafood, calories: "160"),
                      FoodRealm(name: "Salted mackerel", type: .fishAndSeafood, calories: "180"),
                      FoodRealm(name: "Salted pink salmon", type: .fishAndSeafood, calories: "170"),
                      FoodRealm(name: "Salted salmon", type: .fishAndSeafood, calories: "180"),
                      FoodRealm(name: "Salted straw", type: .fishAndSeafood, calories: "380"),
                      FoodRealm(name: "Salted trout", type: .fishAndSeafood, calories: "175"),
                      FoodRealm(name: "Salty tuna", type: .fishAndSeafood, calories: "116"),
                      FoodRealm(name: "Salty tyulka", type: .fishAndSeafood, calories: "105"),
                      FoodRealm(name: "Sardine fish", type: .fishAndSeafood, calories: "149"),
                      FoodRealm(name: "Saury fish", type: .fishAndSeafood, calories: "111"),
                      FoodRealm(name: "Scallop", type: .fishAndSeafood, calories: "75"),
                      FoodRealm(name: "Scomber fish", type: .fishAndSeafood, calories: "144"),
                      FoodRealm(name: "Sea Urchin caviar", type: .fishAndSeafood, calories: "55"),
                      FoodRealm(name: "Sea acorn balanus", type: .fishAndSeafood, calories: "80"),
                      FoodRealm(name: "Sea bass fish", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Sea cabbage (Kelp)", type: .fishAndSeafood, calories: "43"),
                      FoodRealm(name: "Sea ear", type: .fishAndSeafood, calories: "60"),
                      FoodRealm(name: "Sea urchins", type: .fishAndSeafood, calories: "55"),
                      FoodRealm(name: "Sevryuga fish", type: .fishAndSeafood, calories: "167"),
                      FoodRealm(name: "Shark Meat", type: .fishAndSeafood, calories: "200"),
                      FoodRealm(name: "Shark fins", type: .fishAndSeafood, calories: "390"),
                      FoodRealm(name: "Shark katran", type: .fishAndSeafood, calories: "300"),
                      FoodRealm(name: "Shellfish", type: .fishAndSeafood, calories: "80"),
                      FoodRealm(name: "Shellfish caviar", type: .fishAndSeafood, calories: "250"),
                      FoodRealm(name: "Shem fish", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Shrimp", type: .fishAndSeafood, calories: "90"),
                      FoodRealm(name: "Silver carp caviar", type: .fishAndSeafood, calories: "143"),
                      FoodRealm(name: "Silver carp fish", type: .fishAndSeafood, calories: "110"),
                      FoodRealm(name: "Smelt fish", type: .fishAndSeafood, calories: "88"),
                      FoodRealm(name: "Smoked bream", type: .fishAndSeafood, calories: "145"),
                      FoodRealm(name: "Smoked capelin", type: .fishAndSeafood, calories: "170"),
                      FoodRealm(name: "Smoked cod", type: .fishAndSeafood, calories: "150"),
                      FoodRealm(name: "Smoked eel", type: .fishAndSeafood, calories: "208"),
                      FoodRealm(name: "Smoked fish", type: .fishAndSeafood, calories: "145"),
                      FoodRealm(name: "Smoked herring", type: .fishAndSeafood, calories: "180"),
                      FoodRealm(name: "Smoked horse mackerel", type: .fishAndSeafood, calories: "170"),
                      FoodRealm(name: "Smoked mackerel", type: .fishAndSeafood, calories: "170"),
                      FoodRealm(name: "Smoked pink salmon", type: .fishAndSeafood, calories: "158"),
                      FoodRealm(name: "Smoked salmon", type: .fishAndSeafood, calories: "158"),
                      FoodRealm(name: "Smoked sprat", type: .fishAndSeafood, calories: "180"),
                      FoodRealm(name: "Smoked squid", type: .fishAndSeafood, calories: "140"),
                      FoodRealm(name: "Smoked sterlet", type: .fishAndSeafood, calories: "170"),
                      FoodRealm(name: "Smoked tuna", type: .fishAndSeafood, calories: "116"),
                      FoodRealm(name: "Snail caviar", type: .fishAndSeafood, calories: "290"),
                      FoodRealm(name: "Sockeye salmon", type: .fishAndSeafood, calories: "157"),
                      FoodRealm(name: "Spirulina algae", type: .fishAndSeafood, calories: "260"),
                      FoodRealm(name: "Sprat", type: .fishAndSeafood, calories: "208"),
                      FoodRealm(name: "Sprat fish", type: .fishAndSeafood, calories: "129"),
                      FoodRealm(name: "Sprat in tomato sauce", type: .fishAndSeafood, calories: "115"),
                      FoodRealm(name: "Sprat of spicy salting", type: .fishAndSeafood, calories: "210"),
                      FoodRealm(name: "Sprat pate", type: .fishAndSeafood, calories: "250"),
                      FoodRealm(name: "Sprats fish", type: .fishAndSeafood, calories: "208"),
                      FoodRealm(name: "Squid", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Squid Rings", type: .fishAndSeafood, calories: "335"),
                      FoodRealm(name: "Squid Tentacle", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Steers in tomato sauce", type: .fishAndSeafood, calories: "120"),
                      FoodRealm(name: "Sterlet fish", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Stroganina from fish", type: .fishAndSeafood, calories: "120"),
                      FoodRealm(name: "Sturgeon fish", type: .fishAndSeafood, calories: "110"),
                      FoodRealm(name: "Sunfish", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Surimi", type: .fishAndSeafood, calories: "250"),
                      FoodRealm(name: "Swordfish", type: .fishAndSeafood, calories: "125"),
                      FoodRealm(name: "Taimen fish", type: .fishAndSeafood, calories: "144"),
                      FoodRealm(name: "Tiger Prawns", type: .fishAndSeafood, calories: "90"),
                      FoodRealm(name: "Tilapia fillet", type: .fishAndSeafood, calories: "96"),
                      FoodRealm(name: "Tilapia fish", type: .fishAndSeafood, calories: "96"),
                      FoodRealm(name: "Trepang", type: .fishAndSeafood, calories: "55"),
                      FoodRealm(name: "Trout fish", type: .fishAndSeafood, calories: "128"),
                      FoodRealm(name: "Tuna", type: .fishAndSeafood, calories: "116"),
                      FoodRealm(name: "Tuna shavings", type: .fishAndSeafood, calories: "116"),
                      FoodRealm(name: "Turbot fish", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Turtle meat", type: .fishAndSeafood, calories: "200"),
                      FoodRealm(name: "Tyulka fish", type: .fishAndSeafood, calories: "105"),
                      FoodRealm(name: "Ulva seaweed (Sea salad)", type: .fishAndSeafood, calories: "16"),
                      FoodRealm(name: "Venus clam (vongole)", type: .fishAndSeafood, calories: "75"),
                      FoodRealm(name: "Visiga", type: .fishAndSeafood, calories: "300"),
                      FoodRealm(name: "Vobla", type: .fishAndSeafood, calories: "97"),
                      FoodRealm(name: "Wakame seaweed", type: .fishAndSeafood, calories: "45"),
                      FoodRealm(name: "Walleye caviar", type: .fishAndSeafood, calories: "280"),
                      FoodRealm(name: "Whale meat", type: .fishAndSeafood, calories: "170"),
                      FoodRealm(name: "White caviar", type: .fishAndSeafood, calories: "290"),
                      FoodRealm(name: "White-eyed fish", type: .fishAndSeafood, calories: "79"),
                      FoodRealm(name: "Whitefish", type: .fishAndSeafood, calories: "144"),
                      FoodRealm(name: "Whitefish fish", type: .fishAndSeafood, calories: "144"),
                      FoodRealm(name: "Whiting", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Whiting fish", type: .fishAndSeafood, calories: "82"),
                      FoodRealm(name: "Yabbi", type: .fishAndSeafood, calories: "75"),
                      FoodRealm(name: "Yellow striped fish", type: .fishAndSeafood, calories: "135"),
                      FoodRealm(name: "Yellowtail fish (lacedra)", type: .fishAndSeafood, calories: "108"),
                      FoodRealm(name: "Zuban fish", type: .fishAndSeafood, calories: "82")]

