//
//  FlourAndBakeryProductsData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 16.10.2023.
//

import Foundation

let flourAndBakeryProducts = [FlourAndBakeryProducts(name: "Agnolotti", type: .flourAndBakeryProducts, calories: "270"),
                              FlourAndBakeryProducts(name: "Amaranth flour", type: .flourAndBakeryProducts, calories: "325"),
                              FlourAndBakeryProducts(name: "Armenian lavash", type: .flourAndBakeryProducts, calories: "265"),
                              FlourAndBakeryProducts(name: "Bagel", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Bagels (drying)", type: .flourAndBakeryProducts, calories: "380"),
                              FlourAndBakeryProducts(name: "Baguette", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Banana bread", type: .flourAndBakeryProducts, calories: "247"),
                              FlourAndBakeryProducts(name: "Barley flour", type: .flourAndBakeryProducts, calories: "322"),
                              FlourAndBakeryProducts(name: "Bavette pasta", type: .flourAndBakeryProducts, calories: "131"),
                              FlourAndBakeryProducts(name: "Biscuit crumb", type: .flourAndBakeryProducts, calories: "455"),
                              FlourAndBakeryProducts(name: "Black bread", type: .flourAndBakeryProducts, calories: "235"),
                              FlourAndBakeryProducts(name: "Boraki", type: .flourAndBakeryProducts, calories: "268"),
                              FlourAndBakeryProducts(name: "Borodino bread", type: .flourAndBakeryProducts, calories: "235"),
                              FlourAndBakeryProducts(name: "Bread", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Bread crumbs", type: .flourAndBakeryProducts, calories: "380"),
                              FlourAndBakeryProducts(name: "Bread for toast", type: .flourAndBakeryProducts, calories: "235"),
                              FlourAndBakeryProducts(name: "Bread grey", type: .flourAndBakeryProducts, calories: "235"),
                              FlourAndBakeryProducts(name: "Bread rolls", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Bread sticks", type: .flourAndBakeryProducts, calories: "380"),
                              FlourAndBakeryProducts(name: "Bread with bran", type: .flourAndBakeryProducts, calories: "235"),
                              FlourAndBakeryProducts(name: "Bread with dried fruits", type: .flourAndBakeryProducts, calories: "247"),
                              FlourAndBakeryProducts(name: "Bread with seeds", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Breadcrumbs with raisins", type: .flourAndBakeryProducts, calories: "380"),
                              FlourAndBakeryProducts(name: "Brezel", type: .flourAndBakeryProducts, calories: "380"),
                              FlourAndBakeryProducts(name: "Brioche bun", type: .flourAndBakeryProducts, calories: "270"),
                              FlourAndBakeryProducts(name: "Bruschetta", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Bucatini", type: .flourAndBakeryProducts, calories: "131"),
                              FlourAndBakeryProducts(name: "Buckwheat bread", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Buckwheat flour", type: .flourAndBakeryProducts, calories: "329"),
                              FlourAndBakeryProducts(name: "Buckwheat loaves", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Buckwheat noodles", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "Buns", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Buns buns", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Butter buns", type: .flourAndBakeryProducts, calories: "270"),
                              FlourAndBakeryProducts(name: "Cakes for honey cake", type: .flourAndBakeryProducts, calories: "335"),
                              FlourAndBakeryProducts(name: "Cannelloni", type: .flourAndBakeryProducts, calories: "220"),
                              FlourAndBakeryProducts(name: "Chapati", type: .flourAndBakeryProducts, calories: "265"),
                              FlourAndBakeryProducts(name: "Cheese tortilla", type: .flourAndBakeryProducts, calories: "265"),
                              FlourAndBakeryProducts(name: "Cheesecake", type: .flourAndBakeryProducts, calories: "335"),
                              FlourAndBakeryProducts(name: "Chickpea flour", type: .flourAndBakeryProducts, calories: "364"),
                              FlourAndBakeryProducts(name: "Chipette", type: .flourAndBakeryProducts, calories: "270"),
                              FlourAndBakeryProducts(name: "Chips", type: .flourAndBakeryProducts, calories: "380"),
                              FlourAndBakeryProducts(name: "Chopped dough", type: .flourAndBakeryProducts, calories: "300"),
                              FlourAndBakeryProducts(name: "Ciabatta", type: .flourAndBakeryProducts, calories: "265"),
                              FlourAndBakeryProducts(name: "Coconut flour", type: .flourAndBakeryProducts, calories: "197"),
                              FlourAndBakeryProducts(name: "Corn Tortilla", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "Corn bread", type: .flourAndBakeryProducts, calories: "235"),
                              FlourAndBakeryProducts(name: "Corn flour", type: .flourAndBakeryProducts, calories: "358"),
                              FlourAndBakeryProducts(name: "Corn loaves", type: .flourAndBakeryProducts, calories: "235"),
                              FlourAndBakeryProducts(name: "Crackers", type: .flourAndBakeryProducts, calories: "380"),
                              FlourAndBakeryProducts(name: "Croissant", type: .flourAndBakeryProducts, calories: "330"),
                              FlourAndBakeryProducts(name: "Croutons", type: .flourAndBakeryProducts, calories: "380"),
                              FlourAndBakeryProducts(name: "Cupcakes muffins", type: .flourAndBakeryProducts, calories: "350"),
                              FlourAndBakeryProducts(name: "Dough", type: .flourAndBakeryProducts, calories: "300"),
                              FlourAndBakeryProducts(name: "Dough for dumplings", type: .flourAndBakeryProducts, calories: "300"),
                              FlourAndBakeryProducts(name: "Dough-boy", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Dumplings", type: .flourAndBakeryProducts, calories: "120"),
                              FlourAndBakeryProducts(name: "Dumplings with garlic", type: .flourAndBakeryProducts, calories: "120"),
                              FlourAndBakeryProducts(name: "Egg noodles", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "English Christmas Cupcake", type: .flourAndBakeryProducts, calories: "335"),
                              FlourAndBakeryProducts(name: "Farfalle pasta", type: .flourAndBakeryProducts, calories: "131"),
                              FlourAndBakeryProducts(name: "Fatir", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Fettuccine", type: .flourAndBakeryProducts, calories: "131"),
                              FlourAndBakeryProducts(name: "Filo dough", type: .flourAndBakeryProducts, calories: "330"),
                              FlourAndBakeryProducts(name: "Flaxseed flour", type: .flourAndBakeryProducts, calories: "354"),
                              FlourAndBakeryProducts(name: "Flour mixture", type: .flourAndBakeryProducts, calories: "350"),
                              FlourAndBakeryProducts(name: "Focaccia", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Fritters", type: .flourAndBakeryProducts, calories: "200"),
                              FlourAndBakeryProducts(name: "Funchosa noodles", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "Garlic bread", type: .flourAndBakeryProducts, calories: "270"),
                              FlourAndBakeryProducts(name: "Gingerbread dough", type: .flourAndBakeryProducts, calories: "300"),
                              FlourAndBakeryProducts(name: "Grain bread", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Grissini", type: .flourAndBakeryProducts, calories: "380"),
                              FlourAndBakeryProducts(name: "Hala Bread", type: .flourAndBakeryProducts, calories: "265"),
                              FlourAndBakeryProducts(name: "Hamburger buns", type: .flourAndBakeryProducts, calories: "270"),
                              FlourAndBakeryProducts(name: "Hard chuck", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Harusame noodles", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "Homemade bread", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Hot dog buns", type: .flourAndBakeryProducts, calories: "270"),
                              FlourAndBakeryProducts(name: "Instant noodles", type: .flourAndBakeryProducts, calories: "355"),
                              FlourAndBakeryProducts(name: "Italian pasta", type: .flourAndBakeryProducts, calories: "131"),
                              FlourAndBakeryProducts(name: "Kadaif dough", type: .flourAndBakeryProducts, calories: "330"),
                              FlourAndBakeryProducts(name: "Kalach", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Khinkali", type: .flourAndBakeryProducts, calories: "120"),
                              FlourAndBakeryProducts(name: "Kulebyaki pies", type: .flourAndBakeryProducts, calories: "300"),
                              FlourAndBakeryProducts(name: "Lasagna sheets", type: .flourAndBakeryProducts, calories: "220"),
                              FlourAndBakeryProducts(name: "Lavash", type: .flourAndBakeryProducts, calories: "265"),
                              FlourAndBakeryProducts(name: "Lentil flour", type: .flourAndBakeryProducts, calories: "321"),
                              FlourAndBakeryProducts(name: "Linguine (linguine)", type: .flourAndBakeryProducts, calories: "131"),
                              FlourAndBakeryProducts(name: "Loaf", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Long loaf", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Mafaldine", type: .flourAndBakeryProducts, calories: "131"),
                              FlourAndBakeryProducts(name: "Malt bread", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Matzo", type: .flourAndBakeryProducts, calories: "355"),
                              FlourAndBakeryProducts(name: "Muffin", type: .flourAndBakeryProducts, calories: "300"),
                              FlourAndBakeryProducts(name: "Noodles", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "Nut flour", type: .flourAndBakeryProducts, calories: "625"),
                              FlourAndBakeryProducts(name: "Oat flour", type: .flourAndBakeryProducts, calories: "389"),
                              FlourAndBakeryProducts(name: "Oatmeal bread", type: .flourAndBakeryProducts, calories: "235"),
                              FlourAndBakeryProducts(name: "Oatmeal loaves", type: .flourAndBakeryProducts, calories: "235"),
                              FlourAndBakeryProducts(name: "Pampushki", type: .flourAndBakeryProducts, calories: "270"),
                              FlourAndBakeryProducts(name: "Pancakes", type: .flourAndBakeryProducts, calories: "210"),
                              FlourAndBakeryProducts(name: "Pancakes (American pancakes)", type: .flourAndBakeryProducts, calories: "210"),
                              FlourAndBakeryProducts(name: "Papardelle", type: .flourAndBakeryProducts, calories: "131"),
                              FlourAndBakeryProducts(name: "Pasta", type: .flourAndBakeryProducts, calories: "131"),
                              FlourAndBakeryProducts(name: "Pasta capellini", type: .flourAndBakeryProducts, calories: "131"),
                              FlourAndBakeryProducts(name: "Pasta conciglioni", type: .flourAndBakeryProducts, calories: "131"),
                              FlourAndBakeryProducts(name: "Pasta horns", type: .flourAndBakeryProducts, calories: "131"),
                              FlourAndBakeryProducts(name: "Pasta orzo (Risoni)", type: .flourAndBakeryProducts, calories: "131"),
                              FlourAndBakeryProducts(name: "Pasta shells", type: .flourAndBakeryProducts, calories: "131"),
                              FlourAndBakeryProducts(name: "Pasta spiral", type: .flourAndBakeryProducts, calories: "131"),
                              FlourAndBakeryProducts(name: "Pattyes", type: .flourAndBakeryProducts, calories: "300"),
                              FlourAndBakeryProducts(name: "Pea flour", type: .flourAndBakeryProducts, calories: "314"),
                              FlourAndBakeryProducts(name: "Peeled rye flour", type: .flourAndBakeryProducts, calories: "338"),
                              FlourAndBakeryProducts(name: "Penne Pasta", type: .flourAndBakeryProducts, calories: "131"),
                              FlourAndBakeryProducts(name: "Pete", type: .flourAndBakeryProducts, calories: "268"),
                              FlourAndBakeryProducts(name: "Pies", type: .flourAndBakeryProducts, calories: "335"),
                              FlourAndBakeryProducts(name: "Plait", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Premium wheat flour", type: .flourAndBakeryProducts, calories: "348"),
                              FlourAndBakeryProducts(name: "Pretzel", type: .flourAndBakeryProducts, calories: "380"),
                              FlourAndBakeryProducts(name: "Profiteroles", type: .flourAndBakeryProducts, calories: "300"),
                              FlourAndBakeryProducts(name: "Puff pastry", type: .flourAndBakeryProducts, calories: "455"),
                              FlourAndBakeryProducts(name: "Puff tongues", type: .flourAndBakeryProducts, calories: "300"),
                              FlourAndBakeryProducts(name: "Pumpernickel bread", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Pumpkin flour", type: .flourAndBakeryProducts, calories: "357"),
                              FlourAndBakeryProducts(name: "Ramen noodles", type: .flourAndBakeryProducts, calories: "355"),
                              FlourAndBakeryProducts(name: "Ravioli", type: .flourAndBakeryProducts, calories: "270"),
                              FlourAndBakeryProducts(name: "Rice flour", type: .flourAndBakeryProducts, calories: "365"),
                              FlourAndBakeryProducts(name: "Rice noodles", type: .flourAndBakeryProducts, calories: "365"),
                              FlourAndBakeryProducts(name: "Rice paper", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "Rigatoni pasta", type: .flourAndBakeryProducts, calories: "131"),
                              FlourAndBakeryProducts(name: "Roti tortillas", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "Rye bread", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Rye bread rolls", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Rye crackers", type: .flourAndBakeryProducts, calories: "380"),
                              FlourAndBakeryProducts(name: "Rye flour", type: .flourAndBakeryProducts, calories: "338"),
                              FlourAndBakeryProducts(name: "Rye flour wallpaper", type: .flourAndBakeryProducts, calories: "338"),
                              FlourAndBakeryProducts(name: "Rye seed flour", type: .flourAndBakeryProducts, calories: "338"),
                              FlourAndBakeryProducts(name: "Rye-wheat flour", type: .flourAndBakeryProducts, calories: "338"),
                              FlourAndBakeryProducts(name: "Sayka", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Sesame flour", type: .flourAndBakeryProducts, calories: "563"),
                              FlourAndBakeryProducts(name: "Shangi", type: .flourAndBakeryProducts, calories: "265"),
                              FlourAndBakeryProducts(name: "Shortbread dough", type: .flourAndBakeryProducts, calories: "455"),
                              FlourAndBakeryProducts(name: "Snack bars", type: .flourAndBakeryProducts, calories: "380"),
                              FlourAndBakeryProducts(name: "Soba noodles", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "Sochnik", type: .flourAndBakeryProducts, calories: "268"),
                              FlourAndBakeryProducts(name: "Soy bread", type: .flourAndBakeryProducts, calories: "265"),
                              FlourAndBakeryProducts(name: "Soy flour", type: .flourAndBakeryProducts, calories: "353"),
                              FlourAndBakeryProducts(name: "Spaghetti", type: .flourAndBakeryProducts, calories: "131"),
                              FlourAndBakeryProducts(name: "Spaghettini", type: .flourAndBakeryProducts, calories: "131"),
                              FlourAndBakeryProducts(name: "Spiderweb vermicelli", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "Steering wheels", type: .flourAndBakeryProducts, calories: "380"),
                              FlourAndBakeryProducts(name: "Sunflower flour", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "Sweet straw", type: .flourAndBakeryProducts, calories: "380"),
                              FlourAndBakeryProducts(name: "Taco tortillas", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "Tagliatelle", type: .flourAndBakeryProducts, calories: "131"),
                              FlourAndBakeryProducts(name: "Tartlets", type: .flourAndBakeryProducts, calories: "300"),
                              FlourAndBakeryProducts(name: "Tempura flour", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "Toast", type: .flourAndBakeryProducts, calories: "235"),
                              FlourAndBakeryProducts(name: "Tortilla", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "Tortillas", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "Triticale flour", type: .flourAndBakeryProducts, calories: "338"),
                              FlourAndBakeryProducts(name: "Udon noodles", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "Unleavened dough", type: .flourAndBakeryProducts, calories: "300"),
                              FlourAndBakeryProducts(name: "Vareniki", type: .flourAndBakeryProducts, calories: "120"),
                              FlourAndBakeryProducts(name: "Vermicelli", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "Volovan", type: .flourAndBakeryProducts, calories: "268"),
                              FlourAndBakeryProducts(name: "Waffle cakes", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Wallpaper wheat flour", type: .flourAndBakeryProducts, calories: "348"),
                              FlourAndBakeryProducts(name: "Wheat bread", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Wheat flour", type: .flourAndBakeryProducts, calories: "348"),
                              FlourAndBakeryProducts(name: "Wheat flour of the first grade", type: .flourAndBakeryProducts, calories: "348"),
                              FlourAndBakeryProducts(name: "Wheat flour of the second grade", type: .flourAndBakeryProducts, calories: "348"),
                              FlourAndBakeryProducts(name: "Wheat germ flour", type: .flourAndBakeryProducts, calories: "357"),
                              FlourAndBakeryProducts(name: "Wheat loaves", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Wheat noodles", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "Wheat tortilla", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "White bread", type: .flourAndBakeryProducts, calories: "250"),
                              FlourAndBakeryProducts(name: "Whole grain rye-wheat noodles", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "Whole wheat vermicelli", type: .flourAndBakeryProducts, calories: "360"),
                              FlourAndBakeryProducts(name: "Yeast dough", type: .flourAndBakeryProducts, calories: "300"),
                              FlourAndBakeryProducts(name: "Yeast puff pastry", type: .flourAndBakeryProducts, calories: "455"),
                              FlourAndBakeryProducts(name: "Yeast-free bread", type: .flourAndBakeryProducts, calories: "235"),
                              FlourAndBakeryProducts(name: "Yeast-free dough", type: .flourAndBakeryProducts, calories: "300"),
                              FlourAndBakeryProducts(name: "Yufka", type: .flourAndBakeryProducts, calories: "330"),
                              FlourAndBakeryProducts(name: "Ziti Paste", type: .flourAndBakeryProducts, calories: "131")]

