//
//  FoodData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 21.05.2022.
//

import Foundation

let vegitables = [Vegetables(name: "Adzuki beans", type: .vegetables),
                  Vegetables(name: "African bird's eye chili", type: .vegetables),
                  Vegetables(name: "African horned cucumber", type: .vegetables),
                  Vegetables(name: "Ancho", type: .vegetables),
                  Vegetables(name: "Apple pepper", type: .vegetables),
                  Vegetables(name: "Artichoke", type: .vegetables),
                  Vegetables(name: "Baby carrots", type: .vegetables),
                  Vegetables(name: "Baby corn", type: .vegetables),
                  Vegetables(name: "Bean sprouts", type: .vegetables),
                  Vegetables(name: "Beans", type: .vegetables),
                  Vegetables(name: "Beetroot", type: .vegetables),
                  Vegetables(name: "Bell pepper", type: .vegetables),
                  Vegetables(name: "Beluga lentils", type: .vegetables),
                  Vegetables(name: "Bitter melon", type: .vegetables),
                  Vegetables(name: "Black beans", type: .vegetables),
                  Vegetables(name: "Black garlic", type: .vegetables),
                  Vegetables(name: "Black olives", type: .vegetables),
                  Vegetables(name: "Black radish", type: .vegetables),
                  Vegetables(name: "Black salsify", type: .vegetables),
                  Vegetables(name: "Boiled beetroot", type: .vegetables),
                  Vegetables(name: "Boiled carrots", type: .vegetables),
                  Vegetables(name: "Boiled potatoes", type: .vegetables),
                  Vegetables(name: "Bottle gourd", type: .vegetables),
                  Vegetables(name: "Breadfruit", type: .vegetables),
                  Vegetables(name: "Broccoli", type: .vegetables),
                  Vegetables(name: "Brussels sprouts", type: .vegetables),
                  Vegetables(name: "Burdock root", type: .vegetables),
                  Vegetables(name: "Butternut squash", type: .vegetables),
                  Vegetables(name: "Cabbage pak choi", type: .vegetables),
                  Vegetables(name: "Cabbage", type: .vegetables),
                  Vegetables(name: "Canned beans in tomato sauce", type: .vegetables),
                  Vegetables(name: "Canned beans", type: .vegetables),
                  Vegetables(name: "Canned beets", type: .vegetables),
                  Vegetables(name: "Canned black olives", type: .vegetables),
                  Vegetables(name: "Canned broad beans", type: .vegetables),
                  Vegetables(name: "Canned cabbage", type: .vegetables),
                  Vegetables(name: "Canned carrots", type: .vegetables),
                  Vegetables(name: "Canned cauliflower", type: .vegetables),
                  Vegetables(name: "Canned celery", type: .vegetables),
                  Vegetables(name: "Canned cherry tomatoes", type: .vegetables),
                  Vegetables(name: "Canned corn cobs", type: .vegetables),
                  Vegetables(name: "Canned cucumbers", type: .vegetables),
                  Vegetables(name: "Canned eggplants", type: .vegetables),
                  Vegetables(name: "Canned gherkins", type: .vegetables),
                  Vegetables(name: "Canned green beans", type: .vegetables),
                  Vegetables(name: "Canned green peas", type: .vegetables),
                  Vegetables(name: "Canned green tomatoes", type: .vegetables),
                  Vegetables(name: "Canned kidney beans", type: .vegetables),
                  Vegetables(name: "Canned lentils", type: .vegetables),
                  Vegetables(name: "Canned olives", type: .vegetables),
                  Vegetables(name: "Canned onions", type: .vegetables),
                  Vegetables(name: "Canned radish", type: .vegetables),
                  Vegetables(name: "Canned squash", type: .vegetables),
                  Vegetables(name: "Canned sweet pepper", type: .vegetables),
                  Vegetables(name: "Canned tomatoes", type: .vegetables),
                  Vegetables(name: "Canned vegetables", type: .vegetables),
                  Vegetables(name: "Canned white beans", type: .vegetables),
                  Vegetables(name: "Canned whole tomatoes", type: .vegetables),
                  Vegetables(name: "Canned zucchini", type: .vegetables),
                  Vegetables(name: "Cape gooseberry", type: .vegetables),
                  Vegetables(name: "Carrot sticks", type: .vegetables),
                  Vegetables(name: "Carrot", type: .vegetables),
                  Vegetables(name: "Cayenne pepper", type: .vegetables),
                  Vegetables(name: "Celery root", type: .vegetables),
                  Vegetables(name: "Cherry tomatoes", type: .vegetables),
                  Vegetables(name: "Chili pepper", type: .vegetables),
                  Vegetables(name: "Chinese cabbage", type: .vegetables),
                  Vegetables(name: "Chinese cucumber", type: .vegetables),
                  Vegetables(name: "Chinese radish", type: .vegetables),
                  Vegetables(name: "Chipotle pepper", type: .vegetables),
                  Vegetables(name: "Chives", type: .vegetables),
                  Vegetables(name: "Colchic kole", type: .vegetables),
                  Vegetables(name: "Colorful cabbage", type: .vegetables),
                  Vegetables(name: "Cooked lentils", type: .vegetables),
                  Vegetables(name: "Corn on the cob", type: .vegetables),
                  Vegetables(name: "Corn", type: .vegetables),
                  Vegetables(name: "Cowpea", type: .vegetables),
                  Vegetables(name: "Cucumber", type: .vegetables),
                  Vegetables(name: "Daikon", type: .vegetables),
                  Vegetables(name: "Dried beets", type: .vegetables),
                  Vegetables(name: "Dried cabbage", type: .vegetables),
                  Vegetables(name: "Dried horseradish", type: .vegetables),
                  Vegetables(name: "Dried potatoes", type: .vegetables),
                  Vegetables(name: "Dried vegetables", type: .vegetables),
                  Vegetables(name: "Edamame", type: .vegetables),
                  Vegetables(name: "Eggplant", type: .vegetables),
                  Vegetables(name: "Fried onions", type: .vegetables),
                  Vegetables(name: "Fried potatoes", type: .vegetables),
                  Vegetables(name: "Frozen french fries", type: .vegetables),
                  Vegetables(name: "Frozen vegetable mix", type: .vegetables),
                  Vegetables(name: "Garden radish", type: .vegetables),
                  Vegetables(name: "Garlic", type: .vegetables),
                  Vegetables(name: "Gherkin", type: .vegetables),
                  Vegetables(name: "Glazed carrots", type: .vegetables),
                  Vegetables(name: "Green beans", type: .vegetables),
                  Vegetables(name: "Green garlic", type: .vegetables),
                  Vegetables(name: "Green peas", type: .vegetables),
                  Vegetables(name: "Green tomatoes", type: .vegetables),
                  Vegetables(name: "Habanero pepper", type: .vegetables),
                  Vegetables(name: "Hot pepper", type: .vegetables),
                  Vegetables(name: "Indian bitter gourd", type: .vegetables),
                  Vegetables(name: "Jalapeño pepper", type: .vegetables),
                  Vegetables(name: "Jerusalem artichoke", type: .vegetables),
                  Vegetables(name: "Jicama", type: .vegetables),
                  Vegetables(name: "Kale", type: .vegetables),
                  Vegetables(name: "Kidney bean", type: .vegetables),
                  Vegetables(name: "Kidney beans", type: .vegetables),
                  Vegetables(name: "Kohlrabi", type: .vegetables),
                  Vegetables(name: "Korean-style beets", type: .vegetables),
                  Vegetables(name: "Korean-style carrots", type: .vegetables),
                  Vegetables(name: "Lentils", type: .vegetables),
                  Vegetables(name: "Lightly salted cucumbers", type: .vegetables),
                  Vegetables(name: "Lima beans", type: .vegetables),
                  Vegetables(name: "Loofah", type: .vegetables),
                  Vegetables(name: "Mexican cucumber", type: .vegetables),
                  Vegetables(name: "Mexican gherkin", type: .vegetables),
                  Vegetables(name: "Mexican vegetable mix", type: .vegetables),
                  Vegetables(name: "Mini pepper", type: .vegetables),
                  Vegetables(name: "Mirepoix", type: .vegetables),
                  Vegetables(name: "Mooli", type: .vegetables),
                  Vegetables(name: "Mung bean sprouts", type: .vegetables),
                  Vegetables(name: "Muscat pumpkin", type: .vegetables),
                  Vegetables(name: "Okra", type: .vegetables),
                  Vegetables(name: "Olives", type: .vegetables),
                  Vegetables(name: "Onion", type: .vegetables),
                  Vegetables(name: "Parsley root", type: .vegetables),
                  Vegetables(name: "Parsnip", type: .vegetables),
                  Vegetables(name: "Patty pan", type: .vegetables),
                  Vegetables(name: "Peas", type: .vegetables),
                  Vegetables(name: "Pepperoni", type: .vegetables),
                  Vegetables(name: "Pickled artichokes", type: .vegetables),
                  Vegetables(name: "Pickled asparagus", type: .vegetables),
                  Vegetables(name: "Pickled beans", type: .vegetables),
                  Vegetables(name: "Pickled broccoli", type: .vegetables),
                  Vegetables(name: "Pickled cabbage", type: .vegetables),
                  Vegetables(name: "Pickled carrots", type: .vegetables),
                  Vegetables(name: "Pickled cherry tomatoes", type: .vegetables),
                  Vegetables(name: "Pickled chili pepper", type: .vegetables),
                  Vegetables(name: "Pickled chinese cabbage", type: .vegetables),
                  Vegetables(name: "Pickled colorful cabbage", type: .vegetables),
                  Vegetables(name: "Pickled cucumbers", type: .vegetables),
                  Vegetables(name: "Pickled daikon", type: .vegetables),
                  Vegetables(name: "Pickled eggplants", type: .vegetables),
                  Vegetables(name: "Pickled garlic scapes", type: .vegetables),
                  Vegetables(name: "Pickled garlic", type: .vegetables),
                  Vegetables(name: "Pickled gherkins", type: .vegetables),
                  Vegetables(name: "Pickled green beans", type: .vegetables),
                  Vegetables(name: "Pickled green garlic", type: .vegetables),
                  Vegetables(name: "Pickled habanero pepper", type: .vegetables),
                  Vegetables(name: "Pickled hot pepper", type: .vegetables),
                  Vegetables(name: "Pickled onions", type: .vegetables),
                  Vegetables(name: "Pickled patty pan", type: .vegetables),
                  Vegetables(name: "Pickled potatoes", type: .vegetables),
                  Vegetables(name: "Pickled pumpkin", type: .vegetables),
                  Vegetables(name: "Pickled radish", type: .vegetables),
                  Vegetables(name: "Pickled red onion", type: .vegetables),
                  Vegetables(name: "Pickled sweet pepper", type: .vegetables),
                  Vegetables(name: "Pickled tomatoes", type: .vegetables),
                  Vegetables(name: "Pickled wild garlic", type: .vegetables),
                  Vegetables(name: "Pickled zucchini", type: .vegetables),
                  Vegetables(name: "Potato", type: .vegetables),
                  Vegetables(name: "Pumpkin", type: .vegetables),
                  Vegetables(name: "Purple carrot", type: .vegetables),
                  Vegetables(name: "Purple potato", type: .vegetables),
                  Vegetables(name: "Radish", type: .vegetables),
                  Vegetables(name: "Red cabbage", type: .vegetables),
                  Vegetables(name: "Red lentils", type: .vegetables),
                  Vegetables(name: "Red onion", type: .vegetables),
                  Vegetables(name: "Red radish", type: .vegetables),
                  Vegetables(name: "Rhubarb", type: .vegetables),
                  Vegetables(name: "Romanesco", type: .vegetables),
                  Vegetables(name: "Root vegetables", type: .vegetables),
                  Vegetables(name: "Rutabaga", type: .vegetables),
                  Vegetables(name: "Salted cucumbers", type: .vegetables),
                  Vegetables(name: "Salted tomatoes", type: .vegetables),
                  Vegetables(name: "Sauerkraut", type: .vegetables),
                  Vegetables(name: "Savoy cabbage", type: .vegetables),
                  Vegetables(name: "Serrano pepper", type: .vegetables),
                  Vegetables(name: "Shallot", type: .vegetables),
                  Vegetables(name: "Shelled peas", type: .vegetables),
                  Vegetables(name: "Snake gourd", type: .vegetables),
                  Vegetables(name: "Soybean sprouts", type: .vegetables),
                  Vegetables(name: "Soybeans", type: .vegetables),
                  Vegetables(name: "Spring vegetable mix", type: .vegetables),
                  Vegetables(name: "Sugar beet", type: .vegetables),
                  Vegetables(name: "Sun-dried tomatoes", type: .vegetables),
                  Vegetables(name: "Sweet potato", type: .vegetables),
                  Vegetables(name: "Taro", type: .vegetables),
                  Vegetables(name: "Tomato", type: .vegetables),
                  Vegetables(name: "Turnip", type: .vegetables),
                  Vegetables(name: "White beans", type: .vegetables),
                  Vegetables(name: "White cabbage", type: .vegetables),
                  Vegetables(name: "White carrot", type: .vegetables),
                  Vegetables(name: "White onion", type: .vegetables),
                  Vegetables(name: "White radish", type: .vegetables),
                  Vegetables(name: "Winter squash", type: .vegetables),
                  Vegetables(name: "Yacon", type: .vegetables),
                  Vegetables(name: "Yam", type: .vegetables),
                  Vegetables(name: "Yellow beetroot", type: .vegetables),
                  Vegetables(name: "Yellow carrot", type: .vegetables),
                  Vegetables(name: "Young potatoes", type: .vegetables),
                  Vegetables(name: "Zucchini", type: .vegetables)
]

let fruitsAndBerries = [FruitsAndBerries(name: "Абрикос", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Авара", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Авокадо", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Адамово яблоко (Маклюра)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Азимина", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Айва", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Аки", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Актинидия", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Алыча", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ананас", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Апельсин бергамот", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Апельсин", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Араза", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Арбуз", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Арбузы консервированные", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Бабако", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Баиль", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Банан", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Бананы мини", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Барбадосская вишня ацерола", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Барбарис", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Билимби (Огуречное дерево)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Боярышник", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Брусника", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Бузина", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Вампи", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Виноград Изабелла", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Виноград Каберне Совиньон (Cabernet Sauvignon)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Виноград кишмиш", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Виноград Мерло (Merlot)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Виноград Мускат", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Виноград Ркацители", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Виноград Шардоне (Chardonnay)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Виноград", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Вишня", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Водяника (шикша)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Войлочная вишня", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Голубика", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Гранадилла", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Гранат", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Грейпфрут", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Груша", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Гуава земляничная", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Гуава", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Гуанабана (Сметанное яблоко)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Гуарана", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Дерево сикомор", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Джаботикаба", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Джекфрут", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Дуриан", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Дыня", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ежевика", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Желтый арбуз", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Жердела", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Жимолость", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Замороженная вишня", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Замороженные фрукты", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Замороженные ягоды", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Звездное яблоко", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Земклуника", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Земляника", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Земляничное дерево", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Зизифус (Унаби)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Икако (Золотая слива)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Илама", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Инжир", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Инжирный персик", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ирга", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Йошта", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Каламондин (Цитрофортунелла)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Калина", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Каму-каму", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Канталупа", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Капулин", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Карамбола", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Каранда", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Кассаба", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Кафир-лайм", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Кепел", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Кивано", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Киви", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Кизил", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Китайская груша (Нэши)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Китайская клубника (восковница красная)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Клементин", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Клубника маринованная", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Клубника", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Клюква", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Княженика", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Консервированная дыня", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Консервированная черешня", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Консервированные бананы", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Консервированные мандарины", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Консервированные сливы", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Консервированные ягоды", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Консервированный виноград", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Корлан", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Костяника", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Красника", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Красный виноград", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Крыжовник зеленый", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Крыжовник", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Кудрания (Клубничное дерево)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Кумкват", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Купуасу", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Лайм", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Лангсат", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Лимон", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Лимонник", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Личи", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Логанова ягода", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Лонган", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Лукума", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маболо", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Магический фрукт", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Малина", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маммея", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Манго консервированное", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Манго", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Мангостин", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Мандарины", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маракуйя", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маранг", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованная вишня", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованная красная смородина", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованные апельсины", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованные груши", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованные лимоны", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованные сливы", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованные яблоки", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованный ананас", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованный арбуз", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованный крыжовник", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованный чернослив", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Марула", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Медовая дыня", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Можжевельник", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Мора", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Морошка", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Морской виноград (Кокколоба ягодоносная)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Мускатная дыня", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Мушмула германская", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Мушмула японская", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Мушмула", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Нансе", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Наранхилла", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Нектарин", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Нойна", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Нони", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Облепиха", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Панданус (кьюра)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Папайя", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Пассифлора голубая (кавалерская звезда)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Пепино", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Персик", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Персики маринованные", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Питахайя", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Платония", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Плоды померанца (чинотто)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Плуот", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Помело", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Рамбутан", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Рука Будды", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Рябина красная", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Салак", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Саподилла", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Сапота (чёрное яблоко)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Сатсума", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Свежемороженая клубника", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Свежемороженая малина", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Свити", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Сереноа", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Сизигиум", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Слива", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Смородина белая", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Смородина красная", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Смородина черная", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Суринамская вишня питанга", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Сушеная малина", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Тамарилло", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Тамаринд", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Танжело", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Танжерин", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Терн", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Толокнянка обыкновенная (медвежье ушко)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Угни (Уньи)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Фалса", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Фейхоа", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ферония (Деревянное яблоко)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Фрукты", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Хурма виргинская", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Хурма", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Цабр", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Цитрон", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Чемпедак", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Черёмуха виргинская", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Черешня", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Черимойя", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Черника сушеная", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Черника", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Черноплодная рябина", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Черный виноград", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Чилибуха (Рвотный орех)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Чупа-чупа", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Шелковица", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Шефердия серебристая", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Шиповник", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Эмблика лекарственная", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Юдзу", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Айдаред", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Анис", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки антоновка", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки белый налив", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Богатырь", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Гала", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Глостер", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки голден", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Гренни Смит", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Грушовка", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Джонаголд", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Джонатан", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Китайка", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Макинтош", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Мантет", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Медуница", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Мельба", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки моченые", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Пепин", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки ранетки", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Слава победителям", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Спартан", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Флорина", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Фуджи", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоко Лобо", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоко", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ягода дереза китайская", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ягода лох", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ягода магония падуболистная", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ягоды асаи", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ягоды годжи", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ягоды", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Японский лимон (Юзу)", type: .fruitsAndBerries)
]

let mushrooms = [Mushrooms(name: "Белые грибы маринованные", type: .mushrooms),
                 Mushrooms(name: "Белый гриб сушеный", type: .mushrooms),
                 Mushrooms(name: "Белый гриб", type: .mushrooms),
                 Mushrooms(name: "Белый степной гриб (Еринги)", type: .mushrooms),
                 Mushrooms(name: "Белый трюфель", type: .mushrooms),
                 Mushrooms(name: "Березовый гриб чага", type: .mushrooms),
                 Mushrooms(name: "Вешенки", type: .mushrooms),
                 Mushrooms(name: "Гигрофор", type: .mushrooms),
                 Mushrooms(name: "Гриб говорушка", type: .mushrooms),
                 Mushrooms(name: "Гриб дождевик", type: .mushrooms),
                 Mushrooms(name: "Гриб ежовик", type: .mushrooms),
                 Mushrooms(name: "Гриб майтаке", type: .mushrooms),
                 Mushrooms(name: "Гриб мацутакэ", type: .mushrooms),
                 Mushrooms(name: "Гриб моховик", type: .mushrooms),
                 Mushrooms(name: "Гриб порховка", type: .mushrooms),
                 Mushrooms(name: "Гриб серушка", type: .mushrooms),
                 Mushrooms(name: "Гриб-баран", type: .mushrooms),
                 Mushrooms(name: "Грибная икра", type: .mushrooms),
                 Mushrooms(name: "Грибная капуста (Спарассис курчавый)", type: .mushrooms),
                 Mushrooms(name: "Грибы волнушки", type: .mushrooms),
                 Mushrooms(name: "Грибы мун", type: .mushrooms),
                 Mushrooms(name: "Грибы намеко", type: .mushrooms),
                 Mushrooms(name: "Грибы портобелло", type: .mushrooms),
                 Mushrooms(name: "Грибы рядовки", type: .mushrooms),
                 Mushrooms(name: "Грибы сушеные", type: .mushrooms),
                 Mushrooms(name: "Грибы эноки", type: .mushrooms),
                 Mushrooms(name: "Груздь", type: .mushrooms),
                 Mushrooms(name: "Древесный гриб муэр", type: .mushrooms),
                 Mushrooms(name: "Дубовик обыкновенный", type: .mushrooms),
                 Mushrooms(name: "Ежовик желтый", type: .mushrooms),
                 Mushrooms(name: "Замороженные грибы", type: .mushrooms),
                 Mushrooms(name: "Ивишень (Подвишенник)", type: .mushrooms),
                 Mushrooms(name: "Консервированные белые грибы", type: .mushrooms),
                 Mushrooms(name: "Консервированные грибы", type: .mushrooms),
                 Mushrooms(name: "Королевские опята (Чешуйчатка золотистая)", type: .mushrooms),
                 Mushrooms(name: "Королевский устричный гриб", type: .mushrooms),
                 Mushrooms(name: "Лисички", type: .mushrooms),
                 Mushrooms(name: "Майский гриб", type: .mushrooms),
                 Mushrooms(name: "Маринованное грибное ассорти", type: .mushrooms),
                 Mushrooms(name: "Маринованные вешенки", type: .mushrooms),
                 Mushrooms(name: "Маринованные грибы", type: .mushrooms),
                 Mushrooms(name: "Маринованные грузди", type: .mushrooms),
                 Mushrooms(name: "Маринованные лисички", type: .mushrooms),
                 Mushrooms(name: "Маринованные маслята", type: .mushrooms),
                 Mushrooms(name: "Маринованные рыжики", type: .mushrooms),
                 Mushrooms(name: "Маринованные шампиньоны", type: .mushrooms),
                 Mushrooms(name: "Маслята", type: .mushrooms),
                 Mushrooms(name: "Мокруха пурпуровая", type: .mushrooms),
                 Mushrooms(name: "Опенок зимний", type: .mushrooms),
                 Mushrooms(name: "Опята маринованные", type: .mushrooms),
                 Mushrooms(name: "Опята", type: .mushrooms),
                 Mushrooms(name: "Пецица", type: .mushrooms),
                 Mushrooms(name: "Плютей олений", type: .mushrooms),
                 Mushrooms(name: "Подберёзовик сушеный", type: .mushrooms),
                 Mushrooms(name: "Подберёзовик", type: .mushrooms),
                 Mushrooms(name: "Подосиновик сушеный", type: .mushrooms),
                 Mushrooms(name: "Подосиновик", type: .mushrooms),
                 Mushrooms(name: "Полубелый гриб", type: .mushrooms),
                 Mushrooms(name: "Польский гриб", type: .mushrooms),
                 Mushrooms(name: "Рыжик", type: .mushrooms),
                 Mushrooms(name: "Сморчок", type: .mushrooms),
                 Mushrooms(name: "Соленые рыжики", type: .mushrooms),
                 Mushrooms(name: "Сушеные лисички", type: .mushrooms),
                 Mushrooms(name: "Сушеные шампиньоны", type: .mushrooms),
                 Mushrooms(name: "Сыроежка", type: .mushrooms),
                 Mushrooms(name: "Трюфель", type: .mushrooms),
                 Mushrooms(name: "Цезарский гриб", type: .mushrooms),
                 Mushrooms(name: "Чернушка", type: .mushrooms),
                 Mushrooms(name: "Шампиньоны консервированные", type: .mushrooms),
                 Mushrooms(name: "Шампиньоны", type: .mushrooms),
                 Mushrooms(name: "Шиитаке сушеные", type: .mushrooms),
                 Mushrooms(name: "Шиитаке", type: .mushrooms),
                 Mushrooms(name: "Шимеджи", type: .mushrooms)
]

var allFood = vegitables + fruitsAndBerries + mushrooms




























