//
//  FruitsAndBerriesData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 10.10.2023.
//

import Foundation

let fruitsAndBerries = [
    FoodRealm(name: "Acai Berries", type: .fruitsAndBerries, calories: "70"),
    FoodRealm(name: "Acerola Cherry", type: .fruitsAndBerries, calories: "32"),
    FoodRealm(name: "Actinidia", type: .fruitsAndBerries, calories: "61"),
    FoodRealm(name: "Adam's Apple (Osage Orange)", type: .fruitsAndBerries, calories: "129"),
    FoodRealm(name: "Akee", type: .fruitsAndBerries, calories: "151"),
    FoodRealm(name: "Alpine Strawberry", type: .fruitsAndBerries, calories: "32"),
    FoodRealm(name: "American Persimmon", type: .fruitsAndBerries, calories: "81"),
    FoodRealm(name: "Apple", type: .fruitsAndBerries, calories: "52"),
    FoodRealm(name: "Apple (Lobo)", type: .fruitsAndBerries, calories: "57"),
    FoodRealm(name: "Apples (Anise)", type: .fruitsAndBerries, calories: "47"),
    FoodRealm(name: "Apples (Antonovka)", type: .fruitsAndBerries, calories: "47"),
    FoodRealm(name: "Apples (Aydared)", type: .fruitsAndBerries, calories: "52"),
    FoodRealm(name: "Apples (Bogatyr)", type: .fruitsAndBerries, calories: "52"),
    FoodRealm(name: "Apples (Florina)", type: .fruitsAndBerries, calories: "59"),
    FoodRealm(name: "Apples (Fuji)", type: .fruitsAndBerries, calories: "52"),
    FoodRealm(name: "Apples (Gala)", type: .fruitsAndBerries, calories: "57"),
    FoodRealm(name: "Apples (Glory to the Winners)", type: .fruitsAndBerries, calories: "57"),
    FoodRealm(name: "Apples (Gloucester)", type: .fruitsAndBerries, calories: "52"),
    FoodRealm(name: "Apples (Golden)", type: .fruitsAndBerries, calories: "52"),
    FoodRealm(name: "Apples (Granny Smith)", type: .fruitsAndBerries, calories: "57"),
    FoodRealm(name: "Apples (Grushovka)", type: .fruitsAndBerries, calories: "52"),
    FoodRealm(name: "Apples (Jonagold)", type: .fruitsAndBerries, calories: "57"),
    FoodRealm(name: "Apples (Jonathan)", type: .fruitsAndBerries, calories: "52"),
    FoodRealm(name: "Apples (Kitayka)", type: .fruitsAndBerries, calories: "47"),
    FoodRealm(name: "Apples (Macintosh)", type: .fruitsAndBerries, calories: "52"),
    FoodRealm(name: "Apples (Mantet)", type: .fruitsAndBerries, calories: "52"),
    FoodRealm(name: "Apples (Medunica)", type: .fruitsAndBerries, calories: "52"),
    FoodRealm(name: "Apples (Melba)", type: .fruitsAndBerries, calories: "52"),
    FoodRealm(name: "Apples (Pepin)", type: .fruitsAndBerries, calories: "52"),
    FoodRealm(name: "Apples (Ranetki)", type: .fruitsAndBerries, calories: "57"),
    FoodRealm(name: "Apples (Soaked)", type: .fruitsAndBerries, calories: "57"),
    FoodRealm(name: "Apples (Spartan)", type: .fruitsAndBerries, calories: "52"),
    FoodRealm(name: "Apples (White Filling)", type: .fruitsAndBerries, calories: "57"),
    FoodRealm(name: "Apricot", type: .fruitsAndBerries, calories: "48"),
    FoodRealm(name: "Araz", type: .fruitsAndBerries, calories: "42"),
    FoodRealm(name: "Avara", type: .fruitsAndBerries, calories: "70"),
    FoodRealm(name: "Avocado", type: .fruitsAndBerries, calories: "160"),
    FoodRealm(name: "Azimina", type: .fruitsAndBerries, calories: "29"),
    FoodRealm(name: "Babaco", type: .fruitsAndBerries, calories: "31"),
    FoodRealm(name: "Bael", type: .fruitsAndBerries, calories: "31"),
    FoodRealm(name: "Banana", type: .fruitsAndBerries, calories: "89"),
    FoodRealm(name: "Barberry", type: .fruitsAndBerries, calories: "88"),
    FoodRealm(name: "Bergamot Orange", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Berries", type: .fruitsAndBerries, calories: "33"),
    FoodRealm(name: "Bilimbi", type: .fruitsAndBerries, calories: "35"),
    FoodRealm(name: "Black Chokeberry", type: .fruitsAndBerries, calories: "47"),
    FoodRealm(name: "Black Currant", type: .fruitsAndBerries, calories: "63"),
    FoodRealm(name: "Black Grape", type: .fruitsAndBerries, calories: "69"),
    FoodRealm(name: "Black Sapote", type: .fruitsAndBerries, calories: "131"),
    FoodRealm(name: "Blackberry", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Blue Passion Flower", type: .fruitsAndBerries, calories: "98"),
    FoodRealm(name: "Blueberry", type: .fruitsAndBerries, calories: "57"),
    FoodRealm(name: "Bog whortleberry", type: .fruitsAndBerries, calories: "32"),
    FoodRealm(name: "Buddha's Hand", type: .fruitsAndBerries, calories: "160"),
    FoodRealm(name: "Cabernet Sauvignon Grape", type: .fruitsAndBerries, calories: "80"),
    FoodRealm(name: "Calamondin", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Camu Camu", type: .fruitsAndBerries, calories: "20"),
    FoodRealm(name: "Canned Berries", type: .fruitsAndBerries, calories: "50"),
    FoodRealm(name: "Canned Cantaloupe", type: .fruitsAndBerries, calories: "30"),
    FoodRealm(name: "Canned Cherries", type: .fruitsAndBerries, calories: "60"),
    FoodRealm(name: "Canned Grapes", type: .fruitsAndBerries, calories: "70"),
    FoodRealm(name: "Canned Mandarin Oranges", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Canned Mango", type: .fruitsAndBerries, calories: "60"),
    FoodRealm(name: "Canned Plums", type: .fruitsAndBerries, calories: "80"),
    FoodRealm(name: "Canned Watermelon", type: .fruitsAndBerries, calories: "30"),
    FoodRealm(name: "Cantaloupe", type: .fruitsAndBerries, calories: "34"),
    FoodRealm(name: "Capulin", type: .fruitsAndBerries, calories: "50"),
    FoodRealm(name: "Carambola", type: .fruitsAndBerries, calories: "30"),
    FoodRealm(name: "Cassava", type: .fruitsAndBerries, calories: "160"),
    FoodRealm(name: "Chardonnay Grape", type: .fruitsAndBerries, calories: "83"),
    FoodRealm(name: "Chempedak", type: .fruitsAndBerries, calories: "95"),
    FoodRealm(name: "Cherimoya", type: .fruitsAndBerries, calories: "75"),
    FoodRealm(name: "Cherries", type: .fruitsAndBerries, calories: "50"),
    FoodRealm(name: "Cherry", type: .fruitsAndBerries, calories: "50"),
    FoodRealm(name: "Cherry Plum", type: .fruitsAndBerries, calories: "46"),
    FoodRealm(name: "Chilibuha (Vomiting Nut)", type: .fruitsAndBerries, calories: ""),
    FoodRealm(name: "Chinese Date (Jujube)", type: .fruitsAndBerries, calories: "79"),
    FoodRealm(name: "Chinese Magnolia Vine (Magonia oblonga)", type: .fruitsAndBerries, calories: "-"),
    FoodRealm(name: "Chinese Pear (Nashi)", type: .fruitsAndBerries, calories: "42"),
    FoodRealm(name: "Chinese Strawberry (Red Waxberry)", type: .fruitsAndBerries, calories: "37"),
    FoodRealm(name: "Chupa-Chupa", type: .fruitsAndBerries, calories: "143"),
    FoodRealm(name: "Citron", type: .fruitsAndBerries, calories: "200"),
    FoodRealm(name: "Clementine", type: .fruitsAndBerries, calories: "47"),
    FoodRealm(name: "Cloudberry", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Corlan", type: .fruitsAndBerries, calories: "-"),
    FoodRealm(name: "Cornel", type: .fruitsAndBerries, calories: "63"),
    FoodRealm(name: "Cornelian Cherry", type: .fruitsAndBerries, calories: "60"),
    FoodRealm(name: "Cowberry", type: .fruitsAndBerries, calories: "35"),
    FoodRealm(name: "Cranberry", type: .fruitsAndBerries, calories: "46"),
    FoodRealm(name: "Cupuassu", type: .fruitsAndBerries, calories: "70"),
    FoodRealm(name: "Currant", type: .fruitsAndBerries, calories: "56"),
    FoodRealm(name: "Currants", type: .fruitsAndBerries, calories: "63"),
    FoodRealm(name: "Dried Blueberries", type: .fruitsAndBerries, calories: "325"),
    FoodRealm(name: "Dried Raspberry", type: .fruitsAndBerries, calories: "337"),
    FoodRealm(name: "Durian", type: .fruitsAndBerries, calories: "147"),
    FoodRealm(name: "Elderberry", type: .fruitsAndBerries, calories: "73"),
    FoodRealm(name: "European Medlar", type: .fruitsAndBerries, calories: "54"),
    FoodRealm(name: "Feijoa", type: .fruitsAndBerries, calories: "55"),
    FoodRealm(name: "Fig", type: .fruitsAndBerries, calories: "74"),
    FoodRealm(name: "Frozen Berries", type: .fruitsAndBerries, calories: "36"),
    FoodRealm(name: "Frozen Cherry", type: .fruitsAndBerries, calories: "52"),
    FoodRealm(name: "Frozen Fruits", type: .fruitsAndBerries, calories: "79"),
    FoodRealm(name: "Frozen Raspberries", type: .fruitsAndBerries, calories: "37"),
    FoodRealm(name: "Frozen Strawberries", type: .fruitsAndBerries, calories: "32"),
    FoodRealm(name: "Fruits", type: .fruitsAndBerries, calories: "-"),
    FoodRealm(name: "Goji Berries", type: .fruitsAndBerries, calories: "349"),
    FoodRealm(name: "Granadilla", type: .fruitsAndBerries, calories: "55"),
    FoodRealm(name: "Grape", type: .fruitsAndBerries, calories: "69"),
    FoodRealm(name: "Grapefruit", type: .fruitsAndBerries, calories: "42"),
    FoodRealm(name: "Green Currant", type: .fruitsAndBerries, calories: "63"),
    FoodRealm(name: "Guarana", type: .fruitsAndBerries, calories: "37"),
    FoodRealm(name: "Guava", type: .fruitsAndBerries, calories: "68"),
    FoodRealm(name: "Hawthorn", type: .fruitsAndBerries, calories: "52"),
    FoodRealm(name: "Honeydew Melon", type: .fruitsAndBerries, calories: "36"),
    FoodRealm(name: "Honeysuckle", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Ilama", type: .fruitsAndBerries, calories: "81"),
    FoodRealm(name: "Indian Gooseberry (Amla)", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Indian Plum (American Plum)", type: .fruitsAndBerries, calories: "46"),
    FoodRealm(name: "Irga", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Isabella Grape", type: .fruitsAndBerries, calories: "70"),
    FoodRealm(name: "Jaboticaba", type: .fruitsAndBerries, calories: "49"),
    FoodRealm(name: "Jackfruit", type: .fruitsAndBerries, calories: "95"),
    FoodRealm(name: "Japanese Citron (Yuzu)", type: .fruitsAndBerries, calories: "61"),
    FoodRealm(name: "Japanese Loquat", type: .fruitsAndBerries, calories: "47"),
    FoodRealm(name: "Japanese Medlar", type: .fruitsAndBerries, calories: "51"),
    FoodRealm(name: "Jujube", type: .fruitsAndBerries, calories: "79"),
    FoodRealm(name: "Juneberry", type: .fruitsAndBerries, calories: "41"),
    FoodRealm(name: "Juniper", type: .fruitsAndBerries, calories: "571"),
    FoodRealm(name: "Kaffir Lime", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Kamchatka Bilberry", type: .fruitsAndBerries, calories: "38"),
    FoodRealm(name: "Karanda", type: .fruitsAndBerries, calories: "41"),
    FoodRealm(name: "Kepel", type: .fruitsAndBerries, calories: "94"),
    FoodRealm(name: "Kiwano", type: .fruitsAndBerries, calories: "102"),
    FoodRealm(name: "Kiwi", type: .fruitsAndBerries, calories: "61"),
    FoodRealm(name: "Kudrania (Strawberry Tree)", type: .fruitsAndBerries, calories: "88"),
    FoodRealm(name: "Kumquat", type: .fruitsAndBerries, calories: "71"),
    FoodRealm(name: "Langsat", type: .fruitsAndBerries, calories: "60"),
    FoodRealm(name: "Lemon", type: .fruitsAndBerries, calories: "29"),
    FoodRealm(name: "Lemon Tree", type: .fruitsAndBerries, calories: "29"),
    FoodRealm(name: "Lime", type: .fruitsAndBerries, calories: "30"),
    FoodRealm(name: "Lingonberry", type: .fruitsAndBerries, calories: "58"),
    FoodRealm(name: "Litchi (Lychee)", type: .fruitsAndBerries, calories: "66"),
    FoodRealm(name: "Loganberry", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Longan", type: .fruitsAndBerries, calories: "60"),
    FoodRealm(name: "Loquat", type: .fruitsAndBerries, calories: "47"),
    FoodRealm(name: "Lucuma", type: .fruitsAndBerries, calories: "94"),
    FoodRealm(name: "Mabolo", type: .fruitsAndBerries, calories: "82"),
    FoodRealm(name: "Mamey Sapote", type: .fruitsAndBerries, calories: "89"),
    FoodRealm(name: "Mandarins", type: .fruitsAndBerries, calories: "53"),
    FoodRealm(name: "Mango", type: .fruitsAndBerries, calories: "60"),
    FoodRealm(name: "Mangosteen", type: .fruitsAndBerries, calories: "73"),
    FoodRealm(name: "Marang", type: .fruitsAndBerries, calories: "97"),
    FoodRealm(name: "Marula", type: .fruitsAndBerries, calories: "54"),
    FoodRealm(name: "Medlar", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Melon", type: .fruitsAndBerries, calories: "36"),
    FoodRealm(name: "Merlot Grape", type: .fruitsAndBerries, calories: "83"),
    FoodRealm(name: "Mini Bananas", type: .fruitsAndBerries, calories: "89"),
    FoodRealm(name: "Miracle Fruit", type: .fruitsAndBerries, calories: "30"),
    FoodRealm(name: "Mopa", type: .fruitsAndBerries, calories: "95"),
    FoodRealm(name: "Mulberry", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Muscat Grape", type: .fruitsAndBerries, calories: "288"),
    FoodRealm(name: "Muskmelon", type: .fruitsAndBerries, calories: "34"),
    FoodRealm(name: "Naranjilla", type: .fruitsAndBerries, calories: "40"),
    FoodRealm(name: "Nectarine", type: .fruitsAndBerries, calories: "44"),
    FoodRealm(name: "Noina", type: .fruitsAndBerries, calories: "38"),
    FoodRealm(name: "Noni", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Orange", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Orange fruit (chinotto)", type: .fruitsAndBerries, calories: "49"),
    FoodRealm(name: "Pandanus (Kewra)", type: .fruitsAndBerries, calories: "19"),
    FoodRealm(name: "Papaya", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Passion Fruit", type: .fruitsAndBerries, calories: "97"),
    FoodRealm(name: "Peach", type: .fruitsAndBerries, calories: "39"),
    FoodRealm(name: "Pear", type: .fruitsAndBerries, calories: "57"),
    FoodRealm(name: "Pepino", type: .fruitsAndBerries, calories: "19"),
    FoodRealm(name: "Persimmon", type: .fruitsAndBerries, calories: "81"),
    FoodRealm(name: "Phalsa", type: .fruitsAndBerries, calories: "60"),
    FoodRealm(name: "Pickled Apples", type: .fruitsAndBerries, calories: "50"),
    FoodRealm(name: "Pickled Cherries", type: .fruitsAndBerries, calories: "51"),
    FoodRealm(name: "Pickled Currants", type: .fruitsAndBerries, calories: "52"),
    FoodRealm(name: "Pickled Lemons", type: .fruitsAndBerries, calories: "29"),
    FoodRealm(name: "Pickled Oranges", type: .fruitsAndBerries, calories: "44"),
    FoodRealm(name: "Pickled Pears", type: .fruitsAndBerries, calories: "45"),
    FoodRealm(name: "Pickled Pineapple", type: .fruitsAndBerries, calories: "48"),
    FoodRealm(name: "Pickled Plums", type: .fruitsAndBerries, calories: "47"),
    FoodRealm(name: "Pickled Prunes", type: .fruitsAndBerries, calories: "55"),
    FoodRealm(name: "Pickled Red Currants", type: .fruitsAndBerries, calories: "53"),
    FoodRealm(name: "Pickled Strawberries", type: .fruitsAndBerries, calories: "50"),
    FoodRealm(name: "Pickled Watermelon", type: .fruitsAndBerries, calories: "29"),
    FoodRealm(name: "Pineapple", type: .fruitsAndBerries, calories: "50"),
    FoodRealm(name: "Pitahaya", type: .fruitsAndBerries, calories: "60"),
    FoodRealm(name: "Pitanga", type: .fruitsAndBerries, calories: "32"),
    FoodRealm(name: "Platonia", type: .fruitsAndBerries, calories: "84"),
    FoodRealm(name: "Plum", type: .fruitsAndBerries, calories: "46"),
    FoodRealm(name: "Pluot", type: .fruitsAndBerries, calories: "56"),
    FoodRealm(name: "Pomegranate", type: .fruitsAndBerries, calories: "83"),
    FoodRealm(name: "Pomelo", type: .fruitsAndBerries, calories: "38"),
    FoodRealm(name: "Quince", type: .fruitsAndBerries, calories: "57"),
    FoodRealm(name: "Rambutan", type: .fruitsAndBerries, calories: "68"),
    FoodRealm(name: "Raspberry", type: .fruitsAndBerries, calories: "52"),
    FoodRealm(name: "Red Currant", type: .fruitsAndBerries, calories: "56"),
    FoodRealm(name: "Red Grape", type: .fruitsAndBerries, calories: "69"),
    FoodRealm(name: "Rkatsiteli Grape", type: .fruitsAndBerries, calories: "72"),
    FoodRealm(name: "Rose Hip", type: .fruitsAndBerries, calories: "162"),
    FoodRealm(name: "Rowanberry", type: .fruitsAndBerries, calories: "52"),
    FoodRealm(name: "Salak", type: .fruitsAndBerries, calories: "82"),
    FoodRealm(name: "Sapodilla", type: .fruitsAndBerries, calories: "83"),
    FoodRealm(name: "Satsuma", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Saw Palmetto", type: .fruitsAndBerries, calories: "58"),
    FoodRealm(name: "Sea Buckthorn", type: .fruitsAndBerries, calories: "86"),
    FoodRealm(name: "Sea Grape (Coccoloba uvifera)", type: .fruitsAndBerries, calories: "54"),
    FoodRealm(name: "Silver Leaf", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Soursop", type: .fruitsAndBerries, calories: "66"),
    FoodRealm(name: "Star Apple", type: .fruitsAndBerries, calories: "67"),
    FoodRealm(name: "Stone berry", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Strawberry", type: .fruitsAndBerries, calories: "32"),
    FoodRealm(name: "Strawberry Guava", type: .fruitsAndBerries, calories: "32"),
    FoodRealm(name: "Strawberry Tree", type: .fruitsAndBerries, calories: "72"),
    FoodRealm(name: "Sweety", type: .fruitsAndBerries, calories: "80"),
    FoodRealm(name: "Sycamore Fig", type: .fruitsAndBerries, calories: "74"),
    FoodRealm(name: "Syzygium", type: .fruitsAndBerries, calories: "-"),
    FoodRealm(name: "Tamarillo", type: .fruitsAndBerries, calories: "38"),
    FoodRealm(name: "Tamarind", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Tangelo", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Tangerine", type: .fruitsAndBerries, calories: "43"),
    FoodRealm(name: "Tern", type: .fruitsAndBerries, calories: "62"),
    FoodRealm(name: "Tsaoko", type: .fruitsAndBerries, calories: "123"),
    FoodRealm(name: "Vampi", type: .fruitsAndBerries, calories: "74"),
    FoodRealm(name: "Velvet Cherry", type: .fruitsAndBerries, calories: "79"),
    FoodRealm(name: "Viburnum", type: .fruitsAndBerries, calories: "26"),
    FoodRealm(name: "Virginia Creeper", type: .fruitsAndBerries, calories: "83"),
    FoodRealm(name: "Water Apple (Syzygium aqueum)", type: .fruitsAndBerries, calories: "48"),
    FoodRealm(name: "Watermelon", type: .fruitsAndBerries, calories: "30"),
    FoodRealm(name: "White Currant", type: .fruitsAndBerries, calories: "56"),
    FoodRealm(name: "Wild Strawberry", type: .fruitsAndBerries, calories: "32"),
    FoodRealm(name: "Wood Apple (Feronia)", type: .fruitsAndBerries, calories: "66"),
    FoodRealm(name: "Yellow Watermelon", type: .fruitsAndBerries, calories: "30"),
    FoodRealm(name: "Yoshta", type: .fruitsAndBerries, calories: "55"),
    FoodRealm(name: "Yuzu", type: .fruitsAndBerries, calories: "56"),
    FoodRealm(name: "Zizyphus", type: .fruitsAndBerries, calories: "79")
]

