//
//  FruitsAndBerriesData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 10.10.2023.
//

import Foundation

let fruitsAndBerries = [FruitsAndBerries(name: "Acai Berries", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Acerola Cherry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Actinidia", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Adam's Apple (Osage Orange)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Akee", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Alpine Strawberry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "American Persimmon", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apple", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apple (Lobo)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Anise)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Antonovka)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Aydared)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Bogatyr)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Florina)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Fuji)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Gala)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Glory to the Winners)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Gloucester)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Golden)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Granny Smith)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Grushovka)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Jonagold)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Jonathan)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Kitayka)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Macintosh)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Mantet)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Medunica)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Melba)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Pepin)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Ranetki)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Soaked)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (Spartan)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apples (White Filling)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Apricot", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Araz", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Avara", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Avocado", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Azimina", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Babaco", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Bael", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Banana", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Barberry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Bergamot Orange", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Berries", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Bilimbi", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Black Chokeberry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Black Currant", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Black Grape", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Black Sapote", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Blackberry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Blue Passion Flower", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Blueberry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Bog whortleberry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Buddha's Hand", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Cabernet Sauvignon Grape", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Calamondin", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Camu Camu", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Canned Berries", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Canned Cantaloupe", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Canned Cherries", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Canned Grapes", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Canned Mandarin Oranges", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Canned Mango", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Canned Plums", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Canned Watermelon", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Cantaloupe", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Capulin", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Carambola", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Cassava", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Chardonnay Grape", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Chempedak", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Cherimoya", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Cherries", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Cherry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Cherry Plum", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Chilibuha (Vomiting Nut)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Chinese Date (Jujube)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Chinese Magnolia Vine (Magonia oblonga)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Chinese Pear (Nashi)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Chinese Strawberry (Red Waxberry)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Chupa-Chupa", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Citron", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Clementine", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Cloudberry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Corlan", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Cornel", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Cornelian Cherry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Cowberry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Cranberry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Cupuassu", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Currant", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Currants", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Dried Blueberries", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Dried Raspberry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Durian", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Elderberry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "European Medlar", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Feijoa", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Fig", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Frozen Berries", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Frozen Cherry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Frozen Fruits", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Frozen Raspberries", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Frozen Strawberries", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Fruits", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Goji Berries", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Granadilla", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Grape", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Grapefruit", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Green Currant", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Guarana", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Guava", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Hawthorn", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Honeydew Melon", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Honeysuckle", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ilama", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Indian Gooseberry (Amla)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Indian Plum (American Plum)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Irga", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Isabella Grape", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Jaboticaba", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Jackfruit", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Japanese Citron (Yuzu)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Japanese Loquat", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Japanese Medlar", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Jujube", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Juneberry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Juniper", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Kaffir Lime", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Kamchatka Bilberry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Karanda", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Kepel", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Kiwano", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Kiwi", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Kudrania (Strawberry Tree)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Kumquat", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Langsat", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Lemon", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Lemon Tree", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Lime", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Lingonberry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Litchi (Lychee)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Loganberry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Longan", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Loquat", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Lucuma", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Mabolo", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Mamey Sapote", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Mandarins", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Mango", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Mangosteen", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Marang", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Marula", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Medlar", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Melon", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Merlot Grape", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Mini Bananas", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Miracle Fruit", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Mopa", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Mulberry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Muscat Grape", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Muskmelon", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Naranjilla", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Nectarine", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Noina", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Noni", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Orange", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Orange fruit (chinotto)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pandanus (Kewra)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Papaya", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Passion Fruit", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Peach", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pear", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pepino", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Persimmon", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Phalsa", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pickled Apples", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pickled Cherries", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pickled Currants", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pickled Lemons", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pickled Oranges", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pickled Pears", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pickled Pineapple", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pickled Plums", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pickled Prunes", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pickled Red Currants", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pickled Strawberries", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pickled Watermelon", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pineapple", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pitahaya", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pitanga", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Platonia", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Plum", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pluot", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pomegranate", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Pomelo", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Quince", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Rambutan", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Raspberry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Red Currant", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Red Grape", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Rkatsiteli Grape", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Rose Hip", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Rowanberry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Salak", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Sapodilla", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Satsuma", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Saw Palmetto", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Sea Buckthorn", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Sea Grape (Coccoloba uvifera)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Silver Leaf", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Soursop", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Star Apple", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Stone berry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Strawberry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Strawberry Guava", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Strawberry Tree", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Sweety", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Sycamore Fig", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Syzygium", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Tamarillo", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Tamarind", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Tangelo", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Tangerine", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Tern", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Tsaoko", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Vampi", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Velvet Cherry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Viburnum", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Virginia Creeper", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Water Apple (Syzygium aqueum)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Watermelon", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "White Currant", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Wild Strawberry", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Wood Apple (Feronia)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Yellow Watermelon", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Yoshta", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Yuzu", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Zizyphus", type: .fruitsAndBerries),
]
