//
//  GrainsAndPorridgeData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 16.10.2023.
//

import Foundation

let grainsAndPorridge = [GrainsAndPorridge(name: "Almond flour", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Amaranth", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Arborio rice", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Barley flakes", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Barley grains", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Barley groats", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Basmati rice", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Black rice (Wild rice)", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Boiled buckwheat", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Boiled rice", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Bran", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Brown rice", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Buckwheat groats", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Buckwheat kernels", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Bulgur", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Canned chickpeas", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Canned corn", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Carnaroli rice", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Caro", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Cereals", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Chickpeas", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Corn flakes", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Corn porridge", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Cornmeal", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Couscous", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Delicate shirataki spaghetti", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Flaxseed porridge", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Fusigon rice", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Golden rice", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Jasmine rice", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Long-grain rice", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Millet", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Morap", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Nishiki rice", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Oat bran", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Oat flakes", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Oat flakes (Hercules)", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Oat grains", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Oat groats", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Pearl barley", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Pearl barley porridge", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Polished round-grain rice", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Potato flakes", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Puc", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Quinoa", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Rice bran", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Rice flakes", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Risotto", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Rye bran", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Rye flakes", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Rye grains", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Semolina", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Semolina porridge", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Shirataki fettuccine", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Shirataki noodles", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Shirataki rice", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Sorghum cereal", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Sorghum grains", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Spelt", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Sprouted wheat", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Sushi rice", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Tapioca starch", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Teff", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Triticale", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Wheat bran", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Wheat flakes", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Wheat grains", type: .grainsAndPorridge),
                  GrainsAndPorridge(name: "Wheat groats", type: .grainsAndPorridge)
]
