//
//  GrainsAndPorridgeData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 16.10.2023.
//

import Foundation

let grainsAndPorridge = [GrainsAndPorridge(name: "Almond flour", type: .grainsAndPorridge, calories: "625"),
                         GrainsAndPorridge(name: "Amaranth", type: .grainsAndPorridge, calories: "371"),
                         GrainsAndPorridge(name: "Arborio rice", type: .grainsAndPorridge, calories: "350"),
                         GrainsAndPorridge(name: "Barley flakes", type: .grainsAndPorridge, calories: "316"),
                         GrainsAndPorridge(name: "Barley grains", type: .grainsAndPorridge, calories: "354"),
                         GrainsAndPorridge(name: "Barley groats", type: .grainsAndPorridge, calories: "354"),
                         GrainsAndPorridge(name: "Basmati rice", type: .grainsAndPorridge, calories: "350"),
                         GrainsAndPorridge(name: "Black rice (Wild rice)", type: .grainsAndPorridge, calories: "360"),
                         GrainsAndPorridge(name: "Boiled buckwheat", type: .grainsAndPorridge, calories: "343"),
                         GrainsAndPorridge(name: "Boiled rice", type: .grainsAndPorridge, calories: "130"),
                         GrainsAndPorridge(name: "Bran", type: .grainsAndPorridge, calories: "216"),
                         GrainsAndPorridge(name: "Brown rice", type: .grainsAndPorridge, calories: "370"),
                         GrainsAndPorridge(name: "Buckwheat groats", type: .grainsAndPorridge, calories: "343"),
                         GrainsAndPorridge(name: "Buckwheat kernels", type: .grainsAndPorridge, calories: "343"),
                         GrainsAndPorridge(name: "Bulgur", type: .grainsAndPorridge, calories: "342"),
                         GrainsAndPorridge(name: "Canned chickpeas", type: .grainsAndPorridge, calories: "164"),
                         GrainsAndPorridge(name: "Canned corn", type: .grainsAndPorridge, calories: "96"),
                         GrainsAndPorridge(name: "Carnaroli rice", type: .grainsAndPorridge, calories: "350"),
                         GrainsAndPorridge(name: "Cereals", type: .grainsAndPorridge, calories: "380"),
                         GrainsAndPorridge(name: "Chickpeas", type: .grainsAndPorridge, calories: "378"),
                         GrainsAndPorridge(name: "Corn flakes", type: .grainsAndPorridge, calories: "381"),
                         GrainsAndPorridge(name: "Corn porridge", type: .grainsAndPorridge, calories: "96"),
                         GrainsAndPorridge(name: "Cornmeal", type: .grainsAndPorridge, calories: "358"),
                         GrainsAndPorridge(name: "Couscous", type: .grainsAndPorridge, calories: "376"),
                         GrainsAndPorridge(name: "Delicate shirataki spaghetti", type: .grainsAndPorridge, calories: "4"),
                         GrainsAndPorridge(name: "Flaxseed porridge", type: .grainsAndPorridge, calories: "234"),
                         GrainsAndPorridge(name: "Fusigon rice", type: .grainsAndPorridge, calories: "350"),
                         GrainsAndPorridge(name: "Golden rice", type: .grainsAndPorridge, calories: "130"),
                         GrainsAndPorridge(name: "Jasmine rice", type: .grainsAndPorridge, calories: "350"),
                         GrainsAndPorridge(name: "Long-grain rice", type: .grainsAndPorridge, calories: "350"),
                         GrainsAndPorridge(name: "Millet", type: .grainsAndPorridge, calories: "378"),
                         GrainsAndPorridge(name: "Morap", type: .grainsAndPorridge, calories: "378"),
                         GrainsAndPorridge(name: "Nishiki rice", type: .grainsAndPorridge, calories: "350"),
                         GrainsAndPorridge(name: "Oat bran", type: .grainsAndPorridge, calories: "216"),
                         GrainsAndPorridge(name: "Oat flakes", type: .grainsAndPorridge, calories: "379"),
                         GrainsAndPorridge(name: "Oat flakes (Hercules)", type: .grainsAndPorridge, calories: "379"),
                         GrainsAndPorridge(name: "Oat grains", type: .grainsAndPorridge, calories: "389"),
                         GrainsAndPorridge(name: "Oat groats", type: .grainsAndPorridge, calories: "389"),
                         GrainsAndPorridge(name: "Pearl barley", type: .grainsAndPorridge, calories: "354"),
                         GrainsAndPorridge(name: "Pearl barley porridge", type: .grainsAndPorridge, calories: "88"),
                         GrainsAndPorridge(name: "Polished round-grain rice", type: .grainsAndPorridge, calories: "130"),
                         GrainsAndPorridge(name: "Potato flakes", type: .grainsAndPorridge, calories: "353"),
                         GrainsAndPorridge(name: "Quinoa", type: .grainsAndPorridge, calories: "368"),
                         GrainsAndPorridge(name: "Rice", type: .grainsAndPorridge, calories: "130"),
                         GrainsAndPorridge(name: "Rice bran", type: .grainsAndPorridge, calories: "216"),
                         GrainsAndPorridge(name: "Rice flakes", type: .grainsAndPorridge, calories: "350"),
                         GrainsAndPorridge(name: "Risotto", type: .grainsAndPorridge, calories: "130"),
                         GrainsAndPorridge(name: "Rye bran", type: .grainsAndPorridge, calories: "216"),
                         GrainsAndPorridge(name: "Rye flakes", type: .grainsAndPorridge, calories: "338"),
                         GrainsAndPorridge(name: "Rye grains", type: .grainsAndPorridge, calories: "338"),
                         GrainsAndPorridge(name: "Sago", type: .grainsAndPorridge, calories: "358"),
                         GrainsAndPorridge(name: "Semolina", type: .grainsAndPorridge, calories: "358"),
                         GrainsAndPorridge(name: "Semolina porridge", type: .grainsAndPorridge, calories: "100"),
                         GrainsAndPorridge(name: "Shirataki fettuccine", type: .grainsAndPorridge, calories: "4"),
                         GrainsAndPorridge(name: "Shirataki noodles", type: .grainsAndPorridge, calories: "4"),
                         GrainsAndPorridge(name: "Shirataki rice", type: .grainsAndPorridge, calories: "4"),
                         GrainsAndPorridge(name: "Sorghum cereal", type: .grainsAndPorridge, calories: "329"),
                         GrainsAndPorridge(name: "Sorghum grains", type: .grainsAndPorridge, calories: "329"),
                         GrainsAndPorridge(name: "Spelt", type: .grainsAndPorridge, calories: "338"),
                         GrainsAndPorridge(name: "Sprouted wheat", type: .grainsAndPorridge, calories: "49"),
                         GrainsAndPorridge(name: "Sushi rice", type: .grainsAndPorridge, calories: "350"),
                         GrainsAndPorridge(name: "Tapioca starch", type: .grainsAndPorridge, calories: "358"),
                         GrainsAndPorridge(name: "Teff", type: .grainsAndPorridge, calories: "367"),
                         GrainsAndPorridge(name: "Triticale", type: .grainsAndPorridge, calories: "354"),
                         GrainsAndPorridge(name: "Wheat bran", type: .grainsAndPorridge, calories: "216"),
                         GrainsAndPorridge(name: "Wheat flakes", type: .grainsAndPorridge, calories: "340"),
                         GrainsAndPorridge(name: "Wheat grains", type: .grainsAndPorridge, calories: "340"),
                         GrainsAndPorridge(name: "Wheat groats", type: .grainsAndPorridge, calories: "354")]

