//
//  GreensAndHerbsData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 16.10.2023.
//

import Foundation

let greensAndHerbs = [GreensAndHerbs(name: "Aficon salad", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Air", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Alfalfa grass", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Aloe Leaves", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Amaranth leaves", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Angelica", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Arnica mountain", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Asparagus", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Bamboo leaves", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Bamboo shoots", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Basil", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Batavia salad", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Bazella", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Bedrenets saxifrage", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Beet tops", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Bodyak ogorodny", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Borago borage (borage)", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Burdock (burdock)", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Burdock root (burdock)", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Buten tuberous", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Calendula flowers", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Canned bamboo", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Canned basil", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Canned dill", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Canned parsley", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Canned sorrel", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Canned spinach", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Carrot tops", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Celery", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Chamomile flowers", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Chard", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Cherry leaves", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Chrysanthemum flowers", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Chrysanthemum leaves", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Cilantro", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Citrus flowers", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Clover", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Cognac plant (konnyaku)", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Common arrow leaf (Bolotnik)", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Cornflowers", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Crocus flowers", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Currant leaves", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Curry leaves", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Dahlia flowers", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Daisy Flowers", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Dandelion", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Devyasil", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Dill", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Donnik medicinal", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Dried green onion", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Echinacea", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Edible cacti", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Edible flowers", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Elsgoltsia", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Endive", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Eucalyptus leaves", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Fennel", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Fennel Root", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Fenugreek hay (fenugreek)", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Fern", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Field salad", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Fine herbs", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Flower Rose", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Flowers Tulips", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Flowers pansies", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Fresh greens", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Frozen spinach", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Fuchsia", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Garlic Arrows", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Geranium flowers", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Gladiolus", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Grape leaves", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Grass Shepherd's bag", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Green basil", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Green onion", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Herb Immortelle", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Herb gulyavnik medicinal", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Hibiscus flowers (Sudanese rose)", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Hogweed", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Horseradish", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Horseradish leaves", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Horsetail field", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Hyssop", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Iceberg Lettuce", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Iris plant", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Jasmine", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Kiprei (Ivan-tea)", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Kupyr (Chervil)", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Lakonos", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Lavender", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Leek", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Lemon grass", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Lemon verbena", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Lettuce", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Lily Flowers", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Lime leaves", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Linden flowers", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Lollo rossa salad", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Long-term gravilat", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Lotus", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Lovebirds", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Lupin", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Mallow", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Maranta", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Marigold flowers", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Marjoram", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Mash salad", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Medicinal Melissa", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Medicinal asp", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Milk thistle spotted (thistle)", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Mint", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Mitsuna salad", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Monarda", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Mother-and-stepmother", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Mustard leaf", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Nasturtium", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Nettle", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Nightshade black", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Oakleaf salad", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Onion-batun", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Orchid", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Oregano (oregano)", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Parsley", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Patchouli", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Perilla", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Pickled bamboo", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Pickled basil", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Pickled cilantro", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Pickled greens", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Pickled lettuce leaves", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Pickled parsley", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Pickled purslane", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Pineapple leaves", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Plantain", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Plumeria (frangipani)", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Prickly pear", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Prickly pear Indian (fig)", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Primrose", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Purslane", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Quinoa garden", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Radicchio salad", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Rank plant", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Red basil", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Romano salad", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Roots", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Rose petals", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Rosebuds", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Rosehip leaves", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Rosemary", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Rucola", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Sage", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Salad", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Salad frise", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Savory", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Shnitt-onion", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Smilax (sassaparil)", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Snyt grass", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Sorrel", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Sour (hare cabbage)", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Spinach", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Stevia herb", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Sunflower", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Sweet rue", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Tarragon", type: .greensAndHerbs),
                  GreensAndHerbs(name: "The Squirrel (Fuki)", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Thyme (thyme)", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Valerian", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Violet flowers", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Watercress", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Wild cherry", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Willow leaves", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Wormwood", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Yarrow", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Yasmennik odorous", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Ylang-ylang flowers", type: .greensAndHerbs),
                  GreensAndHerbs(name: "Yucca flowers", type: .greensAndHerbs)
]
