//
//  MeatProductsData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 15.10.2023.
//

import Foundation

let meatProducts = [FoodRealm(name: "Amateur sausage", type: .meatProducts, calories: "300"),
                    FoodRealm(name: "Bacon", type: .meatProducts, calories: "417"),
                    FoodRealm(name: "Basturma", type: .meatProducts, calories: "243"),
                    FoodRealm(name: "Bear Meat", type: .meatProducts, calories: "142"),
                    FoodRealm(name: "Beef", type: .meatProducts, calories: "164"),
                    FoodRealm(name: "Beef Goulash", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Beef Romsteak", type: .meatProducts, calories: "190"),
                    FoodRealm(name: "Beef Stroganoff", type: .meatProducts, calories: "205"),
                    FoodRealm(name: "Beef Stroganoff from beef", type: .meatProducts, calories: "205"),
                    FoodRealm(name: "Beef Stroganoff from chicken", type: .meatProducts, calories: "190"),
                    FoodRealm(name: "Beef Stroganoff from pork", type: .meatProducts, calories: "240"),
                    FoodRealm(name: "Beef brains", type: .meatProducts, calories: "150"),
                    FoodRealm(name: "Beef brisket", type: .meatProducts, calories: "175"),
                    FoodRealm(name: "Beef diaphragm", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Beef entrecote", type: .meatProducts, calories: "210"),
                    FoodRealm(name: "Beef fillet", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Beef heart", type: .meatProducts, calories: "121"),
                    FoodRealm(name: "Beef kidneys", type: .meatProducts, calories: "88"),
                    FoodRealm(name: "Beef liver", type: .meatProducts, calories: "135"),
                    FoodRealm(name: "Beef lung", type: .meatProducts, calories: "110"),
                    FoodRealm(name: "Beef okovalok", type: .meatProducts, calories: "175"),
                    FoodRealm(name: "Beef ribs", type: .meatProducts, calories: "217"),
                    FoodRealm(name: "Beef roast beef", type: .meatProducts, calories: "175"),
                    FoodRealm(name: "Beef rump", type: .meatProducts, calories: "175"),
                    FoodRealm(name: "Beef sausage", type: .meatProducts, calories: "322"),
                    FoodRealm(name: "Beef spleen", type: .meatProducts, calories: "110"),
                    FoodRealm(name: "Beef steak", type: .meatProducts, calories: "175"),
                    FoodRealm(name: "Beef stew", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Beef tail", type: .meatProducts, calories: "217"),
                    FoodRealm(name: "Beef tenderloin", type: .meatProducts, calories: "135"),
                    FoodRealm(name: "Beef tongue", type: .meatProducts, calories: "135"),
                    FoodRealm(name: "Beef tripe", type: .meatProducts, calories: "75"),
                    FoodRealm(name: "Beef udder", type: .meatProducts, calories: "110"),
                    FoodRealm(name: "Black grouse meat", type: .meatProducts, calories: "108"),
                    FoodRealm(name: "Black pudding", type: .meatProducts, calories: "317"),
                    FoodRealm(name: "Boiled sausage", type: .meatProducts, calories: "322"),
                    FoodRealm(name: "Boiled sausage Doctor", type: .meatProducts, calories: "225"),
                    FoodRealm(name: "Braunschweig sausage", type: .meatProducts, calories: "322"),
                    FoodRealm(name: "Brawn sausage", type: .meatProducts, calories: "190"),
                    FoodRealm(name: "Bresaola", type: .meatProducts, calories: "243"),
                    FoodRealm(name: "Broiler chickens", type: .meatProducts, calories: "190"),
                    FoodRealm(name: "Buffalo meat", type: .meatProducts, calories: "110"),
                    FoodRealm(name: "Bull's eggs", type: .meatProducts, calories: "88"),
                    FoodRealm(name: "Buzhenina", type: .meatProducts, calories: "243"),
                    FoodRealm(name: "By-products", type: .meatProducts, calories: "75"),
                    FoodRealm(name: "Camel meat", type: .meatProducts, calories: "110"),
                    FoodRealm(name: "Canned chicken", type: .meatProducts, calories: "120"),
                    FoodRealm(name: "Canned ham", type: .meatProducts, calories: "217"),
                    FoodRealm(name: "Canned meat", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Canned minced meat", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Canned sausages", type: .meatProducts, calories: "225"),
                    FoodRealm(name: "Canned tongue", type: .meatProducts, calories: "160"),
                    FoodRealm(name: "Chick", type: .meatProducts, calories: "190"),
                    FoodRealm(name: "Chicken", type: .meatProducts, calories: "190"),
                    FoodRealm(name: "Chicken Goulash", type: .meatProducts, calories: "190"),
                    FoodRealm(name: "Chicken Soup Set", type: .meatProducts, calories: "190"),
                    FoodRealm(name: "Chicken backs", type: .meatProducts, calories: "217"),
                    FoodRealm(name: "Chicken breast", type: .meatProducts, calories: "110"),
                    FoodRealm(name: "Chicken broth", type: .meatProducts, calories: "45"),
                    FoodRealm(name: "Chicken drumstick", type: .meatProducts, calories: "190"),
                    FoodRealm(name: "Chicken feet", type: .meatProducts, calories: "240"),
                    FoodRealm(name: "Chicken fillet", type: .meatProducts, calories: "110"),
                    FoodRealm(name: "Chicken giblets", type: .meatProducts, calories: "110"),
                    FoodRealm(name: "Chicken ham", type: .meatProducts, calories: "283"),
                    FoodRealm(name: "Chicken heads", type: .meatProducts, calories: "240"),
                    FoodRealm(name: "Chicken hearts", type: .meatProducts, calories: "121"),
                    FoodRealm(name: "Chicken legs", type: .meatProducts, calories: "190"),
                    FoodRealm(name: "Chicken liver", type: .meatProducts, calories: "121"),
                    FoodRealm(name: "Chicken necks", type: .meatProducts, calories: "217"),
                    FoodRealm(name: "Chicken nuggets", type: .meatProducts, calories: "257"),
                    FoodRealm(name: "Chicken roll", type: .meatProducts, calories: "190"),
                    FoodRealm(name: "Chicken sausage", type: .meatProducts, calories: "280"),
                    FoodRealm(name: "Chicken schnitzel", type: .meatProducts, calories: "230"),
                    FoodRealm(name: "Chicken skin", type: .meatProducts, calories: "322"),
                    FoodRealm(name: "Chicken tail", type: .meatProducts, calories: "217"),
                    FoodRealm(name: "Chicken thighs", type: .meatProducts, calories: "190"),
                    FoodRealm(name: "Chicken ventricles", type: .meatProducts, calories: "121"),
                    FoodRealm(name: "Chicken wings", type: .meatProducts, calories: "217"),
                    FoodRealm(name: "Chorizo sausage", type: .meatProducts, calories: "417"),
                    FoodRealm(name: "Crocodile meat", type: .meatProducts, calories: "110"),
                    FoodRealm(name: "Dairy sausage", type: .meatProducts, calories: "322"),
                    FoodRealm(name: "Diet sausage", type: .meatProducts, calories: "117"),
                    FoodRealm(name: "Dried meat", type: .meatProducts, calories: "240"),
                    FoodRealm(name: "Dried sausage", type: .meatProducts, calories: "417"),
                    FoodRealm(name: "Duck liver", type: .meatProducts, calories: "184"),
                    FoodRealm(name: "Duck meat", type: .meatProducts, calories: "184"),
                    FoodRealm(name: "Entrecote", type: .meatProducts, calories: "210"),
                    FoodRealm(name: "Escalope", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Foie gras pate", type: .meatProducts, calories: "184"),
                    FoodRealm(name: "Frog legs", type: .meatProducts, calories: "82"),
                    FoodRealm(name: "Gherkin chickens", type: .meatProducts, calories: "190"),
                    FoodRealm(name: "Goat meat", type: .meatProducts, calories: "108"),
                    FoodRealm(name: "Goose liver", type: .meatProducts, calories: "184"),
                    FoodRealm(name: "Goose meat", type: .meatProducts, calories: "184"),
                    FoodRealm(name: "Goulash", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Grape snail", type: .meatProducts, calories: "90"),
                    FoodRealm(name: "Ground beef", type: .meatProducts, calories: "175"),
                    FoodRealm(name: "Grouse Meat", type: .meatProducts, calories: "108"),
                    FoodRealm(name: "Guinea Fowl Meat", type: .meatProducts, calories: "144"),
                    FoodRealm(name: "Ham", type: .meatProducts, calories: "217"),
                    FoodRealm(name: "Hazel grouse meat", type: .meatProducts, calories: "108"),
                    FoodRealm(name: "Ham ham", type: .meatProducts, calories: "217"),
                    FoodRealm(name: "Heart of mutton", type: .meatProducts, calories: "121"),
                    FoodRealm(name: "Homemade liver sausage", type: .meatProducts, calories: "290"),
                    FoodRealm(name: "Homemade sausage", type: .meatProducts, calories: "300"),
                    FoodRealm(name: "Horse meat", type: .meatProducts, calories: "128"),
                    FoodRealm(name: "Hunting sausages", type: .meatProducts, calories: "225"),
                    FoodRealm(name: "Kazy Horse sausage", type: .meatProducts, calories: "417"),
                    FoodRealm(name: "Krakow sausage", type: .meatProducts, calories: "322"),
                    FoodRealm(name: "Kupaty", type: .meatProducts, calories: "300"),
                    FoodRealm(name: "Lamb Meat", type: .meatProducts, calories: "164"),
                    FoodRealm(name: "Lamb Saddle", type: .meatProducts, calories: "164"),
                    FoodRealm(name: "Lamb eggs", type: .meatProducts, calories: "88"),
                    FoodRealm(name: "Lamb leg", type: .meatProducts, calories: "175"),
                    FoodRealm(name: "Lamb liver", type: .meatProducts, calories: "121"),
                    FoodRealm(name: "Lamb minced meat", type: .meatProducts, calories: "164"),
                    FoodRealm(name: "Lamb sausage", type: .meatProducts, calories: "280"),
                    FoodRealm(name: "Lamb square", type: .meatProducts, calories: "175"),
                    FoodRealm(name: "Langet", type: .meatProducts, calories: "243"),
                    FoodRealm(name: "Lard Lardo", type: .meatProducts, calories: "902"),
                    FoodRealm(name: "Lean minced meat", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Liver pate", type: .meatProducts, calories: "290"),
                    FoodRealm(name: "Liver sausage", type: .meatProducts, calories: "290"),
                    FoodRealm(name: "Marbled beef", type: .meatProducts, calories: "190"),
                    FoodRealm(name: "Marbled beef steak", type: .meatProducts, calories: "190"),
                    FoodRealm(name: "Marinated chicken fillet", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Meat", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Meat bread", type: .meatProducts, calories: "300"),
                    FoodRealm(name: "Meat broth", type: .meatProducts, calories: "45"),
                    FoodRealm(name: "Meat meatballs", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Meat pate", type: .meatProducts, calories: "300"),
                    FoodRealm(name: "Meat products", type: .meatProducts, calories: "300"),
                    FoodRealm(name: "Meat semi-finished products", type: .meatProducts, calories: "150"),
                    FoodRealm(name: "Meatballs", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Meatloaf", type: .meatProducts, calories: "230"),
                    FoodRealm(name: "Milk sausages", type: .meatProducts, calories: "225"),
                    FoodRealm(name: "Minced chicken", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Minced meat", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Minced meat patties", type: .meatProducts, calories: "155"),
                    FoodRealm(name: "Minced pork", type: .meatProducts, calories: "242"),
                    FoodRealm(name: "Minced rabbit", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Minced sausage", type: .meatProducts, calories: "300"),
                    FoodRealm(name: "Mincemeat", type: .meatProducts, calories: "300"),
                    FoodRealm(name: "Moose meat", type: .meatProducts, calories: "142"),
                    FoodRealm(name: "Mortadella sausage", type: .meatProducts, calories: "322"),
                    FoodRealm(name: "Moscow sausage", type: .meatProducts, calories: "225"),
                    FoodRealm(name: "Ostrich meat", type: .meatProducts, calories: "97"),
                    FoodRealm(name: "Pancetta", type: .meatProducts, calories: "322"),
                    FoodRealm(name: "Parma ham", type: .meatProducts, calories: "322"),
                    FoodRealm(name: "Partridge meat", type: .meatProducts, calories: "157"),
                    FoodRealm(name: "Pepperoni sausage", type: .meatProducts, calories: "417"),
                    FoodRealm(name: "Pheasant meat", type: .meatProducts, calories: "157"),
                    FoodRealm(name: "Pickled bacon", type: .meatProducts, calories: "270"),
                    FoodRealm(name: "Pickled chicken legs", type: .meatProducts, calories: "160"),
                    FoodRealm(name: "Pickled chicken wings", type: .meatProducts, calories: "270"),
                    FoodRealm(name: "Pickled frozen kebab", type: .meatProducts, calories: "155"),
                    FoodRealm(name: "Pickled liver", type: .meatProducts, calories: "135"),
                    FoodRealm(name: "Pickled meat", type: .meatProducts, calories: "155"),
                    FoodRealm(name: "Pickled pork ribs", type: .meatProducts, calories: "270"),
                    FoodRealm(name: "Pickled tongue", type: .meatProducts, calories: "160"),
                    FoodRealm(name: "Pig ears", type: .meatProducts, calories: "322"),
                    FoodRealm(name: "Pig tails", type: .meatProducts, calories: "322"),
                    FoodRealm(name: "Pig's head", type: .meatProducts, calories: "184"),
                    FoodRealm(name: "Pig's heart", type: .meatProducts, calories: "121"),
                    FoodRealm(name: "Pig's tongue", type: .meatProducts, calories: "160"),
                    FoodRealm(name: "Pigeon meat", type: .meatProducts, calories: "108"),
                    FoodRealm(name: "Porcine diaphragm", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Pork", type: .meatProducts, calories: "242"),
                    FoodRealm(name: "Pork Escalope", type: .meatProducts, calories: "242"),
                    FoodRealm(name: "Pork Goulash", type: .meatProducts, calories: "240"),
                    FoodRealm(name: "Pork Schnitzel", type: .meatProducts, calories: "265"),
                    FoodRealm(name: "Pork balyk", type: .meatProducts, calories: "242"),
                    FoodRealm(name: "Pork belly", type: .meatProducts, calories: "397"),
                    FoodRealm(name: "Pork brawn", type: .meatProducts, calories: "243"),
                    FoodRealm(name: "Pork carbonade", type: .meatProducts, calories: "242"),
                    FoodRealm(name: "Pork cheek", type: .meatProducts, calories: "242"),
                    FoodRealm(name: "Pork eggs", type: .meatProducts, calories: "88"),
                    FoodRealm(name: "Pork entrecote", type: .meatProducts, calories: "265"),
                    FoodRealm(name: "Pork fat (Lard)", type: .meatProducts, calories: "902"),
                    FoodRealm(name: "Pork fillet", type: .meatProducts, calories: "121"),
                    FoodRealm(name: "Pork frankfurters", type: .meatProducts, calories: "322"),
                    FoodRealm(name: "Pork ham", type: .meatProducts, calories: "270"),
                    FoodRealm(name: "Pork kidneys", type: .meatProducts, calories: "88"),
                    FoodRealm(name: "Pork knuckle", type: .meatProducts, calories: "210"),
                    FoodRealm(name: "Pork legs", type: .meatProducts, calories: "242"),
                    FoodRealm(name: "Pork liver", type: .meatProducts, calories: "121"),
                    FoodRealm(name: "Pork loin", type: .meatProducts, calories: "175"),
                    FoodRealm(name: "Pork lung", type: .meatProducts, calories: "110"),
                    FoodRealm(name: "Pork neck", type: .meatProducts, calories: "242"),
                    FoodRealm(name: "Pork ribs", type: .meatProducts, calories: "270"),
                    FoodRealm(name: "Pork sausages", type: .meatProducts, calories: "280"),
                    FoodRealm(name: "Pork skin", type: .meatProducts, calories: "322"),
                    FoodRealm(name: "Pork spleen", type: .meatProducts, calories: "110"),
                    FoodRealm(name: "Pork steak", type: .meatProducts, calories: "242"),
                    FoodRealm(name: "Pork stew", type: .meatProducts, calories: "240"),
                    FoodRealm(name: "Pork stomach", type: .meatProducts, calories: "110"),
                    FoodRealm(name: "Pork tenderloin", type: .meatProducts, calories: "135"),
                    FoodRealm(name: "Poultry meat", type: .meatProducts, calories: "190"),
                    FoodRealm(name: "Poultry meat semi-finished products", type: .meatProducts, calories: "150"),
                    FoodRealm(name: "Poultry sausage", type: .meatProducts, calories: "300"),
                    FoodRealm(name: "Prosciutto", type: .meatProducts, calories: "322"),
                    FoodRealm(name: "Quail Meat", type: .meatProducts, calories: "157"),
                    FoodRealm(name: "Rabbit kidneys", type: .meatProducts, calories: "88"),
                    FoodRealm(name: "Rabbit liver", type: .meatProducts, calories: "121"),
                    FoodRealm(name: "Rabbit meat", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Raw smoked sausage", type: .meatProducts, calories: "255"),
                    FoodRealm(name: "Roast Beef", type: .meatProducts, calories: "175"),
                    FoodRealm(name: "Roe Deer Meat", type: .meatProducts, calories: "142"),
                    FoodRealm(name: "Romsteak", type: .meatProducts, calories: "190"),
                    FoodRealm(name: "Salami sausage", type: .meatProducts, calories: "492"),
                    FoodRealm(name: "Salchichon sausage", type: .meatProducts, calories: "492"),
                    FoodRealm(name: "Salsiccia", type: .meatProducts, calories: "492"),
                    FoodRealm(name: "Salted lard", type: .meatProducts, calories: "322"),
                    FoodRealm(name: "Saltison", type: .meatProducts, calories: "243"),
                    FoodRealm(name: "Sandpiper bird", type: .meatProducts, calories: "108"),
                    FoodRealm(name: "Sausage products", type: .meatProducts, calories: "300"),
                    FoodRealm(name: "Sausages", type: .meatProducts, calories: "300"),
                    FoodRealm(name: "Sausages for beer", type: .meatProducts, calories: "225"),
                    FoodRealm(name: "Schnitzel", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Servelat sausage", type: .meatProducts, calories: "322"),
                    FoodRealm(name: "Sheepmeat", type: .meatProducts, calories: "142"),
                    FoodRealm(name: "Shpikachki", type: .meatProducts, calories: "300"),
                    FoodRealm(name: "Smoked bacon", type: .meatProducts, calories: "270"),
                    FoodRealm(name: "Smoked brisket", type: .meatProducts, calories: "243"),
                    FoodRealm(name: "Smoked cheek", type: .meatProducts, calories: "243"),
                    FoodRealm(name: "Smoked chicken", type: .meatProducts, calories: "160"),
                    FoodRealm(name: "Smoked chicken breast", type: .meatProducts, calories: "160"),
                    FoodRealm(name: "Smoked chicken legs", type: .meatProducts, calories: "160"),
                    FoodRealm(name: "Smoked chicken wings", type: .meatProducts, calories: "270"),
                    FoodRealm(name: "Smoked duck", type: .meatProducts, calories: "184"),
                    FoodRealm(name: "Smoked meat", type: .meatProducts, calories: "243"),
                    FoodRealm(name: "Smoked meats", type: .meatProducts, calories: "243"),
                    FoodRealm(name: "Smoked pork ears", type: .meatProducts, calories: "270"),
                    FoodRealm(name: "Smoked pork ham", type: .meatProducts, calories: "283"),
                    FoodRealm(name: "Smoked pork ribs", type: .meatProducts, calories: "270"),
                    FoodRealm(name: "Smoked sausage", type: .meatProducts, calories: "225"),
                    FoodRealm(name: "Smoked sausages", type: .meatProducts, calories: "225"),
                    FoodRealm(name: "Smoked tongue", type: .meatProducts, calories: "160"),
                    FoodRealm(name: "Snake Meat", type: .meatProducts, calories: "110"),
                    FoodRealm(name: "Snipe Bird", type: .meatProducts, calories: "108"),
                    FoodRealm(name: "Soy minced meat", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Suckling pig", type: .meatProducts, calories: "165"),
                    FoodRealm(name: "Sujuk", type: .meatProducts, calories: "417"),
                    FoodRealm(name: "Tongue sausage", type: .meatProducts, calories: "160"),
                    FoodRealm(name: "Turkey Hearts", type: .meatProducts, calories: "121"),
                    FoodRealm(name: "Turkey Liver", type: .meatProducts, calories: "121"),
                    FoodRealm(name: "Turkey Meat", type: .meatProducts, calories: "144"),
                    FoodRealm(name: "Turkey Necks", type: .meatProducts, calories: "217"),
                    FoodRealm(name: "Turkey Skin", type: .meatProducts, calories: "322"),
                    FoodRealm(name: "Turkey Wing", type: .meatProducts, calories: "217"),
                    FoodRealm(name: "Turkey breast", type: .meatProducts, calories: "135"),
                    FoodRealm(name: "Turkey drumstick", type: .meatProducts, calories: "190"),
                    FoodRealm(name: "Turkey fillet", type: .meatProducts, calories: "140"),
                    FoodRealm(name: "Turkey leg", type: .meatProducts, calories: "190"),
                    FoodRealm(name: "Turkey minced meat", type: .meatProducts, calories: "135"),
                    FoodRealm(name: "Turkey thigh", type: .meatProducts, calories: "144"),
                    FoodRealm(name: "Turkey ventricles", type: .meatProducts, calories: "121"),
                    FoodRealm(name: "Veal", type: .meatProducts, calories: "115"),
                    FoodRealm(name: "Venison", type: .meatProducts, calories: "142"),
                    FoodRealm(name: "Venison sausage", type: .meatProducts, calories: "300"),
                    FoodRealm(name: "Wiener sausages", type: .meatProducts, calories: "322"),
                    FoodRealm(name: "Wild Boar meat", type: .meatProducts, calories: "142"),
                    FoodRealm(name: "Woodcock bird", type: .meatProducts, calories: "108")]

