//
//  MushroomsData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 10.10.2023.
//

import Foundation

let mushrooms = [Mushrooms(name: "Aspen Mushroom", type: .mushrooms, calories: "28"),
                 Mushrooms(name: "Birch Chaga Mushroom", type: .mushrooms, calories: "28"),
                 Mushrooms(name: "Birch Mushroom", type: .mushrooms, calories: "22"),
                 Mushrooms(name: "Black Trumpet", type: .mushrooms, calories: "31"),
                 Mushrooms(name: "Caesar's Mushroom", type: .mushrooms, calories: "22"),
                 Mushrooms(name: "Canned Champignon Mushrooms", type: .mushrooms, calories: "22"),
                 Mushrooms(name: "Canned Mushrooms", type: .mushrooms, calories: "22"),
                 Mushrooms(name: "Canned White Mushrooms", type: .mushrooms, calories: "22"),
                 Mushrooms(name: "Champignon Mushrooms", type: .mushrooms, calories: "22"),
                 Mushrooms(name: "Chanterelle Mushrooms", type: .mushrooms, calories: "38"),
                 Mushrooms(name: "Chanterelles", type: .mushrooms, calories: "38"),
                 Mushrooms(name: "Chanterelles", type: .mushrooms, calories: "38"),
                 Mushrooms(name: "Cremini Mushrooms", type: .mushrooms, calories: "22"),
                 Mushrooms(name: "Dried Aspen Mushroom", type: .mushrooms, calories: "302"),
                 Mushrooms(name: "Dried Birch Mushroom", type: .mushrooms, calories: "302"),
                 Mushrooms(name: "Dried Champignon Mushrooms", type: .mushrooms, calories: "228"),
                 Mushrooms(name: "Dried Chanterelles", type: .mushrooms, calories: "314"),
                 Mushrooms(name: "Dried Mushrooms", type: .mushrooms, calories: "228"),
                 Mushrooms(name: "Dried White Mushroom", type: .mushrooms, calories: "228"),
                 Mushrooms(name: "Enoki Mushrooms", type: .mushrooms, calories: "23"),
                 Mushrooms(name: "False Morel", type: .mushrooms, calories: "28"),
                 Mushrooms(name: "Frozen Mushrooms", type: .mushrooms, calories: "22"),
                 Mushrooms(name: "Gypsy Mushroom", type: .mushrooms, calories: "28"),
                 Mushrooms(name: "Half-free Morel", type: .mushrooms, calories: "28"),
                 Mushrooms(name: "Hedgehog Mushroom", type: .mushrooms, calories: "28"),
                 Mushrooms(name: "Hedgehog Mushrooms", type: .mushrooms, calories: "28"),
                 Mushrooms(name: "Hen of the Woods Mushroom", type: .mushrooms, calories: "28"),
                 Mushrooms(name: "Honey Agaric Mushrooms", type: .mushrooms, calories: "28"),
                 Mushrooms(name: "Honey Mushroom", type: .mushrooms, calories: "28"),
                 Mushrooms(name: "Honey Mushrooms", type: .mushrooms, calories: "28"),
                 Mushrooms(name: "Hygrophorus Mushroom", type: .mushrooms, calories: "28"),
                 Mushrooms(name: "King Oyster Mushrooms", type: .mushrooms, calories: "25"),
                 Mushrooms(name: "Lingzhi Mushroom", type: .mushrooms, calories: "22"),
                 Mushrooms(name: "Maitake Mushroom", type: .mushrooms, calories: "35"),
                 Mushrooms(name: "Marinated Champignon Mushrooms", type: .mushrooms, calories: "26"),
                 Mushrooms(name: "Marinated Chanterelles", type: .mushrooms, calories: "41"),
                 Mushrooms(name: "Marinated Honey Agaric Mushrooms", type: .mushrooms, calories: "33"),
                 Mushrooms(name: "Marinated Honey Fungus", type: .mushrooms, calories: "33"),
                 Mushrooms(name: "Marinated Honey Mushrooms", type: .mushrooms, calories: "33"),
                 Mushrooms(name: "Marinated Mushroom Assortment", type: .mushrooms, calories: "30"),
                 Mushrooms(name: "Marinated Mushrooms", type: .mushrooms, calories: "30"),
                 Mushrooms(name: "Marinated Shimeji Mushrooms", type: .mushrooms, calories: "25"),
                 Mushrooms(name: "Marinated White Mushrooms", type: .mushrooms, calories: "26"),
                 Mushrooms(name: "Meadow Mushroom", type: .mushrooms, calories: "28"),
                 Mushrooms(name: "Mossy Mushroom", type: .mushrooms, calories: "22"),
                 Mushrooms(name: "Mushroom Caviar", type: .mushrooms, calories: "65"),
                 Mushrooms(name: "Oak Mushroom", type: .mushrooms, calories: "28"),
                 Mushrooms(name: "Orange-cap Boletus", type: .mushrooms, calories: "35"),
                 Mushrooms(name: "Parasol Mushroom", type: .mushrooms, calories: "31"),
                 Mushrooms(name: "Polish Mushroom", type: .mushrooms, calories: "35"),
                 Mushrooms(name: "Porcini Mushroom", type: .mushrooms, calories: "35"),
                 Mushrooms(name: "Portobello Mushrooms", type: .mushrooms, calories: "29"),
                 Mushrooms(name: "Purple Coral Mushroom", type: .mushrooms, calories: "28"),
                 Mushrooms(name: "Ram's Head Mushroom", type: .mushrooms, calories: "35"),
                 Mushrooms(name: "Royal Oyster Mushroom", type: .mushrooms, calories: "27"),
                 Mushrooms(name: "Russula Mushroom", type: .mushrooms, calories: "28"),
                 Mushrooms(name: "Salted Orange-cap Boletus", type: .mushrooms, calories: "393"),
                 Mushrooms(name: "Shaggy Mane Mushrooms", type: .mushrooms, calories: "28"),
                 Mushrooms(name: "Shaggy Parasol Mushrooms", type: .mushrooms, calories: "31"),
                 Mushrooms(name: "Shiitake Mushrooms", type: .mushrooms, calories: "34"),
                 Mushrooms(name: "Shimeji Mushrooms", type: .mushrooms, calories: "23"),
                 Mushrooms(name: "Slippery Jack Mushroom", type: .mushrooms, calories: "35"),
                 Mushrooms(name: "Sparassis Crispa", type: .mushrooms, calories: "19"),
                 Mushrooms(name: "Truffle", type: .mushrooms, calories: "384"),
                 Mushrooms(name: "Velvet Shank", type: .mushrooms, calories: "28"),
                 Mushrooms(name: "White Mushroom", type: .mushrooms, calories: "22"),
                 Mushrooms(name: "White Steppe Mushroom (Erinji)", type: .mushrooms, calories: "28"),
                 Mushrooms(name: "White Truffle", type: .mushrooms, calories: "384"),
                 Mushrooms(name: "Winter Chanterelle", type: .mushrooms, calories: "38"),
                 Mushrooms(name: "Yellow Hedgehog Mushroom", type: .mushrooms, calories: "74")]
