//
//  NutsAndDriedFruitsData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 16.10.2023.
//

import Foundation

let nutsAndDriedFruits = [NutsAndDriedFruits(name: "Apricot pits", type: .nutsAndDriedFruits, calories: "576"),
                          NutsAndDriedFruits(name: "Beech nut", type: .nutsAndDriedFruits, calories: "628"),
                          NutsAndDriedFruits(name: "Bitter almonds", type: .nutsAndDriedFruits, calories: "625"),
                          NutsAndDriedFruits(name: "Brazilian opex", type: .nutsAndDriedFruits, calories: "656"),
                          NutsAndDriedFruits(name: "Candied apples", type: .nutsAndDriedFruits, calories: "250"),
                          NutsAndDriedFruits(name: "Candied fruits", type: .nutsAndDriedFruits, calories: "280"),
                          NutsAndDriedFruits(name: "Candied ginger", type: .nutsAndDriedFruits, calories: "260"),
                          NutsAndDriedFruits(name: "Candied melon", type: .nutsAndDriedFruits, calories: "280"),
                          NutsAndDriedFruits(name: "Candied orange", type: .nutsAndDriedFruits, calories: "280"),
                          NutsAndDriedFruits(name: "Candied papaya", type: .nutsAndDriedFruits, calories: "280"),
                          NutsAndDriedFruits(name: "Candied pears", type: .nutsAndDriedFruits, calories: "280"),
                          NutsAndDriedFruits(name: "Candied pineapple", type: .nutsAndDriedFruits, calories: "280"),
                          NutsAndDriedFruits(name: "Candied watermelon crusts", type: .nutsAndDriedFruits, calories: "280"),
                          NutsAndDriedFruits(name: "Canned chestnuts", type: .nutsAndDriedFruits, calories: "170"),
                          NutsAndDriedFruits(name: "Cashews", type: .nutsAndDriedFruits, calories: "553"),
                          NutsAndDriedFruits(name: "Chilim nut", type: .nutsAndDriedFruits, calories: "672"),
                          NutsAndDriedFruits(name: "Chufa (Ground almonds)", type: .nutsAndDriedFruits, calories: "625"),
                          NutsAndDriedFruits(name: "Coconut opex", type: .nutsAndDriedFruits, calories: "660"),
                          NutsAndDriedFruits(name: "Cucui nuts", type: .nutsAndDriedFruits, calories: "525"),
                          NutsAndDriedFruits(name: "Dates", type: .nutsAndDriedFruits, calories: "282"),
                          NutsAndDriedFruits(name: "Dried Fruits", type: .nutsAndDriedFruits, calories: "280"),
                          NutsAndDriedFruits(name: "Dried Hawthorn", type: .nutsAndDriedFruits, calories: "240"),
                          NutsAndDriedFruits(name: "Dried apples", type: .nutsAndDriedFruits, calories: "218"),
                          NutsAndDriedFruits(name: "Dried apricots", type: .nutsAndDriedFruits, calories: "248"),
                          NutsAndDriedFruits(name: "Dried bananas", type: .nutsAndDriedFruits, calories: "300"),
                          NutsAndDriedFruits(name: "Dried barberry", type: .nutsAndDriedFruits, calories: "280"),
                          NutsAndDriedFruits(name: "Dried cherry", type: .nutsAndDriedFruits, calories: "310"),
                          NutsAndDriedFruits(name: "Dried cranberries", type: .nutsAndDriedFruits, calories: "308"),
                          NutsAndDriedFruits(name: "Dried date", type: .nutsAndDriedFruits, calories: "282"),
                          NutsAndDriedFruits(name: "Dried figs", type: .nutsAndDriedFruits, calories: "249"),
                          NutsAndDriedFruits(name: "Dried kumquat", type: .nutsAndDriedFruits, calories: "240"),
                          NutsAndDriedFruits(name: "Dried mango", type: .nutsAndDriedFruits, calories: "60"),
                          NutsAndDriedFruits(name: "Dried melon", type: .nutsAndDriedFruits, calories: "280"),
                          NutsAndDriedFruits(name: "Dried peanuts", type: .nutsAndDriedFruits, calories: "567"),
                          NutsAndDriedFruits(name: "Dried pears", type: .nutsAndDriedFruits, calories: "218"),
                          NutsAndDriedFruits(name: "Dried rosehip", type: .nutsAndDriedFruits, calories: "240"),
                          NutsAndDriedFruits(name: "Flax seeds", type: .nutsAndDriedFruits, calories: "534"),
                          NutsAndDriedFruits(name: "Fresh chestnut", type: .nutsAndDriedFruits, calories: "180"),
                          NutsAndDriedFruits(name: "Fruit chips", type: .nutsAndDriedFruits, calories: "450"),
                          NutsAndDriedFruits(name: "Fruits of the shea tree (karite)", type: .nutsAndDriedFruits, calories: "600"),
                          NutsAndDriedFruits(name: "Hazelnut", type: .nutsAndDriedFruits, calories: "628"),
                          NutsAndDriedFruits(name: "Hazelnuts", type: .nutsAndDriedFruits, calories: "628"),
                          NutsAndDriedFruits(name: "Jerked cranberries", type: .nutsAndDriedFruits, calories: "308"),
                          NutsAndDriedFruits(name: "Kishmish raisins", type: .nutsAndDriedFruits, calories: "299"),
                          NutsAndDriedFruits(name: "Kola nut", type: .nutsAndDriedFruits, calories: "186"),
                          NutsAndDriedFruits(name: "Macadamia nut", type: .nutsAndDriedFruits, calories: "718"),
                          NutsAndDriedFruits(name: "Nuts", type: .nutsAndDriedFruits, calories: "600"),
                          NutsAndDriedFruits(name: "Nuts acorns", type: .nutsAndDriedFruits, calories: "690"),
                          NutsAndDriedFruits(name: "Peanuts", type: .nutsAndDriedFruits, calories: "567"),
                          NutsAndDriedFruits(name: "Pecan", type: .nutsAndDriedFruits, calories: "691"),
                          NutsAndDriedFruits(name: "Pine nut cake", type: .nutsAndDriedFruits, calories: "675"),
                          NutsAndDriedFruits(name: "Pine nuts", type: .nutsAndDriedFruits, calories: "675"),
                          NutsAndDriedFruits(name: "Pistachios", type: .nutsAndDriedFruits, calories: "560"),
                          NutsAndDriedFruits(name: "Prunes", type: .nutsAndDriedFruits, calories: "240"),
                          NutsAndDriedFruits(name: "Pumpkin seeds", type: .nutsAndDriedFruits, calories: "546"),
                          NutsAndDriedFruits(name: "Raisins", type: .nutsAndDriedFruits, calories: "299"),
                          NutsAndDriedFruits(name: "Roasted cashew", type: .nutsAndDriedFruits, calories: "553"),
                          NutsAndDriedFruits(name: "Roasted chestnut", type: .nutsAndDriedFruits, calories: "196"),
                          NutsAndDriedFruits(name: "Roasted peanuts", type: .nutsAndDriedFruits, calories: "628"),
                          NutsAndDriedFruits(name: "Seychelles coco de mer nut", type: .nutsAndDriedFruits, calories: "600"),
                          NutsAndDriedFruits(name: "Stone-pine nuts", type: .nutsAndDriedFruits, calories: "674"),
                          NutsAndDriedFruits(name: "Sunflower seeds", type: .nutsAndDriedFruits, calories: "584"),
                          NutsAndDriedFruits(name: "Sweet almonds", type: .nutsAndDriedFruits, calories: "595"),
                          NutsAndDriedFruits(name: "The nut was drunk", type: .nutsAndDriedFruits, calories: "625"),
                          NutsAndDriedFruits(name: "The softest chestnut (Chinese)", type: .nutsAndDriedFruits, calories: "170"),
                          NutsAndDriedFruits(name: "Uryuk", type: .nutsAndDriedFruits, calories: "152"),
                          NutsAndDriedFruits(name: "Walnut opex", type: .nutsAndDriedFruits, calories: "654"),
                          NutsAndDriedFruits(name: "Watermelon seeds", type: .nutsAndDriedFruits, calories: "436")]

