//
//  NutsAndDriedFruitsData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 16.10.2023.
//

import Foundation

let nutsAndDriedFruits = [NutsAndDriedFruits(name: "Apricot pits", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Beech nut", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Bitter almonds", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Brazilian opex", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Candied apples", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Candied fruits", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Candied ginger", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Candied melon", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Candied orange", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Candied papaya", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Candied pears", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Candied pineapple", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Candied watermelon crusts", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Canned chestnuts", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Cashews", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Chilim nut", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Chufa (Ground almonds)", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Coconut opex", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Cucui nuts", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Dates", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Dried Fruits", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Dried Hawthorn", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Dried apples", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Dried apricots", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Dried bananas", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Dried barberry", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Dried cherry", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Dried cranberries", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Dried date", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Dried figs", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Dried kumquat", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Dried mango", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Dried melon", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Dried peanuts", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Dried pears", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Dried rosehip", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Flax seeds", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Fresh chestnut", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Fruit chips", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Fruits of the shea tree (karite)", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Hazelnut", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Hazelnuts", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Jerked cranberries", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Kishmish raisins", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Kola nut", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Macadamia nut", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Nuts", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Nuts acorns", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Peanuts", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Pecan", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Pine nut cake", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Pine nuts", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Pistachios", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Prunes", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Pumpkin seeds", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Raisins", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Roasted cashew", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Roasted chestnut", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Roasted peanuts", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Seychelles coco de mer nut", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Stone-pine nuts", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Sunflower seeds", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Sweet almonds", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "The nut was drunk", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "The softest chestnut (Chinese)", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Uryuk", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Walnut opex", type: .nutsAndDriedFruits),
                  NutsAndDriedFruits(name: "Watermelon seeds", type: .nutsAndDriedFruits)
]
