//
//  RawMaterialsAndAdditivesData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 17.10.2023.
//

import Foundation

let rawMaterialsAndAdditives = [FoodRealm(name: "A sugar substitute for erythritol", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Acetic essence", type: .rawMaterialsAndAdditives, calories: "890"),
                                FoodRealm(name: "Adjika", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Agar-agar", type: .rawMaterialsAndAdditives, calories: "10"),
                                FoodRealm(name: "Aioli sauce", type: .rawMaterialsAndAdditives, calories: "700"),
                                FoodRealm(name: "Almond Extract", type: .rawMaterialsAndAdditives, calories: "310"),
                                FoodRealm(name: "Almond oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Almond petals", type: .rawMaterialsAndAdditives, calories: "440"),
                                FoodRealm(name: "Amaranth oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Americano Coffee", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Andiroba Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Angelica Root", type: .rawMaterialsAndAdditives, calories: "260"),
                                FoodRealm(name: "Anise Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Annato", type: .rawMaterialsAndAdditives, calories: "360"),
                                FoodRealm(name: "Anti-lipid Tianshi Tea", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Antipasto", type: .rawMaterialsAndAdditives, calories: "230"),
                                FoodRealm(name: "Apple cider vinegar", type: .rawMaterialsAndAdditives, calories: "22"),
                                FoodRealm(name: "Apple sauce", type: .rawMaterialsAndAdditives, calories: "218"),
                                FoodRealm(name: "Apple syrup yellow", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Apricot Kernel Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Apricot kernels", type: .rawMaterialsAndAdditives, calories: "580"),
                                FoodRealm(name: "Arabica Coffee", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Argan oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Arrowroot starch flour", type: .rawMaterialsAndAdditives, calories: "330"),
                                FoodRealm(name: "Avocado Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Babassu oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Backmes", type: .rawMaterialsAndAdditives, calories: "350"),
                                FoodRealm(name: "Baking mix", type: .rawMaterialsAndAdditives, calories: "360"),
                                FoodRealm(name: "Baking powder of the dough", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Baking soda", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Balsamic cream", type: .rawMaterialsAndAdditives, calories: "330"),
                                FoodRealm(name: "Balsamic vinegar", type: .rawMaterialsAndAdditives, calories: "290"),
                                FoodRealm(name: "Bamboo tea", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Banana leaves", type: .rawMaterialsAndAdditives, calories: "90"),
                                FoodRealm(name: "Banana syrup", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Barbecue sauce", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Barley malt", type: .rawMaterialsAndAdditives, calories: "325"),
                                FoodRealm(name: "Bearnaise sauce", type: .rawMaterialsAndAdditives, calories: "390"),
                                FoodRealm(name: "Beech oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Beef broth", type: .rawMaterialsAndAdditives, calories: "20"),
                                FoodRealm(name: "Beet sugar", type: .rawMaterialsAndAdditives, calories: "400"),
                                FoodRealm(name: "Bergamot Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Black Cumin oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Black Pepper oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Black flavored tea", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Black salt", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Black tea", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Blue Tea", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Bolognese sauce", type: .rawMaterialsAndAdditives, calories: "130"),
                                FoodRealm(name: "Bone fat", type: .rawMaterialsAndAdditives, calories: "900"),
                                FoodRealm(name: "Borage oil (borago)", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Botvinya", type: .rawMaterialsAndAdditives, calories: "350"),
                                FoodRealm(name: "Brazil Nut Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Breadcrumbs", type: .rawMaterialsAndAdditives, calories: "380"),
                                FoodRealm(name: "Brewer's yeast", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Broccoli oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Broth", type: .rawMaterialsAndAdditives, calories: "20"),
                                FoodRealm(name: "Broth cube", type: .rawMaterialsAndAdditives, calories: "5"),
                                FoodRealm(name: "Brown cane sugar", type: .rawMaterialsAndAdditives, calories: "380"),
                                FoodRealm(name: "Brown espagnol sauce", type: .rawMaterialsAndAdditives, calories: "140"),
                                FoodRealm(name: "Bulgarian ketchup", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Burdock oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Buriti oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Burnt sugar (Burnt)", type: .rawMaterialsAndAdditives, calories: "380"),
                                FoodRealm(name: "Caesar Sauce", type: .rawMaterialsAndAdditives, calories: "420"),
                                FoodRealm(name: "Calamus Root", type: .rawMaterialsAndAdditives, calories: "340"),
                                FoodRealm(name: "Camelina oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Camphor", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Canned borscht", type: .rawMaterialsAndAdditives, calories: "50"),
                                FoodRealm(name: "Canned grape leaves", type: .rawMaterialsAndAdditives, calories: "25"),
                                FoodRealm(name: "Canned porridge", type: .rawMaterialsAndAdditives, calories: "100"),
                                FoodRealm(name: "Canned soup", type: .rawMaterialsAndAdditives, calories: "30"),
                                FoodRealm(name: "Canned tomato soup", type: .rawMaterialsAndAdditives, calories: "40"),
                                FoodRealm(name: "Canola Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Caramel syrup", type: .rawMaterialsAndAdditives, calories: "320"),
                                FoodRealm(name: "Caramel topping", type: .rawMaterialsAndAdditives, calories: "380"),
                                FoodRealm(name: "Carrot Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Cedar oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Cedar sap", type: .rawMaterialsAndAdditives, calories: "260"),
                                FoodRealm(name: "Celery salt", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Chamomile oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Chamomile tea", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Cheese flavoring", type: .rawMaterialsAndAdditives, calories: "350"),
                                FoodRealm(name: "Cheese sauce", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Cheesecake flavor", type: .rawMaterialsAndAdditives, calories: "330"),
                                FoodRealm(name: "Chereva", type: .rawMaterialsAndAdditives, calories: "20"),
                                FoodRealm(name: "Cherry syrup", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Chestnut honey", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Chia seeds", type: .rawMaterialsAndAdditives, calories: "486"),
                                FoodRealm(name: "Chia seeds (Spanish sage)", type: .rawMaterialsAndAdditives, calories: "486"),
                                FoodRealm(name: "Chicken cubes", type: .rawMaterialsAndAdditives, calories: "5"),
                                FoodRealm(name: "Chicken fat", type: .rawMaterialsAndAdditives, calories: "900"),
                                FoodRealm(name: "Chili ketchup", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Chili sauce", type: .rawMaterialsAndAdditives, calories: "130"),
                                FoodRealm(name: "Chimichurri sauce", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Chocolate butter", type: .rawMaterialsAndAdditives, calories: "580"),
                                FoodRealm(name: "Chocolate for baking", type: .rawMaterialsAndAdditives, calories: "550"),
                                FoodRealm(name: "Chocolate glaze", type: .rawMaterialsAndAdditives, calories: "380"),
                                FoodRealm(name: "Chocolate sauce", type: .rawMaterialsAndAdditives, calories: "460"),
                                FoodRealm(name: "Chocolate syrup", type: .rawMaterialsAndAdditives, calories: "320"),
                                FoodRealm(name: "Chocolate topping", type: .rawMaterialsAndAdditives, calories: "500"),
                                FoodRealm(name: "Cinnamon Essential Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Cinnamon Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Citric acid", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Clove Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Cocoa beans", type: .rawMaterialsAndAdditives, calories: "400"),
                                FoodRealm(name: "Cocoa butter", type: .rawMaterialsAndAdditives, calories: "898"),
                                FoodRealm(name: "Cocoa powder", type: .rawMaterialsAndAdditives, calories: "230"),
                                FoodRealm(name: "Coconut chips", type: .rawMaterialsAndAdditives, calories: "560"),
                                FoodRealm(name: "Coconut manna", type: .rawMaterialsAndAdditives, calories: "330"),
                                FoodRealm(name: "Coconut milk", type: .rawMaterialsAndAdditives, calories: "230"),
                                FoodRealm(name: "Coconut oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Cod liver oil", type: .rawMaterialsAndAdditives, calories: "902"),
                                FoodRealm(name: "Coffee", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Coffee substitute", type: .rawMaterialsAndAdditives, calories: "2"),
                                FoodRealm(name: "Coffee syrup", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Cognac essence", type: .rawMaterialsAndAdditives, calories: "290"),
                                FoodRealm(name: "Confectionery decorations", type: .rawMaterialsAndAdditives, calories: "380"),
                                FoodRealm(name: "Confectionery fat", type: .rawMaterialsAndAdditives, calories: "900"),
                                FoodRealm(name: "Confectionery fudge", type: .rawMaterialsAndAdditives, calories: "480"),
                                FoodRealm(name: "Confectionery glaze", type: .rawMaterialsAndAdditives, calories: "400"),
                                FoodRealm(name: "Confectionery mixes", type: .rawMaterialsAndAdditives, calories: "360"),
                                FoodRealm(name: "Consomme broth", type: .rawMaterialsAndAdditives, calories: "20"),
                                FoodRealm(name: "Cooking fats", type: .rawMaterialsAndAdditives, calories: "900"),
                                FoodRealm(name: "Coriander Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Corn molasses", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Corn oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Corn starch", type: .rawMaterialsAndAdditives, calories: "360"),
                                FoodRealm(name: "Corn syrup", type: .rawMaterialsAndAdditives, calories: "280"),
                                FoodRealm(name: "Cotton oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Cranberry Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Cranberry sauce", type: .rawMaterialsAndAdditives, calories: "210"),
                                FoodRealm(name: "Cranberry seeds", type: .rawMaterialsAndAdditives, calories: "308"),
                                FoodRealm(name: "Cranberry syrup", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Cream margarine", type: .rawMaterialsAndAdditives, calories: "717"),
                                FoodRealm(name: "Cream sauce", type: .rawMaterialsAndAdditives, calories: "200"),
                                FoodRealm(name: "Creamy garlic sauce", type: .rawMaterialsAndAdditives, calories: "420"),
                                FoodRealm(name: "Crushed ice", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Cucumber pickle", type: .rawMaterialsAndAdditives, calories: "15"),
                                FoodRealm(name: "Culinary semi-finished products", type: .rawMaterialsAndAdditives, calories: "130"),
                                FoodRealm(name: "Cupuacu oil (theobroma)", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Currant leaf tea", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Curry Paste", type: .rawMaterialsAndAdditives, calories: "270"),
                                FoodRealm(name: "Cypress Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Da Hong Pao Tea", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Dashi broth (dashi)", type: .rawMaterialsAndAdditives, calories: "5"),
                                FoodRealm(name: "Dead Sea Salt", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Demiglas sauce", type: .rawMaterialsAndAdditives, calories: "80"),
                                FoodRealm(name: "Dietary salt", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Dijon mustard sauce", type: .rawMaterialsAndAdditives, calories: "350"),
                                FoodRealm(name: "Dried carrots", type: .rawMaterialsAndAdditives, calories: "240"),
                                FoodRealm(name: "Dried green peas", type: .rawMaterialsAndAdditives, calories: "330"),
                                FoodRealm(name: "Dry bread kvass", type: .rawMaterialsAndAdditives, calories: "260"),
                                FoodRealm(name: "Dry cake mix", type: .rawMaterialsAndAdditives, calories: "360"),
                                FoodRealm(name: "Dry egg white", type: .rawMaterialsAndAdditives, calories: "350"),
                                FoodRealm(name: "Dry ice", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Dry pudding", type: .rawMaterialsAndAdditives, calories: "360"),
                                FoodRealm(name: "Dry starter culture", type: .rawMaterialsAndAdditives, calories: "290"),
                                FoodRealm(name: "Dry vanilla pudding", type: .rawMaterialsAndAdditives, calories: "360"),
                                FoodRealm(name: "Dry yeast", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Duck fat", type: .rawMaterialsAndAdditives, calories: "900"),
                                FoodRealm(name: "Ebara Sauce", type: .rawMaterialsAndAdditives, calories: "140"),
                                FoodRealm(name: "Edible Himalayan pink salt", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Edible animal fats", type: .rawMaterialsAndAdditives, calories: "900"),
                                FoodRealm(name: "Egg broth", type: .rawMaterialsAndAdditives, calories: "50"),
                                FoodRealm(name: "Egg melange", type: .rawMaterialsAndAdditives, calories: "157"),
                                FoodRealm(name: "Egg powder (dry melange)", type: .rawMaterialsAndAdditives, calories: "350"),
                                FoodRealm(name: "Eggplant caviar", type: .rawMaterialsAndAdditives, calories: "80"),
                                FoodRealm(name: "Essence of rum", type: .rawMaterialsAndAdditives, calories: "290"),
                                FoodRealm(name: "Eucalyptus oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Fat tail fat", type: .rawMaterialsAndAdditives, calories: "900"),
                                FoodRealm(name: "Fennel Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Fir Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Fish broth", type: .rawMaterialsAndAdditives, calories: "10"),
                                FoodRealm(name: "Fish sauce", type: .rawMaterialsAndAdditives, calories: "60"),
                                FoodRealm(name: "Flavor Condensed milk", type: .rawMaterialsAndAdditives, calories: "335"),
                                FoodRealm(name: "Flavor Duchess", type: .rawMaterialsAndAdditives, calories: "350"),
                                FoodRealm(name: "Flavored vinegar", type: .rawMaterialsAndAdditives, calories: "15"),
                                FoodRealm(name: "Flower Tea", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Food coloring varnish golden Kandurin", type: .rawMaterialsAndAdditives, calories: "380"),
                                FoodRealm(name: "Food coloring varnish silver Kandurin", type: .rawMaterialsAndAdditives, calories: "380"),
                                FoodRealm(name: "Food ice", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Food iodized salt", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Food salt", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Frangipani (plumeria) oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Frozen pancakes", type: .rawMaterialsAndAdditives, calories: "250"),
                                FoodRealm(name: "Frozen vegetables", type: .rawMaterialsAndAdditives, calories: "30"),
                                FoodRealm(name: "Fructose", type: .rawMaterialsAndAdditives, calories: "360"),
                                FoodRealm(name: "Fruit essence", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Garlic leaves", type: .rawMaterialsAndAdditives, calories: "28"),
                                FoodRealm(name: "Garlic oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Garlic salt", type: .rawMaterialsAndAdditives, calories: "10"),
                                FoodRealm(name: "Garlic sauce", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Garnet sauce Narsharab", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Garum sauce", type: .rawMaterialsAndAdditives, calories: "100"),
                                FoodRealm(name: "Gelatin", type: .rawMaterialsAndAdditives, calories: "350"),
                                FoodRealm(name: "Gelling mixture", type: .rawMaterialsAndAdditives, calories: "380"),
                                FoodRealm(name: "Geranium Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Ghee clarified butter", type: .rawMaterialsAndAdditives, calories: "898"),
                                FoodRealm(name: "Gin flavor", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Ginger Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Ginger tea", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Ginkgo Biloba seeds", type: .rawMaterialsAndAdditives, calories: "392"),
                                FoodRealm(name: "Ginseng Root", type: .rawMaterialsAndAdditives, calories: "370"),
                                FoodRealm(name: "Goose fat", type: .rawMaterialsAndAdditives, calories: "900"),
                                FoodRealm(name: "Granola bars", type: .rawMaterialsAndAdditives, calories: "400"),
                                FoodRealm(name: "Granulated sugar", type: .rawMaterialsAndAdditives, calories: "400"),
                                FoodRealm(name: "Grape Seed Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Grape Seed powder", type: .rawMaterialsAndAdditives, calories: "332"),
                                FoodRealm(name: "Grape seeds", type: .rawMaterialsAndAdditives, calories: "308"),
                                FoodRealm(name: "Grapefruit Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Gravies", type: .rawMaterialsAndAdditives, calories: "100"),
                                FoodRealm(name: "Green Coffee oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Green coffee", type: .rawMaterialsAndAdditives, calories: "2"),
                                FoodRealm(name: "Green sauce", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Green tea", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Green tea with jasmine", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Green tea with rosehip", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Grenadine Syrup", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Guacamole sauce", type: .rawMaterialsAndAdditives, calories: "230"),
                                FoodRealm(name: "Gyokuro green tea", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Harissa", type: .rawMaterialsAndAdditives, calories: "270"),
                                FoodRealm(name: "Hashtak", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Hawthorn tea", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Hazelnut oil (hazelnuts)", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Hemp oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Hoisin sauce", type: .rawMaterialsAndAdditives, calories: "270"),
                                FoodRealm(name: "Hollandaise sauce", type: .rawMaterialsAndAdditives, calories: "405"),
                                FoodRealm(name: "Honeybush tea", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Hop Cones oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Hop cones", type: .rawMaterialsAndAdditives, calories: "33"),
                                FoodRealm(name: "Hops", type: .rawMaterialsAndAdditives, calories: "33"),
                                FoodRealm(name: "Hot tomato sauce", type: .rawMaterialsAndAdditives, calories: "80"),
                                FoodRealm(name: "Hummus Paste", type: .rawMaterialsAndAdditives, calories: "164"),
                                FoodRealm(name: "Ice cubes", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Instant chicory", type: .rawMaterialsAndAdditives, calories: "260"),
                                FoodRealm(name: "Instant coffee", type: .rawMaterialsAndAdditives, calories: "5"),
                                FoodRealm(name: "Instant dry soup", type: .rawMaterialsAndAdditives, calories: "360"),
                                FoodRealm(name: "Instant hot chocolate", type: .rawMaterialsAndAdditives, calories: "500"),
                                FoodRealm(name: "Instant mashed potatoes", type: .rawMaterialsAndAdditives, calories: "80"),
                                FoodRealm(name: "Iris Root", type: .rawMaterialsAndAdditives, calories: "315"),
                                FoodRealm(name: "Isolate", type: .rawMaterialsAndAdditives, calories: "350"),
                                FoodRealm(name: "Italian tomato sauce", type: .rawMaterialsAndAdditives, calories: "80"),
                                FoodRealm(name: "Ivan-tea (cypress) narrow-leaved", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Ivar", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Japanese mayonnaise", type: .rawMaterialsAndAdditives, calories: "700"),
                                FoodRealm(name: "Jasmine Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Jelly concentrate", type: .rawMaterialsAndAdditives, calories: "320"),
                                FoodRealm(name: "Jerusalem Artichoke syrup", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Juniper Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Karkade tea", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Kebab ketchup", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Ketchup", type: .rawMaterialsAndAdditives, calories: "100"),
                                FoodRealm(name: "Kidney tea", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Kikkoman sauce", type: .rawMaterialsAndAdditives, calories: "60"),
                                FoodRealm(name: "Kimchi sauce", type: .rawMaterialsAndAdditives, calories: "70"),
                                FoodRealm(name: "Kopor tea", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Krasnodar sauce", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Kudin tea", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Laurel Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Lavender Extract", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Lavender Flowers", type: .rawMaterialsAndAdditives, calories: "260"),
                                FoodRealm(name: "Lavender Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Leaf gelatin", type: .rawMaterialsAndAdditives, calories: "350"),
                                FoodRealm(name: "Leaves of orthosiphon staminate", type: .rawMaterialsAndAdditives, calories: "18"),
                                FoodRealm(name: "Lecho", type: .rawMaterialsAndAdditives, calories: "35"),
                                FoodRealm(name: "Lecithin", type: .rawMaterialsAndAdditives, calories: "744"),
                                FoodRealm(name: "Lemon Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Lemon sauce", type: .rawMaterialsAndAdditives, calories: "80"),
                                FoodRealm(name: "Lemon syrup", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Lemongrass oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Lime Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Linden oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Lingonberry sauce", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Lingonberry syrup", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Linseed oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Lotus Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Macadamia Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Malt", type: .rawMaterialsAndAdditives, calories: "325"),
                                FoodRealm(name: "Malt sugar (maltose)", type: .rawMaterialsAndAdditives, calories: "310"),
                                FoodRealm(name: "Malt vinegar", type: .rawMaterialsAndAdditives, calories: "42"),
                                FoodRealm(name: "Mandarin peel", type: .rawMaterialsAndAdditives, calories: "311"),
                                FoodRealm(name: "Margarine", type: .rawMaterialsAndAdditives, calories: "717"),
                                FoodRealm(name: "Marinade for barbecue", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Marinade for fish", type: .rawMaterialsAndAdditives, calories: "80"),
                                FoodRealm(name: "Marinade sauce for chicken", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Marinades", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Masala Tea", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Mate tea", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Matignon", type: .rawMaterialsAndAdditives, calories: "60"),
                                FoodRealm(name: "Mayonnaise", type: .rawMaterialsAndAdditives, calories: "700"),
                                FoodRealm(name: "Melissa Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Melon oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Melon seeds", type: .rawMaterialsAndAdditives, calories: "576"),
                                FoodRealm(name: "Melted beef fat", type: .rawMaterialsAndAdditives, calories: "900"),
                                FoodRealm(name: "Milk Thistle oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Milk margarine", type: .rawMaterialsAndAdditives, calories: "717"),
                                FoodRealm(name: "Milk sauce", type: .rawMaterialsAndAdditives, calories: "100"),
                                FoodRealm(name: "Mink oil (mink fat)", type: .rawMaterialsAndAdditives, calories: "900"),
                                FoodRealm(name: "Mint Essence", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Mint Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Mint syrup", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Mint tea", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Mirin sauce", type: .rawMaterialsAndAdditives, calories: "60"),
                                FoodRealm(name: "Miso Paste", type: .rawMaterialsAndAdditives, calories: "207"),
                                FoodRealm(name: "Mocha coffee (mocha)", type: .rawMaterialsAndAdditives, calories: "5"),
                                FoodRealm(name: "Modena balsamic vinegar", type: .rawMaterialsAndAdditives, calories: "68"),
                                FoodRealm(name: "Modified starch", type: .rawMaterialsAndAdditives, calories: "360"),
                                FoodRealm(name: "Molasses", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Molasses molasses", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Monarda Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Mulberry doshab", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Mulled wine seasoning", type: .rawMaterialsAndAdditives, calories: "30"),
                                FoodRealm(name: "Murumuru Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Mushroom broth", type: .rawMaterialsAndAdditives, calories: "5"),
                                FoodRealm(name: "Mushroom sauce", type: .rawMaterialsAndAdditives, calories: "50"),
                                FoodRealm(name: "Mustard", type: .rawMaterialsAndAdditives, calories: "208"),
                                FoodRealm(name: "Mustard grainy sauce", type: .rawMaterialsAndAdditives, calories: "208"),
                                FoodRealm(name: "Mustard oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Mutton fat", type: .rawMaterialsAndAdditives, calories: "900"),
                                FoodRealm(name: "Nardek (Watermelon honey)", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Natto", type: .rawMaterialsAndAdditives, calories: "207"),
                                FoodRealm(name: "Natural Food coloring black", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Natural Food coloring blue", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Natural Food coloring pink", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Natural Food coloring yellow", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Natural food coloring green", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Natural food coloring orange", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Natural food coloring red", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Natural ground coffee", type: .rawMaterialsAndAdditives, calories: "2"),
                                FoodRealm(name: "Natural honey", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Natural vinegar", type: .rawMaterialsAndAdditives, calories: "20"),
                                FoodRealm(name: "Neem Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Neroli oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Nut butter", type: .rawMaterialsAndAdditives, calories: "600"),
                                FoodRealm(name: "Nut sauce", type: .rawMaterialsAndAdditives, calories: "420"),
                                FoodRealm(name: "Nut syrup", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Nutmeg oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Oak bark", type: .rawMaterialsAndAdditives, calories: "374"),
                                FoodRealm(name: "Oatmeal oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Oleoresin", type: .rawMaterialsAndAdditives, calories: "840"),
                                FoodRealm(name: "Olive mayonnaise", type: .rawMaterialsAndAdditives, calories: "700"),
                                FoodRealm(name: "Olive oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Onion husk", type: .rawMaterialsAndAdditives, calories: "40"),
                                FoodRealm(name: "Onion jam", type: .rawMaterialsAndAdditives, calories: "258"),
                                FoodRealm(name: "Onion soubise sauce", type: .rawMaterialsAndAdditives, calories: "80"),
                                FoodRealm(name: "Oolong Tea", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Orange Essential Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Orange Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Orange sauce", type: .rawMaterialsAndAdditives, calories: "80"),
                                FoodRealm(name: "Orange syrup", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Orange water", type: .rawMaterialsAndAdditives, calories: "30"),
                                FoodRealm(name: "Orchid Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Oregano oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Organic olive oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Osmanthus flowers", type: .rawMaterialsAndAdditives, calories: "15"),
                                FoodRealm(name: "Ostrich fat", type: .rawMaterialsAndAdditives, calories: "900"),
                                FoodRealm(name: "Oyster sauce", type: .rawMaterialsAndAdditives, calories: "75"),
                                FoodRealm(name: "Pad Thai Sauce", type: .rawMaterialsAndAdditives, calories: "60"),
                                FoodRealm(name: "Palm oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Palm yagre sugar", type: .rawMaterialsAndAdditives, calories: "380"),
                                FoodRealm(name: "Palmarose oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Pancake flour", type: .rawMaterialsAndAdditives, calories: "360"),
                                FoodRealm(name: "Parsley oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Pasta tapenade", type: .rawMaterialsAndAdditives, calories: "630"),
                                FoodRealm(name: "Patchouli oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Pate", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Peach oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Peanut sauce", type: .rawMaterialsAndAdditives, calories: "480"),
                                FoodRealm(name: "Pectin", type: .rawMaterialsAndAdditives, calories: "250"),
                                FoodRealm(name: "Pesto sauce", type: .rawMaterialsAndAdditives, calories: "420"),
                                FoodRealm(name: "Petitgrain oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Pickled beetroot", type: .rawMaterialsAndAdditives, calories: "20"),
                                FoodRealm(name: "Pineapple syrup", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Pink Essence", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Pink Vinegar", type: .rawMaterialsAndAdditives, calories: "80"),
                                FoodRealm(name: "Pink tea", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Pistachio oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Pistachio paste", type: .rawMaterialsAndAdditives, calories: "576"),
                                FoodRealm(name: "Pizzaiola", type: .rawMaterialsAndAdditives, calories: "100"),
                                FoodRealm(name: "Plum oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Plum sauce", type: .rawMaterialsAndAdditives, calories: "258"),
                                FoodRealm(name: "Polish sauce", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Pomegranate sauce", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Pomegranate syrup", type: .rawMaterialsAndAdditives, calories: "320"),
                                FoodRealm(name: "Poppy seed oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Pork Marinade", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Pork broth", type: .rawMaterialsAndAdditives, calories: "20"),
                                FoodRealm(name: "Pork fat", type: .rawMaterialsAndAdditives, calories: "900"),
                                FoodRealm(name: "Pork gravy", type: .rawMaterialsAndAdditives, calories: "100"),
                                FoodRealm(name: "Pork liver gravy", type: .rawMaterialsAndAdditives, calories: "50"),
                                FoodRealm(name: "Pork seasoning", type: .rawMaterialsAndAdditives, calories: "5"),
                                FoodRealm(name: "Potato starch", type: .rawMaterialsAndAdditives, calories: "358"),
                                FoodRealm(name: "Powdered sugar", type: .rawMaterialsAndAdditives, calories: "380"),
                                FoodRealm(name: "Prefix", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Pressed yeast", type: .rawMaterialsAndAdditives, calories: "335"),
                                FoodRealm(name: "Protein Shake", type: .rawMaterialsAndAdditives, calories: "170"),
                                FoodRealm(name: "Protein-free berry pasta", type: .rawMaterialsAndAdditives, calories: "360"),
                                FoodRealm(name: "Protein-free fruit pasta", type: .rawMaterialsAndAdditives, calories: "360"),
                                FoodRealm(name: "Protein-free pasta", type: .rawMaterialsAndAdditives, calories: "360"),
                                FoodRealm(name: "Protein-free vegetable pasta", type: .rawMaterialsAndAdditives, calories: "360"),
                                FoodRealm(name: "Provencal Mayonnaise", type: .rawMaterialsAndAdditives, calories: "700"),
                                FoodRealm(name: "Pu-erh tea", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Pumpkin oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Pumpkin seed cake", type: .rawMaterialsAndAdditives, calories: "546"),
                                FoodRealm(name: "Quince syrup", type: .rawMaterialsAndAdditives, calories: "320"),
                                FoodRealm(name: "Rapeseed oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Rapeseed seeds", type: .rawMaterialsAndAdditives, calories: "568"),
                                FoodRealm(name: "Raspberry Extract", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Raspberry leaves", type: .rawMaterialsAndAdditives, calories: "26"),
                                FoodRealm(name: "Raspberry syrup", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Raw beef fat", type: .rawMaterialsAndAdditives, calories: "900"),
                                FoodRealm(name: "Raw sugar", type: .rawMaterialsAndAdditives, calories: "380"),
                                FoodRealm(name: "Red Wine vinegar", type: .rawMaterialsAndAdditives, calories: "20"),
                                FoodRealm(name: "Red tea", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Refined sugar", type: .rawMaterialsAndAdditives, calories: "400"),
                                FoodRealm(name: "Refined vegetable oil", type: .rawMaterialsAndAdditives, calories: "900"),
                                FoodRealm(name: "Related Tea", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Remoulade sauce", type: .rawMaterialsAndAdditives, calories: "420"),
                                FoodRealm(name: "Rice Bran oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Rice milk", type: .rawMaterialsAndAdditives, calories: "47"),
                                FoodRealm(name: "Rice vinegar", type: .rawMaterialsAndAdditives, calories: "42"),
                                FoodRealm(name: "Robusta Coffee", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Rose Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Rose water", type: .rawMaterialsAndAdditives, calories: "30"),
                                FoodRealm(name: "Rosehip Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Rosehip petals", type: .rawMaterialsAndAdditives, calories: "17"),
                                FoodRealm(name: "Rosemary oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Rye bread starter", type: .rawMaterialsAndAdditives, calories: "335"),
                                FoodRealm(name: "Rye malt", type: .rawMaterialsAndAdditives, calories: "325"),
                                FoodRealm(name: "Rye wort", type: .rawMaterialsAndAdditives, calories: "260"),
                                FoodRealm(name: "Safflower dye seeds", type: .rawMaterialsAndAdditives, calories: "525"),
                                FoodRealm(name: "Safflower oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Sage Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Sage tea", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Salad dressing", type: .rawMaterialsAndAdditives, calories: "420"),
                                FoodRealm(name: "Salmon fat", type: .rawMaterialsAndAdditives, calories: "902"),
                                FoodRealm(name: "Salsa sauce", type: .rawMaterialsAndAdditives, calories: "70"),
                                FoodRealm(name: "Salt substitute", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Sandalwood oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Sasankva oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Satsebeli sauce", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Sauce 1000 islands", type: .rawMaterialsAndAdditives, calories: "420"),
                                FoodRealm(name: "Sauce ru", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Sauces", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Sea Buckthorn oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Sea buckthorn syrup", type: .rawMaterialsAndAdditives, calories: "320"),
                                FoodRealm(name: "Sesame oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Sesame paste", type: .rawMaterialsAndAdditives, calories: "586"),
                                FoodRealm(name: "Sherry vinegar", type: .rawMaterialsAndAdditives, calories: "20"),
                                FoodRealm(name: "Shortening", type: .rawMaterialsAndAdditives, calories: "910"),
                                FoodRealm(name: "Siberian fiber", type: .rawMaterialsAndAdditives, calories: "10"),
                                FoodRealm(name: "Snacks", type: .rawMaterialsAndAdditives, calories: "380"),
                                FoodRealm(name: "Snake oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Soap grass root (saponaria)", type: .rawMaterialsAndAdditives, calories: "374"),
                                FoodRealm(name: "Sodium Glutamate", type: .rawMaterialsAndAdditives, calories: "4"),
                                FoodRealm(name: "Soup mix", type: .rawMaterialsAndAdditives, calories: "360"),
                                FoodRealm(name: "Sour cream sauce", type: .rawMaterialsAndAdditives, calories: "220"),
                                FoodRealm(name: "Soy asparagus", type: .rawMaterialsAndAdditives, calories: "86"),
                                FoodRealm(name: "Soy chips", type: .rawMaterialsAndAdditives, calories: "441"),
                                FoodRealm(name: "Soy goulash", type: .rawMaterialsAndAdditives, calories: "120"),
                                FoodRealm(name: "Soy isolate", type: .rawMaterialsAndAdditives, calories: "350"),
                                FoodRealm(name: "Soy marinade", type: .rawMaterialsAndAdditives, calories: "60"),
                                FoodRealm(name: "Soy meat", type: .rawMaterialsAndAdditives, calories: "170"),
                                FoodRealm(name: "Soy milk", type: .rawMaterialsAndAdditives, calories: "47"),
                                FoodRealm(name: "Soy paper", type: .rawMaterialsAndAdditives, calories: "330"),
                                FoodRealm(name: "Soy paste", type: .rawMaterialsAndAdditives, calories: "207"),
                                FoodRealm(name: "Soy pieces", type: .rawMaterialsAndAdditives, calories: "120"),
                                FoodRealm(name: "Soy sauce", type: .rawMaterialsAndAdditives, calories: "60"),
                                FoodRealm(name: "Soy steak", type: .rawMaterialsAndAdditives, calories: "140"),
                                FoodRealm(name: "Soybean oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Spicy sauce", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Sprinkling confectionery", type: .rawMaterialsAndAdditives, calories: "380"),
                                FoodRealm(name: "Squash caviar", type: .rawMaterialsAndAdditives, calories: "25"),
                                FoodRealm(name: "Stevia tea", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Strawberry syrup", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Substitute for dry cream", type: .rawMaterialsAndAdditives, calories: "350"),
                                FoodRealm(name: "Sugar sorghum", type: .rawMaterialsAndAdditives, calories: "350"),
                                FoodRealm(name: "Sugar substitute", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Sugar substitute for fructose", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Sugar substitute for stevia", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Sugar substitute on sorbitol", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Sugar syrup", type: .rawMaterialsAndAdditives, calories: "320"),
                                FoodRealm(name: "Sunflower oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Sweet and sour sauce", type: .rawMaterialsAndAdditives, calories: "150"),
                                FoodRealm(name: "Sweet mustard", type: .rawMaterialsAndAdditives, calories: "208"),
                                FoodRealm(name: "Synthetic vinegar", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Syrup", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Tabasco sauce", type: .rawMaterialsAndAdditives, calories: "144"),
                                FoodRealm(name: "Tabasco sauce green", type: .rawMaterialsAndAdditives, calories: "144"),
                                FoodRealm(name: "Tabasco sauce red", type: .rawMaterialsAndAdditives, calories: "144"),
                                FoodRealm(name: "Table margarine", type: .rawMaterialsAndAdditives, calories: "717"),
                                FoodRealm(name: "Table vinegar 5%", type: .rawMaterialsAndAdditives, calories: "5"),
                                FoodRealm(name: "Taco sauce", type: .rawMaterialsAndAdditives, calories: "120"),
                                FoodRealm(name: "Tamanu oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Tangerine Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Tartar sauce", type: .rawMaterialsAndAdditives, calories: "420"),
                                FoodRealm(name: "Tea", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Tea Seeds", type: .rawMaterialsAndAdditives, calories: "332"),
                                FoodRealm(name: "Tea bagged", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Tea oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Tea rooibos (rooibos)", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "Tea with cardamom", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Tea with osmanthus", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Tea with rosehip", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Tea with rosemary", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Teriyaki sauce", type: .rawMaterialsAndAdditives, calories: "50"),
                                FoodRealm(name: "Terrine", type: .rawMaterialsAndAdditives, calories: "250"),
                                FoodRealm(name: "The root of the elecampane", type: .rawMaterialsAndAdditives, calories: "315"),
                                FoodRealm(name: "Thickener for cream", type: .rawMaterialsAndAdditives, calories: "200"),
                                FoodRealm(name: "Thyme Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Tile tea", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Tkemali sauce", type: .rawMaterialsAndAdditives, calories: "60"),
                                FoodRealm(name: "Tomato ketchup", type: .rawMaterialsAndAdditives, calories: "100"),
                                FoodRealm(name: "Tomato oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Tomato paste", type: .rawMaterialsAndAdditives, calories: "80"),
                                FoodRealm(name: "Tomato powder", type: .rawMaterialsAndAdditives, calories: "88"),
                                FoodRealm(name: "Tomato sauce", type: .rawMaterialsAndAdditives, calories: "80"),
                                FoodRealm(name: "Tonka beans", type: .rawMaterialsAndAdditives, calories: "293"),
                                FoodRealm(name: "Topping", type: .rawMaterialsAndAdditives, calories: "380"),
                                FoodRealm(name: "Turkey fat", type: .rawMaterialsAndAdditives, calories: "900"),
                                FoodRealm(name: "Valerian Root", type: .rawMaterialsAndAdditives, calories: "222"),
                                FoodRealm(name: "Vanilla Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Vanilla essence", type: .rawMaterialsAndAdditives, calories: "330"),
                                FoodRealm(name: "Vanilla paste", type: .rawMaterialsAndAdditives, calories: "320"),
                                FoodRealm(name: "Vanilla sauce", type: .rawMaterialsAndAdditives, calories: "200"),
                                FoodRealm(name: "Vanillin", type: .rawMaterialsAndAdditives, calories: "308"),
                                FoodRealm(name: "Vegetable broth", type: .rawMaterialsAndAdditives, calories: "8"),
                                FoodRealm(name: "Vegetable caviar", type: .rawMaterialsAndAdditives, calories: "25"),
                                FoodRealm(name: "Vegetable fat", type: .rawMaterialsAndAdditives, calories: "900"),
                                FoodRealm(name: "Vegetable fiber", type: .rawMaterialsAndAdditives, calories: "2"),
                                FoodRealm(name: "Vegetable marinade", type: .rawMaterialsAndAdditives, calories: "50"),
                                FoodRealm(name: "Vegetable oil", type: .rawMaterialsAndAdditives, calories: "900"),
                                FoodRealm(name: "Vegetable-fat spread", type: .rawMaterialsAndAdditives, calories: "717"),
                                FoodRealm(name: "Vegetarian sausage", type: .rawMaterialsAndAdditives, calories: "250"),
                                FoodRealm(name: "Velute sauce", type: .rawMaterialsAndAdditives, calories: "80"),
                                FoodRealm(name: "Verbena Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Vetiver Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Vincotto berry sauce", type: .rawMaterialsAndAdditives, calories: "260"),
                                FoodRealm(name: "Vinegar", type: .rawMaterialsAndAdditives, calories: "20"),
                                FoodRealm(name: "Vinegar 3%", type: .rawMaterialsAndAdditives, calories: "3"),
                                FoodRealm(name: "Vinegar 9%", type: .rawMaterialsAndAdditives, calories: "9"),
                                FoodRealm(name: "Walnut oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Wasabi", type: .rawMaterialsAndAdditives, calories: "109"),
                                FoodRealm(name: "Watermelon Seed Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Watermelon syrup", type: .rawMaterialsAndAdditives, calories: "300"),
                                FoodRealm(name: "Wheat Germ Oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Wheat fiber (kelp)", type: .rawMaterialsAndAdditives, calories: "10"),
                                FoodRealm(name: "Wheat gluten (gluten)", type: .rawMaterialsAndAdditives, calories: "356"),
                                FoodRealm(name: "Wheat malt", type: .rawMaterialsAndAdditives, calories: "325"),
                                FoodRealm(name: "Whipped cream", type: .rawMaterialsAndAdditives, calories: "345"),
                                FoodRealm(name: "White Bechamel sauce", type: .rawMaterialsAndAdditives, calories: "80"),
                                FoodRealm(name: "White tea", type: .rawMaterialsAndAdditives, calories: "0"),
                                FoodRealm(name: "White wine vinegar", type: .rawMaterialsAndAdditives, calories: "20"),
                                FoodRealm(name: "Wine stone", type: .rawMaterialsAndAdditives, calories: "260"),
                                FoodRealm(name: "Wine vinegar", type: .rawMaterialsAndAdditives, calories: "20"),
                                FoodRealm(name: "Worcester sauce", type: .rawMaterialsAndAdditives, calories: "60"),
                                FoodRealm(name: "Worcestershire sauce", type: .rawMaterialsAndAdditives, calories: "60"),
                                FoodRealm(name: "Wormwood oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Yellow tea", type: .rawMaterialsAndAdditives, calories: "1"),
                                FoodRealm(name: "Ylang-ylang oil", type: .rawMaterialsAndAdditives, calories: "884"),
                                FoodRealm(name: "Zajiki sauce", type: .rawMaterialsAndAdditives, calories: "60")]

