//
//  SoftDrinksData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 17.10.2023.
//

import Foundation

let softDrinks = [SoftDrinks(name: "7UP", type: .softDrinks, calories: "42"),
                  SoftDrinks(name: "Agave syrup", type: .softDrinks, calories: "310"),
                  SoftDrinks(name: "Aloe juice", type: .softDrinks, calories: "16"),
                  SoftDrinks(name: "Apple compote", type: .softDrinks, calories: "48"),
                  SoftDrinks(name: "Apple juice", type: .softDrinks, calories: "46"),
                  SoftDrinks(name: "Apple nectar", type: .softDrinks, calories: "50"),
                  SoftDrinks(name: "Apple sorbet", type: .softDrinks, calories: "60"),
                  SoftDrinks(name: "Apple syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Apricot compote", type: .softDrinks, calories: "48"),
                  SoftDrinks(name: "Apricot juice", type: .softDrinks, calories: "50"),
                  SoftDrinks(name: "Apricot syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Assam Tea", type: .softDrinks, calories: "1"),
                  SoftDrinks(name: "Banana juice", type: .softDrinks, calories: "60"),
                  SoftDrinks(name: "Banana syrup green", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Beet juice", type: .softDrinks, calories: "43"),
                  SoftDrinks(name: "Berry juice", type: .softDrinks, calories: "60"),
                  SoftDrinks(name: "Birch sap", type: .softDrinks, calories: "31"),
                  SoftDrinks(name: "Bitter lemon", type: .softDrinks, calories: "42"),
                  SoftDrinks(name: "Black currant compote", type: .softDrinks, calories: "48"),
                  SoftDrinks(name: "Blackberry juice", type: .softDrinks, calories: "42"),
                  SoftDrinks(name: "Blackberry syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Blackcurrant juice", type: .softDrinks, calories: "43"),
                  SoftDrinks(name: "Blackcurrant syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Blue Curacao Syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Blueberry juice", type: .softDrinks, calories: "57"),
                  SoftDrinks(name: "Blueberry syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "BonAqua Water", type: .softDrinks, calories: "0"),
                  SoftDrinks(name: "Borjomi Mineral water (Borjomi)", type: .softDrinks, calories: "0"),
                  SoftDrinks(name: "Bread kvass", type: .softDrinks, calories: "17"),
                  SoftDrinks(name: "Bubble gum Syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Cabbage juice", type: .softDrinks, calories: "16"),
                  SoftDrinks(name: "Cappuccino Coffee", type: .softDrinks, calories: "125"),
                  SoftDrinks(name: "Carbonated water", type: .softDrinks, calories: "0"),
                  SoftDrinks(name: "Carrot juice", type: .softDrinks, calories: "41"),
                  SoftDrinks(name: "Celery juice", type: .softDrinks, calories: "16"),
                  SoftDrinks(name: "Chamomile tea bags", type: .softDrinks, calories: "1"),
                  SoftDrinks(name: "Cherry compote", type: .softDrinks, calories: "48"),
                  SoftDrinks(name: "Cherry juice", type: .softDrinks, calories: "50"),
                  SoftDrinks(name: "Chocolate drink", type: .softDrinks, calories: "115"),
                  SoftDrinks(name: "Cinnamon syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Coca-Cola", type: .softDrinks, calories: "42"),
                  SoftDrinks(name: "Cocktails", type: .softDrinks, calories: "150"),
                  SoftDrinks(name: "Coconut syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Coconut water", type: .softDrinks, calories: "19"),
                  SoftDrinks(name: "Coffee frappe", type: .softDrinks, calories: "100"),
                  SoftDrinks(name: "Coffee glasse", type: .softDrinks, calories: "42"),
                  SoftDrinks(name: "Coffee with milk", type: .softDrinks, calories: "42"),
                  SoftDrinks(name: "Cold peach tea", type: .softDrinks, calories: "42"),
                  SoftDrinks(name: "Compote", type: .softDrinks, calories: "48"),
                  SoftDrinks(name: "Cranberry fruit-drink", type: .softDrinks, calories: "50"),
                  SoftDrinks(name: "Cranberry juice", type: .softDrinks, calories: "42"),
                  SoftDrinks(name: "Creme brulee syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Cucumber juice", type: .softDrinks, calories: "16"),
                  SoftDrinks(name: "Cucumber syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Decaf coffee", type: .softDrinks, calories: "1"),
                  SoftDrinks(name: "Dian Hong Tea", type: .softDrinks, calories: "0"),
                  SoftDrinks(name: "Dried fruit compote", type: .softDrinks, calories: "48"),
                  SoftDrinks(name: "Drink Baikal", type: .softDrinks, calories: "20"),
                  SoftDrinks(name: "Drink Burn", type: .softDrinks, calories: "5"),
                  SoftDrinks(name: "Drink citro", type: .softDrinks, calories: "42"),
                  SoftDrinks(name: "Earl Grey Tea", type: .softDrinks, calories: "1"),
                  SoftDrinks(name: "Elderberry juice", type: .softDrinks, calories: "58"),
                  SoftDrinks(name: "Elderberry syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Energy drinks", type: .softDrinks, calories: "10"),
                  SoftDrinks(name: "Espresso coffee", type: .softDrinks, calories: "42"),
                  SoftDrinks(name: "Essentuki Mineral water", type: .softDrinks, calories: "0"),
                  SoftDrinks(name: "Fanta", type: .softDrinks, calories: "42"),
                  SoftDrinks(name: "Fig syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Flavored tea", type: .softDrinks, calories: "1"),
                  SoftDrinks(name: "Freshly squeezed juices", type: .softDrinks, calories: "30"),
                  SoftDrinks(name: "Fruit Smoothie", type: .softDrinks, calories: "110"),
                  SoftDrinks(name: "Fruit and berry juices", type: .softDrinks, calories: "50"),
                  SoftDrinks(name: "Fruit nectars", type: .softDrinks, calories: "50"),
                  SoftDrinks(name: "Fruit water", type: .softDrinks, calories: "30"),
                  SoftDrinks(name: "Ginger syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Gingerbread syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Gooseberry juice", type: .softDrinks, calories: "45"),
                  SoftDrinks(name: "Grape compote", type: .softDrinks, calories: "48"),
                  SoftDrinks(name: "Grape juice", type: .softDrinks, calories: "60"),
                  SoftDrinks(name: "Grape syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Grapefruit juice", type: .softDrinks, calories: "42"),
                  SoftDrinks(name: "Grapefruit syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Green mint syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Guava juice", type: .softDrinks, calories: "56"),
                  SoftDrinks(name: "Hazelnut syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Heather tea", type: .softDrinks, calories: "0"),
                  SoftDrinks(name: "Herbal Tea", type: .softDrinks, calories: "0"),
                  SoftDrinks(name: "Hibiscus Syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Honey syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Ice mint syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Iced tea (ice tea)", type: .softDrinks, calories: "1"),
                  SoftDrinks(name: "Irish coffee", type: .softDrinks, calories: "167"),
                  SoftDrinks(name: "Jasmine syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Jasmine tea", type: .softDrinks, calories: "0"),
                  SoftDrinks(name: "Juices", type: .softDrinks, calories: "40"),
                  SoftDrinks(name: "Kiwi juice", type: .softDrinks, calories: "50"),
                  SoftDrinks(name: "Kiwi syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Kvass", type: .softDrinks, calories: "20"),
                  SoftDrinks(name: "Latte Coffee", type: .softDrinks, calories: "125"),
                  SoftDrinks(name: "Latte macchiato coffee", type: .softDrinks, calories: "125"),
                  SoftDrinks(name: "Lavender Syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Lemon juice", type: .softDrinks, calories: "29"),
                  SoftDrinks(name: "Lemonade", type: .softDrinks, calories: "42"),
                  SoftDrinks(name: "Lime Sorbet", type: .softDrinks, calories: "60"),
                  SoftDrinks(name: "Lime cordial", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Lime juice", type: .softDrinks, calories: "30"),
                  SoftDrinks(name: "Lime syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Lingonberry juice", type: .softDrinks, calories: "44"),
                  SoftDrinks(name: "Lychee syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Macadamia syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Mango Syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Mango juice", type: .softDrinks, calories: "60"),
                  SoftDrinks(name: "Milkshake", type: .softDrinks, calories: "167"),
                  SoftDrinks(name: "Mineral water", type: .softDrinks, calories: "0"),
                  SoftDrinks(name: "Mineral water Narzan", type: .softDrinks, calories: "0"),
                  SoftDrinks(name: "Mint chocolate syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Mirinda", type: .softDrinks, calories: "42"),
                  SoftDrinks(name: "Moccachino coffee (moccachino)", type: .softDrinks, calories: "125"),
                  SoftDrinks(name: "Mojito syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Morse", type: .softDrinks, calories: "42"),
                  SoftDrinks(name: "Multifruit juice", type: .softDrinks, calories: "50"),
                  SoftDrinks(name: "Nectarine juice", type: .softDrinks, calories: "44"),
                  SoftDrinks(name: "Non-alcoholic beer", type: .softDrinks, calories: "20"),
                  SoftDrinks(name: "Noni juice", type: .softDrinks, calories: "47"),
                  SoftDrinks(name: "Orange juice", type: .softDrinks, calories: "47"),
                  SoftDrinks(name: "Orange sorbet", type: .softDrinks, calories: "60"),
                  SoftDrinks(name: "Oriental coffee (Turkish)", type: .softDrinks, calories: "1"),
                  SoftDrinks(name: "Oxygen cocktail", type: .softDrinks, calories: "15"),
                  SoftDrinks(name: "Papaya juice", type: .softDrinks, calories: "43"),
                  SoftDrinks(name: "Parsley juice", type: .softDrinks, calories: "36"),
                  SoftDrinks(name: "Passion Fruit juice", type: .softDrinks, calories: "97"),
                  SoftDrinks(name: "Passion fruit syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Peach juice", type: .softDrinks, calories: "48"),
                  SoftDrinks(name: "Peach syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Pear juice", type: .softDrinks, calories: "46"),
                  SoftDrinks(name: "Pear syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Pepsi", type: .softDrinks, calories: "42"),
                  SoftDrinks(name: "Pinacolada syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Pineapple juice", type: .softDrinks, calories: "46"),
                  SoftDrinks(name: "Pink Grapefruit syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Pistachio syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Plum compote", type: .softDrinks, calories: "48"),
                  SoftDrinks(name: "Plum juice", type: .softDrinks, calories: "46"),
                  SoftDrinks(name: "Pomegranate juice", type: .softDrinks, calories: "53"),
                  SoftDrinks(name: "Potato juice", type: .softDrinks, calories: "47"),
                  SoftDrinks(name: "Power engineer", type: .softDrinks, calories: "32"),
                  SoftDrinks(name: "Praline syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Pumpkin juice", type: .softDrinks, calories: "20"),
                  SoftDrinks(name: "Quince juice", type: .softDrinks, calories: "57"),
                  SoftDrinks(name: "Radish juice", type: .softDrinks, calories: "16"),
                  SoftDrinks(name: "Raspberry juice", type: .softDrinks, calories: "48"),
                  SoftDrinks(name: "Raspberry tea syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Rose Syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Rowan juice", type: .softDrinks, calories: "57"),
                  SoftDrinks(name: "Schweppes drink", type: .softDrinks, calories: "42"),
                  SoftDrinks(name: "Sea buckthorn juice", type: .softDrinks, calories: "45"),
                  SoftDrinks(name: "Sencha tea", type: .softDrinks, calories: "1"),
                  SoftDrinks(name: "Shorley's drink", type: .softDrinks, calories: "42"),
                  SoftDrinks(name: "Smoked tea", type: .softDrinks, calories: "1"),
                  SoftDrinks(name: "Soda water", type: .softDrinks, calories: "0"),
                  SoftDrinks(name: "Spicy syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Sprite", type: .softDrinks, calories: "42"),
                  SoftDrinks(name: "Strawberry candy syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Strawberry juice", type: .softDrinks, calories: "32"),
                  SoftDrinks(name: "Syrup black forest", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Tangerine compote", type: .softDrinks, calories: "48"),
                  SoftDrinks(name: "Tangerine juice", type: .softDrinks, calories: "47"),
                  SoftDrinks(name: "Tangerine syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Tarragon drink", type: .softDrinks, calories: "17"),
                  SoftDrinks(name: "Tarragon syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Tiramisu syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Toffee syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Tomato juice", type: .softDrinks, calories: "17"),
                  SoftDrinks(name: "Tonic", type: .softDrinks, calories: "42"),
                  SoftDrinks(name: "Uzvar", type: .softDrinks, calories: "48"),
                  SoftDrinks(name: "Vanilla syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Vegetable juices", type: .softDrinks, calories: "20"),
                  SoftDrinks(name: "Violet syrup", type: .softDrinks, calories: "300"),
                  SoftDrinks(name: "Water", type: .softDrinks, calories: "0"),
                  SoftDrinks(name: "Watermelon juice", type: .softDrinks, calories: "30"),
                  SoftDrinks(name: "Wood-strawberry juice", type: .softDrinks, calories: "32")]

