//
//  SpicesandSeasoningsData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 17.10.2023.
//

import Foundation

let spicesAndSeasonings = [FoodRealm(name: "Allspice", type: .spicesAndSeasonings, calories: "251"),
                           FoodRealm(name: "Anise", type: .spicesAndSeasonings, calories: "311"),
                           FoodRealm(name: "Asafoetida ground", type: .spicesAndSeasonings, calories: "276"),
                           FoodRealm(name: "Azhgon", type: .spicesAndSeasonings, calories: "276"),
                           FoodRealm(name: "Baharat", type: .spicesAndSeasonings, calories: "265"),
                           FoodRealm(name: "Barbecue seasoning", type: .spicesAndSeasonings, calories: "30"),
                           FoodRealm(name: "Bay leaf", type: .spicesAndSeasonings, calories: "313"),
                           FoodRealm(name: "Berbere", type: .spicesAndSeasonings, calories: "284"),
                           FoodRealm(name: "Black Cardamom", type: .spicesAndSeasonings, calories: "251"),
                           FoodRealm(name: "Black Sesame", type: .spicesAndSeasonings, calories: "586"),
                           FoodRealm(name: "Black Thursday salt", type: .spicesAndSeasonings, calories: "0"),
                           FoodRealm(name: "Black mustard (French)", type: .spicesAndSeasonings, calories: "208"),
                           FoodRealm(name: "Black pepper peas", type: .spicesAndSeasonings, calories: "251"),
                           FoodRealm(name: "Black seed (kalinji)", type: .spicesAndSeasonings, calories: "568"),
                           FoodRealm(name: "Bouquet of garnishes", type: .spicesAndSeasonings, calories: "20"),
                           FoodRealm(name: "Bumbu", type: .spicesAndSeasonings, calories: "265"),
                           FoodRealm(name: "Cane sugar", type: .spicesAndSeasonings, calories: "380"),
                           FoodRealm(name: "Canned capers", type: .spicesAndSeasonings, calories: "23"),
                           FoodRealm(name: "Cardamom", type: .spicesAndSeasonings, calories: "311"),
                           FoodRealm(name: "Carnation", type: .spicesAndSeasonings, calories: "127"),
                           FoodRealm(name: "Carob", type: .spicesAndSeasonings, calories: "191"),
                           FoodRealm(name: "Cassia", type: .spicesAndSeasonings, calories: "251"),
                           FoodRealm(name: "Chicken seasoning", type: .spicesAndSeasonings, calories: "10"),
                           FoodRealm(name: "Chicory", type: .spicesAndSeasonings, calories: "72"),
                           FoodRealm(name: "Chicory Root", type: .spicesAndSeasonings, calories: "45"),
                           FoodRealm(name: "Chinese ginger krachai", type: .spicesAndSeasonings, calories: "80"),
                           FoodRealm(name: "Chinese pepper in granules", type: .spicesAndSeasonings, calories: "251"),
                           FoodRealm(name: "Cinnamon", type: .spicesAndSeasonings, calories: "247"),
                           FoodRealm(name: "Cinnamon sticks", type: .spicesAndSeasonings, calories: "247"),
                           FoodRealm(name: "Coriander", type: .spicesAndSeasonings, calories: "299"),
                           FoodRealm(name: "Cumin", type: .spicesAndSeasonings, calories: "375"),
                           FoodRealm(name: "Curry", type: .spicesAndSeasonings, calories: "293"),
                           FoodRealm(name: "Dill seeds", type: .spicesAndSeasonings, calories: "271"),
                           FoodRealm(name: "Dried Marjoram", type: .spicesAndSeasonings, calories: "305"),
                           FoodRealm(name: "Dried basil", type: .spicesAndSeasonings, calories: "265"),
                           FoodRealm(name: "Dried chervil", type: .spicesAndSeasonings, calories: "305"),
                           FoodRealm(name: "Dried cilantro", type: .spicesAndSeasonings, calories: "250"),
                           FoodRealm(name: "Dried dill", type: .spicesAndSeasonings, calories: "271"),
                           FoodRealm(name: "Dried galangal", type: .spicesAndSeasonings, calories: "334"),
                           FoodRealm(name: "Dried garlic", type: .spicesAndSeasonings, calories: "231"),
                           FoodRealm(name: "Dried mint", type: .spicesAndSeasonings, calories: "282"),
                           FoodRealm(name: "Dried onion", type: .spicesAndSeasonings, calories: "40"),
                           FoodRealm(name: "Dried oregano (oregano)", type: .spicesAndSeasonings, calories: "261"),
                           FoodRealm(name: "Dried paprika", type: .spicesAndSeasonings, calories: "282"),
                           FoodRealm(name: "Dried parsley", type: .spicesAndSeasonings, calories: "290"),
                           FoodRealm(name: "Dried rosemary", type: .spicesAndSeasonings, calories: "331"),
                           FoodRealm(name: "Dried sage", type: .spicesAndSeasonings, calories: "315"),
                           FoodRealm(name: "Dried tarragon", type: .spicesAndSeasonings, calories: "276"),
                           FoodRealm(name: "Dried thyme", type: .spicesAndSeasonings, calories: "276"),
                           FoodRealm(name: "Fennel seeds", type: .spicesAndSeasonings, calories: "234"),
                           FoodRealm(name: "Fenugreek seeds", type: .spicesAndSeasonings, calories: "323"),
                           FoodRealm(name: "Galangal Root", type: .spicesAndSeasonings, calories: "80"),
                           FoodRealm(name: "Garam masala", type: .spicesAndSeasonings, calories: "265"),
                           FoodRealm(name: "Garlic pepper", type: .spicesAndSeasonings, calories: "10"),
                           FoodRealm(name: "Ginger Root", type: .spicesAndSeasonings, calories: "80"),
                           FoodRealm(name: "Ginseng", type: .spicesAndSeasonings, calories: "370"),
                           FoodRealm(name: "Grapefruit zest", type: .spicesAndSeasonings, calories: "31"),
                           FoodRealm(name: "Grated horseradish", type: .spicesAndSeasonings, calories: "109"),
                           FoodRealm(name: "Green pepper with peas", type: .spicesAndSeasonings, calories: "251"),
                           FoodRealm(name: "Gremolata", type: .spicesAndSeasonings, calories: "320"),
                           FoodRealm(name: "Ground Chinese pepper", type: .spicesAndSeasonings, calories: "251"),
                           FoodRealm(name: "Ground black pepper", type: .spicesAndSeasonings, calories: "251"),
                           FoodRealm(name: "Ground cherry", type: .spicesAndSeasonings, calories: "293"),
                           FoodRealm(name: "Ground cinnamon", type: .spicesAndSeasonings, calories: "228"),
                           FoodRealm(name: "Ground coriander", type: .spicesAndSeasonings, calories: "298"),
                           FoodRealm(name: "Ground dry ginger", type: .spicesAndSeasonings, calories: "325"),
                           FoodRealm(name: "Ground nutmeg", type: .spicesAndSeasonings, calories: "525"),
                           FoodRealm(name: "Ground red pepper", type: .spicesAndSeasonings, calories: "251"),
                           FoodRealm(name: "Ground white pepper", type: .spicesAndSeasonings, calories: "251"),
                           FoodRealm(name: "Hops-suneli", type: .spicesAndSeasonings, calories: "253"),
                           FoodRealm(name: "Horseradish sauce", type: .spicesAndSeasonings, calories: "80"),
                           FoodRealm(name: "Imeretian saffron", type: .spicesAndSeasonings, calories: "310"),
                           FoodRealm(name: "Italian herbs", type: .spicesAndSeasonings, calories: "251"),
                           FoodRealm(name: "Japanese pepper kalufer", type: .spicesAndSeasonings, calories: "251"),
                           FoodRealm(name: "Korean carrot seasoning", type: .spicesAndSeasonings, calories: "20"),
                           FoodRealm(name: "Lamb seasoning", type: .spicesAndSeasonings, calories: "10"),
                           FoodRealm(name: "Lemon zest", type: .spicesAndSeasonings, calories: "17"),
                           FoodRealm(name: "Licorice (licorice)", type: .spicesAndSeasonings, calories: "380"),
                           FoodRealm(name: "Licorice root", type: .spicesAndSeasonings, calories: "249"),
                           FoodRealm(name: "Lime zest", type: .spicesAndSeasonings, calories: "30"),
                           FoodRealm(name: "Long black pepper", type: .spicesAndSeasonings, calories: "251"),
                           FoodRealm(name: "Lotus Root", type: .spicesAndSeasonings, calories: "74"),
                           FoodRealm(name: "Lumi", type: .spicesAndSeasonings, calories: "20"),
                           FoodRealm(name: "Mac", type: .spicesAndSeasonings, calories: "10"),
                           FoodRealm(name: "Masala", type: .spicesAndSeasonings, calories: "265"),
                           FoodRealm(name: "Minionet", type: .spicesAndSeasonings, calories: "150"),
                           FoodRealm(name: "Mushroom seasoning", type: .spicesAndSeasonings, calories: "20"),
                           FoodRealm(name: "Mustard powder", type: .spicesAndSeasonings, calories: "208"),
                           FoodRealm(name: "Mustard seeds", type: .spicesAndSeasonings, calories: "508"),
                           FoodRealm(name: "Nutmeg", type: .spicesAndSeasonings, calories: "525"),
                           FoodRealm(name: "Nutmeg color of macis", type: .spicesAndSeasonings, calories: "525"),
                           FoodRealm(name: "Oatmeal root kozloborodnik", type: .spicesAndSeasonings, calories: "218"),
                           FoodRealm(name: "Orange peel", type: .spicesAndSeasonings, calories: "47"),
                           FoodRealm(name: "Pepper mixture", type: .spicesAndSeasonings, calories: "251"),
                           FoodRealm(name: "Pepper pink peas", type: .spicesAndSeasonings, calories: "251"),
                           FoodRealm(name: "Pickled capers", type: .spicesAndSeasonings, calories: "23"),
                           FoodRealm(name: "Pickled ginger", type: .spicesAndSeasonings, calories: "60"),
                           FoodRealm(name: "Pink Salt", type: .spicesAndSeasonings, calories: "0"),
                           FoodRealm(name: "Pizza seasoning", type: .spicesAndSeasonings, calories: "20"),
                           FoodRealm(name: "Potato seasoning", type: .spicesAndSeasonings, calories: "10"),
                           FoodRealm(name: "Provencal herbs", type: .spicesAndSeasonings, calories: "251"),
                           FoodRealm(name: "Russian mustard (Sarepta)", type: .spicesAndSeasonings, calories: "208"),
                           FoodRealm(name: "Saffron", type: .spicesAndSeasonings, calories: "310"),
                           FoodRealm(name: "Sea salt", type: .spicesAndSeasonings, calories: "0"),
                           FoodRealm(name: "Seasoning 10 vegetables", type: .spicesAndSeasonings, calories: "20"),
                           FoodRealm(name: "Seasoning for borscht", type: .spicesAndSeasonings, calories: "10"),
                           FoodRealm(name: "Seasoning for dumplings", type: .spicesAndSeasonings, calories: "10"),
                           FoodRealm(name: "Seasoning for fish", type: .spicesAndSeasonings, calories: "10"),
                           FoodRealm(name: "Seasoning for fish soup", type: .spicesAndSeasonings, calories: "10"),
                           FoodRealm(name: "Seasoning for goulash", type: .spicesAndSeasonings, calories: "10"),
                           FoodRealm(name: "Seasoning for lard", type: .spicesAndSeasonings, calories: "5"),
                           FoodRealm(name: "Seasoning for minced meat", type: .spicesAndSeasonings, calories: "10"),
                           FoodRealm(name: "Seasoning for pilaf", type: .spicesAndSeasonings, calories: "10"),
                           FoodRealm(name: "Seasoning for rice", type: .spicesAndSeasonings, calories: "10"),
                           FoodRealm(name: "Seasoning for soup", type: .spicesAndSeasonings, calories: "10"),
                           FoodRealm(name: "Seasonings for meat", type: .spicesAndSeasonings, calories: "10"),
                           FoodRealm(name: "Sesame", type: .spicesAndSeasonings, calories: "568"),
                           FoodRealm(name: "Shea butter (karite)", type: .spicesAndSeasonings, calories: "898"),
                           FoodRealm(name: "Shichimi", type: .spicesAndSeasonings, calories: "228"),
                           FoodRealm(name: "Siamese (Thai) mixture", type: .spicesAndSeasonings, calories: "131"),
                           FoodRealm(name: "Smoked salt", type: .spicesAndSeasonings, calories: "0"),
                           FoodRealm(name: "Spices", type: .spicesAndSeasonings, calories: "251"),
                           FoodRealm(name: "Seasonings", type: .spicesAndSeasonings, calories: "20"),
                           FoodRealm(name: "Spicy herbs", type: .spicesAndSeasonings, calories: "150"),
                           FoodRealm(name: "Star anise", type: .spicesAndSeasonings, calories: "316"),
                           FoodRealm(name: "Star-shaped anise", type: .spicesAndSeasonings, calories: "316"),
                           FoodRealm(name: "Sugar", type: .spicesAndSeasonings, calories: "400"),
                           FoodRealm(name: "Sumac seasoning", type: .spicesAndSeasonings, calories: "360"),
                           FoodRealm(name: "Svan salt", type: .spicesAndSeasonings, calories: "0"),
                           FoodRealm(name: "Sweet sugar", type: .spicesAndSeasonings, calories: "400"),
                           FoodRealm(name: "Table salt", type: .spicesAndSeasonings, calories: "0"),
                           FoodRealm(name: "Tamarind paste", type: .spicesAndSeasonings, calories: "240"),
                           FoodRealm(name: "Tandoori masala", type: .spicesAndSeasonings, calories: "255"),
                           FoodRealm(name: "The root of love", type: .spicesAndSeasonings, calories: "218"),
                           FoodRealm(name: "Turmeric", type: .spicesAndSeasonings, calories: "312"),
                           FoodRealm(name: "Turmeric Root", type: .spicesAndSeasonings, calories: "80"),
                           FoodRealm(name: "Universal seasoning", type: .spicesAndSeasonings, calories: "10"),
                           FoodRealm(name: "Vanilla", type: .spicesAndSeasonings, calories: "288"),
                           FoodRealm(name: "Vanilla Powder", type: .spicesAndSeasonings, calories: "288"),
                           FoodRealm(name: "Vanilla in pods", type: .spicesAndSeasonings, calories: "288"),
                           FoodRealm(name: "Vanilla sugar", type: .spicesAndSeasonings, calories: "397"),
                           FoodRealm(name: "Vegetable seasoning", type: .spicesAndSeasonings, calories: "20"),
                           FoodRealm(name: "Water pepper", type: .spicesAndSeasonings, calories: "251"),
                           FoodRealm(name: "White mustard (English)", type: .spicesAndSeasonings, calories: "208"),
                           FoodRealm(name: "White pepper", type: .spicesAndSeasonings, calories: "251"),
                           FoodRealm(name: "Zantoxylum", type: .spicesAndSeasonings, calories: "344"),
                           FoodRealm(name: "Zira", type: .spicesAndSeasonings, calories: "375"),
                           FoodRealm(name: "Zubrovka fragrant", type: .spicesAndSeasonings, calories: "293")]

