//
//  SweetsAndConfectioneryData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 16.10.2023.
//

import Foundation

let sweetsAndConfectionery = [FoodRealm(name: "Acacia honey", type: .sweetsAndConfectionery, calories: "300"),
                              FoodRealm(name: "Acan Powder", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Air cakes (meringues)", type: .sweetsAndConfectionery, calories: "340"),
                              FoodRealm(name: "Air wheat", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Almond honey", type: .sweetsAndConfectionery, calories: "300"),
                              FoodRealm(name: "Amaretti", type: .sweetsAndConfectionery, calories: "426"),
                              FoodRealm(name: "Angelica honey", type: .sweetsAndConfectionery, calories: "300"),
                              FoodRealm(name: "Anzac", type: .sweetsAndConfectionery, calories: "446"),
                              FoodRealm(name: "Apple chips", type: .sweetsAndConfectionery, calories: "280"),
                              FoodRealm(name: "Apple confiture", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Apple jam", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Apple jelly", type: .sweetsAndConfectionery, calories: "250"),
                              FoodRealm(name: "Apple pastille", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Apple-lingonberry jam", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Apricot jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Apricot marmalade", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Artificial honey", type: .sweetsAndConfectionery, calories: "310"),
                              FoodRealm(name: "Baklava", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Banana chips", type: .sweetsAndConfectionery, calories: "387"),
                              FoodRealm(name: "Banana confiture", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Banana jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Barberry lollipops", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Basil sorbet", type: .sweetsAndConfectionery, calories: "170"),
                              FoodRealm(name: "Baursaki", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Bavarian cream", type: .sweetsAndConfectionery, calories: "167"),
                              FoodRealm(name: "Berry confiture", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Berry jam", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Bird cherry jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Biscotti cookies", type: .sweetsAndConfectionery, calories: "446"),
                              FoodRealm(name: "Biscuit", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Biscuit roll", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Biscuits", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Bitter chocolate", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "Black currant jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Blackberry jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Blackcurrant jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Blueberry confiture", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Blueberry jam", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Bog whortleberry jam", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Boiled condensed milk", type: .sweetsAndConfectionery, calories: "335"),
                              FoodRealm(name: "Brownie Cake", type: .sweetsAndConfectionery, calories: "385"),
                              FoodRealm(name: "Buckwheat honey", type: .sweetsAndConfectionery, calories: "300"),
                              FoodRealm(name: "Butter cookies", type: .sweetsAndConfectionery, calories: "446"),
                              FoodRealm(name: "Butter cream", type: .sweetsAndConfectionery, calories: "467"),
                              FoodRealm(name: "Cake basket", type: .sweetsAndConfectionery, calories: "335"),
                              FoodRealm(name: "Cake nut", type: .sweetsAndConfectionery, calories: "335"),
                              FoodRealm(name: "Cake", type: .sweetsAndConfectionery, calories: "335"),
                              FoodRealm(name: "Cakes", type: .sweetsAndConfectionery, calories: "335"),
                              FoodRealm(name: "Candy", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Candy Lollipops", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Candy Truffle", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "Candy dragees", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Candy iris", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Candy souffle", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Cane sugar in cubes", type: .sweetsAndConfectionery, calories: "400"),
                              FoodRealm(name: "Canned apples", type: .sweetsAndConfectionery, calories: "42"),
                              FoodRealm(name: "Canned apricots", type: .sweetsAndConfectionery, calories: "48"),
                              FoodRealm(name: "Canned fruit", type: .sweetsAndConfectionery, calories: "42"),
                              FoodRealm(name: "Canned peaches", type: .sweetsAndConfectionery, calories: "42"),
                              FoodRealm(name: "Canned pear", type: .sweetsAndConfectionery, calories: "42"),
                              FoodRealm(name: "Canned pineapples", type: .sweetsAndConfectionery, calories: "42"),
                              FoodRealm(name: "Canned strawberries", type: .sweetsAndConfectionery, calories: "42"),
                              FoodRealm(name: "Caramel", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Cherry confiture", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Cherry jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Cherry jelly", type: .sweetsAndConfectionery, calories: "250"),
                              FoodRealm(name: "Cherry plum jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Chocolate", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "Chocolate Eggs Kinder Surprise", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "Chocolate Sponge cake", type: .sweetsAndConfectionery, calories: "385"),
                              FoodRealm(name: "Chocolate Sponge roll", type: .sweetsAndConfectionery, calories: "385"),
                              FoodRealm(name: "Chocolate balls", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "Chocolate bars", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "Chocolate candies", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "Chocolate cookies", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Chocolate ganache", type: .sweetsAndConfectionery, calories: "567"),
                              FoodRealm(name: "Chocolate gingerbread", type: .sweetsAndConfectionery, calories: "385"),
                              FoodRealm(name: "Chocolate ice cream", type: .sweetsAndConfectionery, calories: "220"),
                              FoodRealm(name: "Chocolate mousse", type: .sweetsAndConfectionery, calories: "220"),
                              FoodRealm(name: "Chocolate on fructose", type: .sweetsAndConfectionery, calories: "550"),
                              FoodRealm(name: "Chocolate pads", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "Chocolate-nut paste", type: .sweetsAndConfectionery, calories: "576"),
                              FoodRealm(name: "Chocolates prunes in chocolate", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "Chokeberry jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Chokolatl", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "Chuck-chuck", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Churchkhela", type: .sweetsAndConfectionery, calories: "467"),
                              FoodRealm(name: "Cocktail cherry", type: .sweetsAndConfectionery, calories: "50"),
                              FoodRealm(name: "Coconut cream", type: .sweetsAndConfectionery, calories: "230"),
                              FoodRealm(name: "Coconut puree", type: .sweetsAndConfectionery, calories: "230"),
                              FoodRealm(name: "Confiture", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Cookie Cracker", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Cookies", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Cookies brushwood", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Cookies nuts with condensed milk", type: .sweetsAndConfectionery, calories: "467"),
                              FoodRealm(name: "Corn Balls", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Corn sticks", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Cottage cheese jelly", type: .sweetsAndConfectionery, calories: "83"),
                              FoodRealm(name: "Cotton candy pink", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Cranberries in sugar", type: .sweetsAndConfectionery, calories: "308"),
                              FoodRealm(name: "Cranberry jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Cream chocolate", type: .sweetsAndConfectionery, calories: "567"),
                              FoodRealm(name: "Cream ganache", type: .sweetsAndConfectionery, calories: "567"),
                              FoodRealm(name: "Creme brulee ice cream", type: .sweetsAndConfectionery, calories: "220"),
                              FoodRealm(name: "Cupcake rum woman", type: .sweetsAndConfectionery, calories: "350"),
                              FoodRealm(name: "Currant jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Custard", type: .sweetsAndConfectionery, calories: "167"),
                              FoodRealm(name: "Custard cake", type: .sweetsAndConfectionery, calories: "335"),
                              FoodRealm(name: "Custard lemon cream", type: .sweetsAndConfectionery, calories: "167"),
                              FoodRealm(name: "Dandelion jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Dessert creme brulee", type: .sweetsAndConfectionery, calories: "220"),
                              FoodRealm(name: "Dessert sambuk", type: .sweetsAndConfectionery, calories: "385"),
                              FoodRealm(name: "Dogwood jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Donuts", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Eclair cake", type: .sweetsAndConfectionery, calories: "385"),
                              FoodRealm(name: "Energy Candies", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "English custard", type: .sweetsAndConfectionery, calories: "167"),
                              FoodRealm(name: "Eucalyptus honey", type: .sweetsAndConfectionery, calories: "300"),
                              FoodRealm(name: "Fake honey", type: .sweetsAndConfectionery, calories: "310"),
                              FoodRealm(name: "Feijoa jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Ferrero Rocher Candy", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "Fig jam", type: .sweetsAndConfectionery, calories: "249"),
                              FoodRealm(name: "Flower Honey", type: .sweetsAndConfectionery, calories: "300"),
                              FoodRealm(name: "Fondant candies", type: .sweetsAndConfectionery, calories: "500"),
                              FoodRealm(name: "Frangipane", type: .sweetsAndConfectionery, calories: "500"),
                              FoodRealm(name: "Fruit spread", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Fruits in chocolate", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "Galaretka", type: .sweetsAndConfectionery, calories: "83"),
                              FoodRealm(name: "Ginger jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Gingerbread", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Gingerbread cookies", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Gingerbread goats", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Gingerbread house", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Gingerbread man", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Glazed cheeses", type: .sweetsAndConfectionery, calories: "83"),
                              FoodRealm(name: "Golden sugar balls", type: .sweetsAndConfectionery, calories: "400"),
                              FoodRealm(name: "Gooseberry jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Grape jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Green Marmalade", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Grillage candies", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Halva", type: .sweetsAndConfectionery, calories: "560"),
                              FoodRealm(name: "Hawthorn jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Heather honey", type: .sweetsAndConfectionery, calories: "300"),
                              FoodRealm(name: "Hematogen", type: .sweetsAndConfectionery, calories: "467"),
                              FoodRealm(name: "Honey bee", type: .sweetsAndConfectionery, calories: "300"),
                              FoodRealm(name: "Honeydew", type: .sweetsAndConfectionery, calories: "335"),
                              FoodRealm(name: "Hot chocolate", type: .sweetsAndConfectionery, calories: "500"),
                              FoodRealm(name: "Ice cream", type: .sweetsAndConfectionery, calories: "220"),
                              FoodRealm(name: "Ice cream fruit ice", type: .sweetsAndConfectionery, calories: "220"),
                              FoodRealm(name: "Icing", type: .sweetsAndConfectionery, calories: "467"),
                              FoodRealm(name: "Jam", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Jam from irga", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Jam from paradise apples", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Jam from pine cones", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Jelly", type: .sweetsAndConfectionery, calories: "250"),
                              FoodRealm(name: "Jelly for cake", type: .sweetsAndConfectionery, calories: "250"),
                              FoodRealm(name: "Kiwi jelly", type: .sweetsAndConfectionery, calories: "250"),
                              FoodRealm(name: "Kos-halva", type: .sweetsAndConfectionery, calories: "560"),
                              FoodRealm(name: "Kovrizhka", type: .sweetsAndConfectionery, calories: "446"),
                              FoodRealm(name: "Kozinaki", type: .sweetsAndConfectionery, calories: "560"),
                              FoodRealm(name: "Kurabye cookies", type: .sweetsAndConfectionery, calories: "446"),
                              FoodRealm(name: "Lamingtons", type: .sweetsAndConfectionery, calories: "385"),
                              FoodRealm(name: "Lemon jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Lemon jelly", type: .sweetsAndConfectionery, calories: "250"),
                              FoodRealm(name: "Licorice candies", type: .sweetsAndConfectionery, calories: "400"),
                              FoodRealm(name: "Lingonberry jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Lollipops of Montpensier", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Lukma", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Macaroni Cookies", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Madeleine Cookies", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Mango Jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Maple syrup", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Marmalade", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Marshmallow", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Marshmallow Marshmallow", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Marshmallow cream", type: .sweetsAndConfectionery, calories: "467"),
                              FoodRealm(name: "Marshmallows in chocolate", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "Marzipan", type: .sweetsAndConfectionery, calories: "467"),
                              FoodRealm(name: "May honey", type: .sweetsAndConfectionery, calories: "300"),
                              FoodRealm(name: "Melon jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Meringue cookies", type: .sweetsAndConfectionery, calories: "340"),
                              FoodRealm(name: "Milk chocolate", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "Milk jelly", type: .sweetsAndConfectionery, calories: "83"),
                              FoodRealm(name: "Monofleral honey", type: .sweetsAndConfectionery, calories: "300"),
                              FoodRealm(name: "Mousse", type: .sweetsAndConfectionery, calories: "220"),
                              FoodRealm(name: "Muesli", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Mushroom Cookies", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Nectarine jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Nougat", type: .sweetsAndConfectionery, calories: "560"),
                              FoodRealm(name: "Nutella Paste", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "Nuts in chocolate", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "Oatmeal cookies", type: .sweetsAndConfectionery, calories: "446"),
                              FoodRealm(name: "Orange chocolate", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "Orange confiture", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Orange jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Orange jelly", type: .sweetsAndConfectionery, calories: "250"),
                              FoodRealm(name: "Parfait", type: .sweetsAndConfectionery, calories: "220"),
                              FoodRealm(name: "Pastille", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Pastry tubes", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Peach confiture", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Peach jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Peach marmelade", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Peanut halva", type: .sweetsAndConfectionery, calories: "563"),
                              FoodRealm(name: "Peanut paste", type: .sweetsAndConfectionery, calories: "563"),
                              FoodRealm(name: "Pear jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Pear marmalade", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Physalis jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Pineapple jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Plum confiture", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Plum jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Plum marmelade", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Popcorn", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Porous chocolate", type: .sweetsAndConfectionery, calories: "535"),
                              FoodRealm(name: "Porous milk chocolate", type: .sweetsAndConfectionery, calories: "535"),
                              FoodRealm(name: "Potato cake", type: .sweetsAndConfectionery, calories: "300"),
                              FoodRealm(name: "Praline", type: .sweetsAndConfectionery, calories: "500"),
                              FoodRealm(name: "Pudding", type: .sweetsAndConfectionery, calories: "167"),
                              FoodRealm(name: "Puff pastry ears", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Puff pastry pies", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Pumpkin jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Quince jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Raffaello Candy", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "Rapeseed honey", type: .sweetsAndConfectionery, calories: "300"),
                              FoodRealm(name: "Raspberry confiture", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Raspberry jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Raspberry jelly", type: .sweetsAndConfectionery, calories: "250"),
                              FoodRealm(name: "Ready-made cakes for Napoleon", type: .sweetsAndConfectionery, calories: "335"),
                              FoodRealm(name: "Ready-made sponge cakes", type: .sweetsAndConfectionery, calories: "385"),
                              FoodRealm(name: "Rhubarb jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Rice Pudding", type: .sweetsAndConfectionery, calories: "220"),
                              FoodRealm(name: "Rose jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Rosehip jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Sea buckthorn confiture", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Sea buckthorn jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Sesame halva", type: .sweetsAndConfectionery, calories: "563"),
                              FoodRealm(name: "Sesame kozinaki", type: .sweetsAndConfectionery, calories: "560"),
                              FoodRealm(name: "Shaker churek", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Shaker drill", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Sherbet", type: .sweetsAndConfectionery, calories: "220"),
                              FoodRealm(name: "Shortbread cookies", type: .sweetsAndConfectionery, calories: "446"),
                              FoodRealm(name: "Shortbread ring cake with nuts", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Skimmed cocoa. Powder", type: .sweetsAndConfectionery, calories: "228"),
                              FoodRealm(name: "Slices", type: .sweetsAndConfectionery, calories: "335"),
                              FoodRealm(name: "Sloe jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Sorbet Ice cream", type: .sweetsAndConfectionery, calories: "220"),
                              FoodRealm(name: "Souffle", type: .sweetsAndConfectionery, calories: "167"),
                              FoodRealm(name: "Strawberry confiture", type: .sweetsAndConfectionery, calories: "260"),
                              FoodRealm(name: "Strawberry ice cream", type: .sweetsAndConfectionery, calories: "220"),
                              FoodRealm(name: "Strawberry jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Strawberry jelly", type: .sweetsAndConfectionery, calories: "250"),
                              FoodRealm(name: "Sugar cookies", type: .sweetsAndConfectionery, calories: "446"),
                              FoodRealm(name: "Sugar mastic", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Sugar on a stick brown", type: .sweetsAndConfectionery, calories: "400"),
                              FoodRealm(name: "Sunflower halva", type: .sweetsAndConfectionery, calories: "563"),
                              FoodRealm(name: "Sunflower honey", type: .sweetsAndConfectionery, calories: "300"),
                              FoodRealm(name: "Tiramisu chocolate", type: .sweetsAndConfectionery, calories: "385"),
                              FoodRealm(name: "Tiramisu dessert", type: .sweetsAndConfectionery, calories: "220"),
                              FoodRealm(name: "Truffle chocolate", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "Tula gingerbread", type: .sweetsAndConfectionery, calories: "455"),
                              FoodRealm(name: "Turkish delight", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Vanilla ice cream", type: .sweetsAndConfectionery, calories: "220"),
                              FoodRealm(name: "Viburnum jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Viennese waffles", type: .sweetsAndConfectionery, calories: "360"),
                              FoodRealm(name: "Waffle cups", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "Waffles", type: .sweetsAndConfectionery, calories: "360"),
                              FoodRealm(name: "Walnut jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Wheat slices", type: .sweetsAndConfectionery, calories: "335"),
                              FoodRealm(name: "White chocolate", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "White cotton candy", type: .sweetsAndConfectionery, calories: "380"),
                              FoodRealm(name: "White ganache", type: .sweetsAndConfectionery, calories: "567"),
                              FoodRealm(name: "White porous chocolate", type: .sweetsAndConfectionery, calories: "535"),
                              FoodRealm(name: "Wild strawberry jam", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Writing", type: .sweetsAndConfectionery, calories: "545"),
                              FoodRealm(name: "Yellow Marmalade", type: .sweetsAndConfectionery, calories: "258"),
                              FoodRealm(name: "Zucchini jam", type: .sweetsAndConfectionery, calories: "258")]

