//
//  FoodData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 21.05.2022.
//

import Foundation

let vegitables = [
    FoodRealm(name: "Adzuki beans", type: .vegetables, calories: "128"),
    FoodRealm(name: "African bird's eye chili", type: .vegetables, calories: "40"),
    FoodRealm(name: "African horned cucumber", type: .vegetables, calories: "14"),
    FoodRealm(name: "Ancho", type: .vegetables, calories: "40"),
    FoodRealm(name: "Apple pepper", type: .vegetables, calories: "26"),
    FoodRealm(name: "Artichoke", type: .vegetables, calories: "47"),
    FoodRealm(name: "Baby carrots", type: .vegetables, calories: "41"),
    FoodRealm(name: "Baby corn", type: .vegetables, calories: "24"),
    FoodRealm(name: "Bean sprouts", type: .vegetables, calories: "32"),
    FoodRealm(name: "Beans", type: .vegetables, calories: "-"),
    FoodRealm(name: "Beetroot", type: .vegetables, calories: "43"),
    FoodRealm(name: "Bell pepper", type: .vegetables, calories: "31"),
    FoodRealm(name: "Beluga lentils", type: .vegetables, calories: "336"),
    FoodRealm(name: "Bitter melon", type: .vegetables, calories: "17"),
    FoodRealm(name: "Black beans", type: .vegetables, calories: "132"),
    FoodRealm(name: "Black garlic", type: .vegetables, calories: "106"),
    FoodRealm(name: "Black olives", type: .vegetables, calories: "115"),
    FoodRealm(name: "Black radish", type: .vegetables, calories: "21"),
    FoodRealm(name: "Black salsify", type: .vegetables, calories: "87"),
    FoodRealm(name: "Boiled beetroot", type: .vegetables, calories: "35"),
    FoodRealm(name: "Boiled carrots", type: .vegetables, calories: "41"),
    FoodRealm(name: "Boiled potatoes", type: .vegetables, calories: "87"),
    FoodRealm(name: "Bottle gourd", type: .vegetables, calories: "14"),
    FoodRealm(name: "Breadfruit", type: .vegetables, calories: "103"),
    FoodRealm(name: "Broccoli", type: .vegetables, calories: "31"),
    FoodRealm(name: "Brussels sprouts", type: .vegetables, calories: "43"),
    FoodRealm(name: "Burdock root", type: .vegetables, calories: "72"),
    FoodRealm(name: "Butternut squash", type: .vegetables, calories: "45"),
    FoodRealm(name: "Cabbage pak choi", type: .vegetables, calories: "13"),
    FoodRealm(name: "Cabbage", type: .vegetables, calories: "25"),
    FoodRealm(name: "Canned beans in tomato sauce", type: .vegetables, calories: "83"),
    FoodRealm(name: "Canned beans", type: .vegetables, calories: "75"),
    FoodRealm(name: "Canned beets", type: .vegetables, calories: "35"),
    FoodRealm(name: "Canned black olives", type: .vegetables, calories: "115"),
    FoodRealm(name: "Canned broad beans", type: .vegetables, calories: "48"),
    FoodRealm(name: "Canned cabbage", type: .vegetables, calories: "26"),
    FoodRealm(name: "Canned carrots", type: .vegetables, calories: "37"),
    FoodRealm(name: "Canned cauliflower", type: .vegetables, calories: "27"),
    FoodRealm(name: "Canned celery", type: .vegetables, calories: "15"),
    FoodRealm(name: "Canned cherry tomatoes", type: .vegetables, calories: "19"),
    FoodRealm(name: "Canned corn cobs", type: .vegetables, calories: "76"),
    FoodRealm(name: "Canned cucumbers", type: .vegetables, calories: "12"),
    FoodRealm(name: "Canned eggplants", type: .vegetables, calories: "38"),
    FoodRealm(name: "Canned gherkins", type: .vegetables, calories: "12"),
    FoodRealm(name: "Canned green beans", type: .vegetables, calories: "25"),
    FoodRealm(name: "Canned green peas", type: .vegetables, calories: "71"),
    FoodRealm(name: "Canned green tomatoes", type: .vegetables, calories: "18"),
    FoodRealm(name: "Canned kidney beans", type: .vegetables, calories: "86"),
    FoodRealm(name: "Canned lentils", type: .vegetables, calories: "73"),
    FoodRealm(name: "Canned olives", type: .vegetables, calories: "115"),
    FoodRealm(name: "Canned onions", type: .vegetables, calories: "24"),
    FoodRealm(name: "Canned radish", type: .vegetables, calories: "23"),
    FoodRealm(name: "Canned squash", type: .vegetables, calories: "16"),
    FoodRealm(name: "Canned sweet pepper", type: .vegetables, calories: "26"),
    FoodRealm(name: "Canned tomatoes", type: .vegetables, calories: "17"),
    FoodRealm(name: "Canned vegetables", type: .vegetables, calories: "34"),
    FoodRealm(name: "Canned white beans", type: .vegetables, calories: "77"),
    FoodRealm(name: "Canned whole tomatoes", type: .vegetables, calories: "20"),
    FoodRealm(name: "Canned zucchini", type: .vegetables, calories: "14"),
    FoodRealm(name: "Cape gooseberry", type: .vegetables, calories: "53"),
    FoodRealm(name: "Carrot sticks", type: .vegetables, calories: "41"),
    FoodRealm(name: "Carrot", type: .vegetables, calories: "41"),
    FoodRealm(name: "Cayenne pepper", type: .vegetables, calories: "40"),
    FoodRealm(name: "Celery root", type: .vegetables, calories: "17"),
    FoodRealm(name: "Cherry tomatoes", type: .vegetables, calories: "18"),
    FoodRealm(name: "Chili pepper", type: .vegetables, calories: "40"),
    FoodRealm(name: "Chinese cabbage", type: .vegetables, calories: "12"),
    FoodRealm(name: "Chinese cucumber", type: .vegetables, calories: "12"),
    FoodRealm(name: "Chinese radish", type: .vegetables, calories: "16"),
    FoodRealm(name: "Chipotle pepper", type: .vegetables, calories: "40"),
    FoodRealm(name: "Chives", type: .vegetables, calories: "30"),
    FoodRealm(name: "Colchic kole", type: .vegetables, calories: "24"),
    FoodRealm(name: "Colorful cabbage", type: .vegetables, calories: "25"),
    FoodRealm(name: "Cooked lentils", type: .vegetables, calories: "116"),
    FoodRealm(name: "Corn on the cob", type: .vegetables, calories: "86"),
    FoodRealm(name: "Corn", type: .vegetables, calories: "86"),
    FoodRealm(name: "Cowpea", type: .vegetables, calories: "66"),
    FoodRealm(name: "Cucumber", type: .vegetables, calories: "15"),
    FoodRealm(name: "Daikon", type: .vegetables, calories: "18"),
    FoodRealm(name: "Dried beets", type: .vegetables, calories: "318"),
    FoodRealm(name: "Dried cabbage", type: .vegetables, calories: "350"),
    FoodRealm(name: "Dried horseradish", type: .vegetables, calories: "48"),
    FoodRealm(name: "Dried potatoes", type: .vegetables, calories: "307"),
    FoodRealm(name: "Dried vegetables", type: .vegetables, calories: "333"),
    FoodRealm(name: "Edamame", type: .vegetables, calories: "122"),
    FoodRealm(name: "Eggplant", type: .vegetables, calories: "25"),
    FoodRealm(name: "Fried onions", type: .vegetables, calories: "407"),
    FoodRealm(name: "Fried potatoes", type: .vegetables, calories: "319"),
    FoodRealm(name: "Frozen french fries", type: .vegetables, calories: "130"),
    FoodRealm(name: "Frozen vegetable mix", type: .vegetables, calories: "31"),
    FoodRealm(name: "Garden radish", type: .vegetables, calories: "16"),
    FoodRealm(name: "Garlic", type: .vegetables, calories: "149"),
    FoodRealm(name: "Gherkin", type: .vegetables, calories: "12"),
    FoodRealm(name: "Glazed carrots", type: .vegetables, calories: "109"),
    FoodRealm(name: "Green beans", type: .vegetables, calories: "31"),
    FoodRealm(name: "Green garlic", type: .vegetables, calories: "149"),
    FoodRealm(name: "Green peas", type: .vegetables, calories: "84"),
    FoodRealm(name: "Green tomatoes", type: .vegetables, calories: "23"),
    FoodRealm(name: "Habanero pepper", type: .vegetables, calories: "40"),
    FoodRealm(name: "Hot pepper", type: .vegetables, calories: "40"),
    FoodRealm(name: "Indian bitter gourd", type: .vegetables, calories: "20"),
    FoodRealm(name: "Jalapeño pepper", type: .vegetables, calories: "29"),
    FoodRealm(name: "Jerusalem artichoke", type: .vegetables, calories: "73"),
    FoodRealm(name: "Jicama", type: .vegetables, calories: "38"),
    FoodRealm(name: "Kale", type: .vegetables, calories: "35"),
    FoodRealm(name: "Kidney bean", type: .vegetables, calories: "127"),
    FoodRealm(name: "Kidney beans", type: .vegetables, calories: "127"),
    FoodRealm(name: "Kohlrabi", type: .vegetables, calories: "41"),
    FoodRealm(name: "Korean-style beets", type: .vegetables, calories: "21"),
    FoodRealm(name: "Korean-style carrots", type: .vegetables, calories: "32"),
    FoodRealm(name: "Lentils", type: .vegetables, calories: "116"),
    FoodRealm(name: "Lightly salted cucumbers", type: .vegetables, calories: "12"),
    FoodRealm(name: "Lima beans", type: .vegetables, calories: "113"),
    FoodRealm(name: "Loofah", type: .vegetables, calories: "24"),
    FoodRealm(name: "Mexican cucumber", type: .vegetables, calories: "13"),
    FoodRealm(name: "Mexican gherkin", type: .vegetables, calories: "13"),
    FoodRealm(name: "Mexican vegetable mix", type: .vegetables, calories: "37"),
    FoodRealm(name: "Mini pepper", type: .vegetables, calories: "20"),
    FoodRealm(name: "Mirepoix", type: .vegetables, calories: "42"),
    FoodRealm(name: "Mooli", type: .vegetables, calories: "16"),
    FoodRealm(name: "Mung bean sprouts", type: .vegetables, calories: "30"),
    FoodRealm(name: "Muscat pumpkin", type: .vegetables, calories: "47"),
    FoodRealm(name: "Okra", type: .vegetables, calories: "33"),
    FoodRealm(name: "Olives", type: .vegetables, calories: "115"),
    FoodRealm(name: "Onion", type: .vegetables, calories: "40"),
    FoodRealm(name: "Parsley root", type: .vegetables, calories: "45"),
    FoodRealm(name: "Parsnip", type: .vegetables, calories: "75"),
    FoodRealm(name: "Patty pan", type: .vegetables, calories: "24"),
    FoodRealm(name: "Peas", type: .vegetables, calories: "81"),
    FoodRealm(name: "Pepperoni", type: .vegetables, calories: "494"),
    FoodRealm(name: "Pickled artichokes", type: .vegetables, calories: "23"),
    FoodRealm(name: "Pickled asparagus", type: .vegetables, calories: "17"),
    FoodRealm(name: "Pickled beans", type: .vegetables, calories: "14"),
    FoodRealm(name: "Pickled broccoli", type: .vegetables, calories: "20"),
    FoodRealm(name: "Pickled cabbage", type: .vegetables, calories: "15"),
    FoodRealm(name: "Pickled carrots", type: .vegetables, calories: "21"),
    FoodRealm(name: "Pickled cherry tomatoes", type: .vegetables, calories: "12"),
    FoodRealm(name: "Pickled chili pepper", type: .vegetables, calories: "7"),
    FoodRealm(name: "Pickled chinese cabbage", type: .vegetables, calories: "11"),
    FoodRealm(name: "Pickled colorful cabbage", type: .vegetables, calories: "13"),
    FoodRealm(name: "Pickled cucumbers", type: .vegetables, calories: "12"),
    FoodRealm(name: "Pickled daikon", type: .vegetables, calories: "19"),
    FoodRealm(name: "Pickled eggplants", type: .vegetables, calories: "41"),
    FoodRealm(name: "Pickled garlic scapes", type: .vegetables, calories: "48"),
    FoodRealm(name: "Pickled garlic", type: .vegetables, calories: "109"),
    FoodRealm(name: "Pickled gherkins", type: .vegetables, calories: "12"),
    FoodRealm(name: "Pickled green beans", type: .vegetables, calories: "10"),
    FoodRealm(name: "Pickled green garlic", type: .vegetables, calories: "4"),
    FoodRealm(name: "Pickled habanero pepper", type: .vegetables, calories: "29"),
    FoodRealm(name: "Pickled hot pepper", type: .vegetables, calories: "21"),
    FoodRealm(name: "Pickled onions", type: .vegetables, calories: "19"),
    FoodRealm(name: "Pickled patty pan", type: .vegetables, calories: "16"),
    FoodRealm(name: "Pickled potatoes", type: .vegetables, calories: "32"),
    FoodRealm(name: "Pickled pumpkin", type: .vegetables, calories: "20"),
    FoodRealm(name: "Pickled radish", type: .vegetables, calories: "11"),
    FoodRealm(name: "Pickled red onion", type: .vegetables, calories: "21"),
    FoodRealm(name: "Pickled sweet pepper", type: .vegetables, calories: "19"),
    FoodRealm(name: "Pickled tomatoes", type: .vegetables, calories: "19"),
    FoodRealm(name: "Pickled wild garlic", type: .vegetables, calories: "34"),
    FoodRealm(name: "Pickled zucchini", type: .vegetables, calories: "15"),
    FoodRealm(name: "Potato", type: .vegetables, calories: "77"),
    FoodRealm(name: "Pumpkin", type: .vegetables, calories: "26"),
    FoodRealm(name: "Purple carrot", type: .vegetables, calories: "41"),
    FoodRealm(name: "Purple potato", type: .vegetables, calories: "77"),
    FoodRealm(name: "Radish", type: .vegetables, calories: "16"),
    FoodRealm(name: "Red cabbage", type: .vegetables, calories: "31"),
    FoodRealm(name: "Red lentils", type: .vegetables, calories: "116"),
    FoodRealm(name: "Red onion", type: .vegetables, calories: "40"),
    FoodRealm(name: "Red radish", type: .vegetables, calories: "14"),
    FoodRealm(name: "Rhubarb", type: .vegetables, calories: "21"),
    FoodRealm(name: "Romanesco", type: .vegetables, calories: "25"),
    FoodRealm(name: "Root vegetables", type: .vegetables, calories: "40"),
    FoodRealm(name: "Rutabaga", type: .vegetables, calories: "35"),
    FoodRealm(name: "Salted cucumbers", type: .vegetables, calories: "12"),
    FoodRealm(name: "Salted tomatoes", type: .vegetables, calories: "15"),
    FoodRealm(name: "Sauerkraut", type: .vegetables, calories: "19"),
    FoodRealm(name: "Savoy cabbage", type: .vegetables, calories: "27"),
    FoodRealm(name: "Serrano pepper", type: .vegetables, calories: "32"),
    FoodRealm(name: "Shallot", type: .vegetables, calories: "72"),
    FoodRealm(name: "Shelled peas", type: .vegetables, calories: "81"),
    FoodRealm(name: "Snake gourd", type: .vegetables, calories: "20"),
    FoodRealm(name: "Soybean sprouts", type: .vegetables, calories: "33"),
    FoodRealm(name: "Soybeans", type: .vegetables, calories: "446"),
    FoodRealm(name: "Spring vegetable mix", type: .vegetables, calories: "43"),
    FoodRealm(name: "Sugar beet", type: .vegetables, calories: "43"),
    FoodRealm(name: "Sun-dried tomatoes", type: .vegetables, calories: "258"),
    FoodRealm(name: "Sweet potato", type: .vegetables, calories: "86"),
    FoodRealm(name: "Taro", type: .vegetables, calories: "112"),
    FoodRealm(name: "Tomato", type: .vegetables, calories: "18"),
    FoodRealm(name: "Turnip", type: .vegetables, calories: "28"),
    FoodRealm(name: "White beans", type: .vegetables, calories: "142"),
    FoodRealm(name: "White cabbage", type: .vegetables, calories: "27"),
    FoodRealm(name: "White carrot", type: .vegetables, calories: "41"),
    FoodRealm(name: "White onion", type: .vegetables, calories: "40"),
    FoodRealm(name: "White radish", type: .vegetables, calories: "14"),
    FoodRealm(name: "Winter squash", type: .vegetables, calories: "45"),
    FoodRealm(name: "Yacon", type: .vegetables, calories: "55"),
    FoodRealm(name: "Yam", type: .vegetables, calories: "118"),
    FoodRealm(name: "Yellow beetroot", type: .vegetables, calories: "43"),
    FoodRealm(name: "Yellow carrot", type: .vegetables, calories: "41"),
    FoodRealm(name: "Young potatoes", type: .vegetables, calories: "86"),
    FoodRealm(name: "Zucchini", type: .vegetables, calories: "17")
]






























