//
//  FoodData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 21.05.2022.
//

import Foundation

let vegitables = [Vegetables(name: "Adzuki beans", type: .vegetables),
                  Vegetables(name: "African bird's eye chili", type: .vegetables),
                  Vegetables(name: "African horned cucumber", type: .vegetables),
                  Vegetables(name: "Ancho", type: .vegetables),
                  Vegetables(name: "Apple pepper", type: .vegetables),
                  Vegetables(name: "Artichoke", type: .vegetables),
                  Vegetables(name: "Baby carrots", type: .vegetables),
                  Vegetables(name: "Baby corn", type: .vegetables),
                  Vegetables(name: "Bean sprouts", type: .vegetables),
                  Vegetables(name: "Beans", type: .vegetables),
                  Vegetables(name: "Beetroot", type: .vegetables),
                  Vegetables(name: "Bell pepper", type: .vegetables),
                  Vegetables(name: "Beluga lentils", type: .vegetables),
                  Vegetables(name: "Bitter melon", type: .vegetables),
                  Vegetables(name: "Black beans", type: .vegetables),
                  Vegetables(name: "Black garlic", type: .vegetables),
                  Vegetables(name: "Black olives", type: .vegetables),
                  Vegetables(name: "Black radish", type: .vegetables),
                  Vegetables(name: "Black salsify", type: .vegetables),
                  Vegetables(name: "Boiled beetroot", type: .vegetables),
                  Vegetables(name: "Boiled carrots", type: .vegetables),
                  Vegetables(name: "Boiled potatoes", type: .vegetables),
                  Vegetables(name: "Bottle gourd", type: .vegetables),
                  Vegetables(name: "Breadfruit", type: .vegetables),
                  Vegetables(name: "Broccoli", type: .vegetables),
                  Vegetables(name: "Brussels sprouts", type: .vegetables),
                  Vegetables(name: "Burdock root", type: .vegetables),
                  Vegetables(name: "Butternut squash", type: .vegetables),
                  Vegetables(name: "Cabbage pak choi", type: .vegetables),
                  Vegetables(name: "Cabbage", type: .vegetables),
                  Vegetables(name: "Canned beans in tomato sauce", type: .vegetables),
                  Vegetables(name: "Canned beans", type: .vegetables),
                  Vegetables(name: "Canned beets", type: .vegetables),
                  Vegetables(name: "Canned black olives", type: .vegetables),
                  Vegetables(name: "Canned broad beans", type: .vegetables),
                  Vegetables(name: "Canned cabbage", type: .vegetables),
                  Vegetables(name: "Canned carrots", type: .vegetables),
                  Vegetables(name: "Canned cauliflower", type: .vegetables),
                  Vegetables(name: "Canned celery", type: .vegetables),
                  Vegetables(name: "Canned cherry tomatoes", type: .vegetables),
                  Vegetables(name: "Canned corn cobs", type: .vegetables),
                  Vegetables(name: "Canned cucumbers", type: .vegetables),
                  Vegetables(name: "Canned eggplants", type: .vegetables),
                  Vegetables(name: "Canned gherkins", type: .vegetables),
                  Vegetables(name: "Canned green beans", type: .vegetables),
                  Vegetables(name: "Canned green peas", type: .vegetables),
                  Vegetables(name: "Canned green tomatoes", type: .vegetables),
                  Vegetables(name: "Canned kidney beans", type: .vegetables),
                  Vegetables(name: "Canned lentils", type: .vegetables),
                  Vegetables(name: "Canned olives", type: .vegetables),
                  Vegetables(name: "Canned onions", type: .vegetables),
                  Vegetables(name: "Canned radish", type: .vegetables),
                  Vegetables(name: "Canned squash", type: .vegetables),
                  Vegetables(name: "Canned sweet pepper", type: .vegetables),
                  Vegetables(name: "Canned tomatoes", type: .vegetables),
                  Vegetables(name: "Canned vegetables", type: .vegetables),
                  Vegetables(name: "Canned white beans", type: .vegetables),
                  Vegetables(name: "Canned whole tomatoes", type: .vegetables),
                  Vegetables(name: "Canned zucchini", type: .vegetables),
                  Vegetables(name: "Cape gooseberry", type: .vegetables),
                  Vegetables(name: "Carrot sticks", type: .vegetables),
                  Vegetables(name: "Carrot", type: .vegetables),
                  Vegetables(name: "Cayenne pepper", type: .vegetables),
                  Vegetables(name: "Celery root", type: .vegetables),
                  Vegetables(name: "Cherry tomatoes", type: .vegetables),
                  Vegetables(name: "Chili pepper", type: .vegetables),
                  Vegetables(name: "Chinese cabbage", type: .vegetables),
                  Vegetables(name: "Chinese cucumber", type: .vegetables),
                  Vegetables(name: "Chinese radish", type: .vegetables),
                  Vegetables(name: "Chipotle pepper", type: .vegetables),
                  Vegetables(name: "Chives", type: .vegetables),
                  Vegetables(name: "Colchic kole", type: .vegetables),
                  Vegetables(name: "Colorful cabbage", type: .vegetables),
                  Vegetables(name: "Cooked lentils", type: .vegetables),
                  Vegetables(name: "Corn on the cob", type: .vegetables),
                  Vegetables(name: "Corn", type: .vegetables),
                  Vegetables(name: "Cowpea", type: .vegetables),
                  Vegetables(name: "Cucumber", type: .vegetables),
                  Vegetables(name: "Daikon", type: .vegetables),
                  Vegetables(name: "Dried beets", type: .vegetables),
                  Vegetables(name: "Dried cabbage", type: .vegetables),
                  Vegetables(name: "Dried horseradish", type: .vegetables),
                  Vegetables(name: "Dried potatoes", type: .vegetables),
                  Vegetables(name: "Dried vegetables", type: .vegetables),
                  Vegetables(name: "Edamame", type: .vegetables),
                  Vegetables(name: "Eggplant", type: .vegetables),
                  Vegetables(name: "Fried onions", type: .vegetables),
                  Vegetables(name: "Fried potatoes", type: .vegetables),
                  Vegetables(name: "Frozen french fries", type: .vegetables),
                  Vegetables(name: "Frozen vegetable mix", type: .vegetables),
                  Vegetables(name: "Garden radish", type: .vegetables),
                  Vegetables(name: "Garlic", type: .vegetables),
                  Vegetables(name: "Gherkin", type: .vegetables),
                  Vegetables(name: "Glazed carrots", type: .vegetables),
                  Vegetables(name: "Green beans", type: .vegetables),
                  Vegetables(name: "Green garlic", type: .vegetables),
                  Vegetables(name: "Green peas", type: .vegetables),
                  Vegetables(name: "Green tomatoes", type: .vegetables),
                  Vegetables(name: "Habanero pepper", type: .vegetables),
                  Vegetables(name: "Hot pepper", type: .vegetables),
                  Vegetables(name: "Indian bitter gourd", type: .vegetables),
                  Vegetables(name: "Jalapeño pepper", type: .vegetables),
                  Vegetables(name: "Jerusalem artichoke", type: .vegetables),
                  Vegetables(name: "Jicama", type: .vegetables),
                  Vegetables(name: "Kale", type: .vegetables),
                  Vegetables(name: "Kidney bean", type: .vegetables),
                  Vegetables(name: "Kidney beans", type: .vegetables),
                  Vegetables(name: "Kohlrabi", type: .vegetables),
                  Vegetables(name: "Korean-style beets", type: .vegetables),
                  Vegetables(name: "Korean-style carrots", type: .vegetables),
                  Vegetables(name: "Lentils", type: .vegetables),
                  Vegetables(name: "Lightly salted cucumbers", type: .vegetables),
                  Vegetables(name: "Lima beans", type: .vegetables),
                  Vegetables(name: "Loofah", type: .vegetables),
                  Vegetables(name: "Mexican cucumber", type: .vegetables),
                  Vegetables(name: "Mexican gherkin", type: .vegetables),
                  Vegetables(name: "Mexican vegetable mix", type: .vegetables),
                  Vegetables(name: "Mini pepper", type: .vegetables),
                  Vegetables(name: "Mirepoix", type: .vegetables),
                  Vegetables(name: "Mooli", type: .vegetables),
                  Vegetables(name: "Mung bean sprouts", type: .vegetables),
                  Vegetables(name: "Muscat pumpkin", type: .vegetables),
                  Vegetables(name: "Okra", type: .vegetables),
                  Vegetables(name: "Olives", type: .vegetables),
                  Vegetables(name: "Onion", type: .vegetables),
                  Vegetables(name: "Parsley root", type: .vegetables),
                  Vegetables(name: "Parsnip", type: .vegetables),
                  Vegetables(name: "Patty pan", type: .vegetables),
                  Vegetables(name: "Peas", type: .vegetables),
                  Vegetables(name: "Pepperoni", type: .vegetables),
                  Vegetables(name: "Pickled artichokes", type: .vegetables),
                  Vegetables(name: "Pickled asparagus", type: .vegetables),
                  Vegetables(name: "Pickled beans", type: .vegetables),
                  Vegetables(name: "Pickled broccoli", type: .vegetables),
                  Vegetables(name: "Pickled cabbage", type: .vegetables),
                  Vegetables(name: "Pickled carrots", type: .vegetables),
                  Vegetables(name: "Pickled cherry tomatoes", type: .vegetables),
                  Vegetables(name: "Pickled chili pepper", type: .vegetables),
                  Vegetables(name: "Pickled chinese cabbage", type: .vegetables),
                  Vegetables(name: "Pickled colorful cabbage", type: .vegetables),
                  Vegetables(name: "Pickled cucumbers", type: .vegetables),
                  Vegetables(name: "Pickled daikon", type: .vegetables),
                  Vegetables(name: "Pickled eggplants", type: .vegetables),
                  Vegetables(name: "Pickled garlic scapes", type: .vegetables),
                  Vegetables(name: "Pickled garlic", type: .vegetables),
                  Vegetables(name: "Pickled gherkins", type: .vegetables),
                  Vegetables(name: "Pickled green beans", type: .vegetables),
                  Vegetables(name: "Pickled green garlic", type: .vegetables),
                  Vegetables(name: "Pickled habanero pepper", type: .vegetables),
                  Vegetables(name: "Pickled hot pepper", type: .vegetables),
                  Vegetables(name: "Pickled onions", type: .vegetables),
                  Vegetables(name: "Pickled patty pan", type: .vegetables),
                  Vegetables(name: "Pickled potatoes", type: .vegetables),
                  Vegetables(name: "Pickled pumpkin", type: .vegetables),
                  Vegetables(name: "Pickled radish", type: .vegetables),
                  Vegetables(name: "Pickled red onion", type: .vegetables),
                  Vegetables(name: "Pickled sweet pepper", type: .vegetables),
                  Vegetables(name: "Pickled tomatoes", type: .vegetables),
                  Vegetables(name: "Pickled wild garlic", type: .vegetables),
                  Vegetables(name: "Pickled zucchini", type: .vegetables),
                  Vegetables(name: "Potato", type: .vegetables),
                  Vegetables(name: "Pumpkin", type: .vegetables),
                  Vegetables(name: "Purple carrot", type: .vegetables),
                  Vegetables(name: "Purple potato", type: .vegetables),
                  Vegetables(name: "Radish", type: .vegetables),
                  Vegetables(name: "Red cabbage", type: .vegetables),
                  Vegetables(name: "Red lentils", type: .vegetables),
                  Vegetables(name: "Red onion", type: .vegetables),
                  Vegetables(name: "Red radish", type: .vegetables),
                  Vegetables(name: "Rhubarb", type: .vegetables),
                  Vegetables(name: "Romanesco", type: .vegetables),
                  Vegetables(name: "Root vegetables", type: .vegetables),
                  Vegetables(name: "Rutabaga", type: .vegetables),
                  Vegetables(name: "Salted cucumbers", type: .vegetables),
                  Vegetables(name: "Salted tomatoes", type: .vegetables),
                  Vegetables(name: "Sauerkraut", type: .vegetables),
                  Vegetables(name: "Savoy cabbage", type: .vegetables),
                  Vegetables(name: "Serrano pepper", type: .vegetables),
                  Vegetables(name: "Shallot", type: .vegetables),
                  Vegetables(name: "Shelled peas", type: .vegetables),
                  Vegetables(name: "Snake gourd", type: .vegetables),
                  Vegetables(name: "Soybean sprouts", type: .vegetables),
                  Vegetables(name: "Soybeans", type: .vegetables),
                  Vegetables(name: "Spring vegetable mix", type: .vegetables),
                  Vegetables(name: "Sugar beet", type: .vegetables),
                  Vegetables(name: "Sun-dried tomatoes", type: .vegetables),
                  Vegetables(name: "Sweet potato", type: .vegetables),
                  Vegetables(name: "Taro", type: .vegetables),
                  Vegetables(name: "Tomato", type: .vegetables),
                  Vegetables(name: "Turnip", type: .vegetables),
                  Vegetables(name: "White beans", type: .vegetables),
                  Vegetables(name: "White cabbage", type: .vegetables),
                  Vegetables(name: "White carrot", type: .vegetables),
                  Vegetables(name: "White onion", type: .vegetables),
                  Vegetables(name: "White radish", type: .vegetables),
                  Vegetables(name: "Winter squash", type: .vegetables),
                  Vegetables(name: "Yacon", type: .vegetables),
                  Vegetables(name: "Yam", type: .vegetables),
                  Vegetables(name: "Yellow beetroot", type: .vegetables),
                  Vegetables(name: "Yellow carrot", type: .vegetables),
                  Vegetables(name: "Young potatoes", type: .vegetables),
                  Vegetables(name: "Zucchini", type: .vegetables)
]

var allFood = vegitables + fruitsAndBerries + mushrooms




























