//
//  FoodData.swift
//  FoodAtHome
//
//  Created by Артем Кудрявцев on 21.05.2022.
//

import Foundation
import RealmSwift

var test = [FoodRealm]()
var vcCheck = Bool()

var foodRealmArra: Results<FoodRealm>!


let vegitables = [Vegetables(name: "Анчо", type: .vegetables),
                  Vegetables(name: "Артишок", type: .vegetables),
                  Vegetables(name: "Африканский огурец мелотрия", type: .vegetables),
                  Vegetables(name: "Баклажан", type: .vegetables),
                  Vegetables(name: "Баклажаны консервированные", type: .vegetables),
                  Vegetables(name: "Бамия", type: .vegetables),
                  Vegetables(name: "Батат", type: .vegetables),
                  Vegetables(name: "Белая морковь", type: .vegetables),
                  Vegetables(name: "Бобы", type: .vegetables),
                  Vegetables(name: "Брокколи", type: .vegetables),
                  Vegetables(name: "Брюква турнепс", type: .vegetables),
                  Vegetables(name: "Брюква", type: .vegetables),
                  Vegetables(name: "Вареная кукуруза", type: .vegetables),
                  Vegetables(name: "Вареная морковь", type: .vegetables),
                  Vegetables(name: "Вареная свекла", type: .vegetables),
                  Vegetables(name: "Вареный картофель", type: .vegetables),
                  Vegetables(name: "Вигна (Коровий горох)", type: .vegetables),
                  Vegetables(name: "Восковая тыква зимняя", type: .vegetables),
                  Vegetables(name: "Вяленые томаты", type: .vegetables),
                  Vegetables(name: "Горох", type: .vegetables),
                  Vegetables(name: "Горошек зеленый консервированный", type: .vegetables),
                  Vegetables(name: "Горошек зеленый", type: .vegetables),
                  Vegetables(name: "Горькая тыква момордика", type: .vegetables),
                  Vegetables(name: "Дайкон маринованный", type: .vegetables),
                  Vegetables(name: "Дайкон", type: .vegetables),
                  Vegetables(name: "Жареный картофель", type: .vegetables),
                  Vegetables(name: "Желтая свекла", type: .vegetables),
                  Vegetables(name: "Замороженная овощная смесь", type: .vegetables),
                  Vegetables(name: "Замороженный картофель фри", type: .vegetables),
                  Vegetables(name: "Зеленые помидоры консервированные", type: .vegetables),
                  Vegetables(name: "Зеленый огурец", type: .vegetables),
                  Vegetables(name: "Индийский огурец момордика", type: .vegetables),
                  Vegetables(name: "Кабачок", type: .vegetables),
                  Vegetables(name: "Капуста белокочанная", type: .vegetables),
                  Vegetables(name: "Капуста брюссельская", type: .vegetables),
                  Vegetables(name: "Капуста кале", type: .vegetables),
                  Vegetables(name: "Капуста консервированная", type: .vegetables),
                  Vegetables(name: "Капуста краснокочанная", type: .vegetables),
                  Vegetables(name: "Капуста маринованная", type: .vegetables),
                  Vegetables(name: "Капуста пак чой", type: .vegetables),
                  Vegetables(name: "Капуста пекинская", type: .vegetables),
                  Vegetables(name: "Капуста романеско", type: .vegetables),
                  Vegetables(name: "Капуста савойская", type: .vegetables),
                  Vegetables(name: "Капуста цветная", type: .vegetables),
                  Vegetables(name: "Капуста", type: .vegetables),
                  Vegetables(name: "Картофель", type: .vegetables),
                  Vegetables(name: "Квашеная капуста", type: .vegetables),
                  Vegetables(name: "Клекачка колхидская (Джонджоли)", type: .vegetables),
                  Vegetables(name: "Колоказия съедобная", type: .vegetables),
                  Vegetables(name: "Кольраби", type: .vegetables),
                  Vegetables(name: "Консервированная стручковая фасоль", type: .vegetables),
                  Vegetables(name: "Консервированная фасоль в томатном соусе", type: .vegetables),
                  Vegetables(name: "Консервированные бобы", type: .vegetables),
                  Vegetables(name: "Консервированные кабачки", type: .vegetables),
                  Vegetables(name: "Консервированные корнишоны", type: .vegetables),
                  Vegetables(name: "Консервированные маслины", type: .vegetables),
                  Vegetables(name: "Консервированные овощи", type: .vegetables),
                  Vegetables(name: "Консервированные огурцы", type: .vegetables),
                  Vegetables(name: "Консервированные оливки", type: .vegetables),
                  Vegetables(name: "Консервированные патиссоны", type: .vegetables),
                  Vegetables(name: "Консервированные помидоры", type: .vegetables),
                  Vegetables(name: "Консервированные початки кукурузы", type: .vegetables),
                  Vegetables(name: "Консервированные черри", type: .vegetables),
                  Vegetables(name: "Консервированный лук", type: .vegetables),
                  Vegetables(name: "Консервированный редис", type: .vegetables),
                  Vegetables(name: "Консервированный сельдерей", type: .vegetables),
                  Vegetables(name: "Корень петрушки", type: .vegetables),
                  Vegetables(name: "Корень сельдерея", type: .vegetables),
                  Vegetables(name: "Корнеплоды", type: .vegetables),
                  Vegetables(name: "Корнишоны маринованные", type: .vegetables),
                  Vegetables(name: "Корнишоны", type: .vegetables),
                  Vegetables(name: "Красная редька", type: .vegetables),
                  Vegetables(name: "Красный лук", type: .vegetables),
                  Vegetables(name: "Красный огурец тладианта", type: .vegetables),
                  Vegetables(name: "Кукуруза", type: .vegetables),
                  Vegetables(name: "Лагенария", type: .vegetables),
                  Vegetables(name: "Лимская фасоль", type: .vegetables),
                  Vegetables(name: "Лук душистый джусай", type: .vegetables),
                  Vegetables(name: "Лук жареный", type: .vegetables),
                  Vegetables(name: "Лук репчатый", type: .vegetables),
                  Vegetables(name: "Лук-шалот", type: .vegetables),
                  Vegetables(name: "Лущеный горох", type: .vegetables),
                  Vegetables(name: "Малосольные огурцы", type: .vegetables),
                  Vegetables(name: "Маргеланская (китайская) редька", type: .vegetables),
                  Vegetables(name: "Маринованная брокколи", type: .vegetables),
                  Vegetables(name: "Маринованная капуста пекинская", type: .vegetables),
                  Vegetables(name: "Маринованная капуста цветная", type: .vegetables),
                  Vegetables(name: "Маринованная морковь", type: .vegetables),
                  Vegetables(name: "Маринованная спаржа", type: .vegetables),
                  Vegetables(name: "Маринованная стручковая фасоль", type: .vegetables),
                  Vegetables(name: "Маринованная тыква", type: .vegetables),
                  Vegetables(name: "Маринованная фасоль", type: .vegetables),
                  Vegetables(name: "Маринованные артишоки", type: .vegetables),
                  Vegetables(name: "Маринованные баклажаны", type: .vegetables),
                  Vegetables(name: "Маринованные кабачки", type: .vegetables),
                  Vegetables(name: "Маринованные огурцы", type: .vegetables),
                  Vegetables(name: "Маринованные помидоры черри", type: .vegetables),
                  Vegetables(name: "Маринованные помидоры", type: .vegetables),
                  Vegetables(name: "Маринованные цукини", type: .vegetables),
                  Vegetables(name: "Маринованный горький перец", type: .vegetables),
                  Vegetables(name: "Маринованный картофель", type: .vegetables),
                  Vegetables(name: "Маринованный красный лук", type: .vegetables),
                  Vegetables(name: "Маринованный лук", type: .vegetables),
                  Vegetables(name: "Маринованный молодой чеснок", type: .vegetables),
                  Vegetables(name: "Маринованный сладкий перец", type: .vegetables),
                  Vegetables(name: "Маринованный чеснок", type: .vegetables),
                  Vegetables(name: "Маслины", type: .vegetables),
                  Vegetables(name: "Мексиканская овощная смесь", type: .vegetables),
                  Vegetables(name: "Мексиканский огурец чайот", type: .vegetables),
                  Vegetables(name: "Мини кукуруза", type: .vegetables),
                  Vegetables(name: "Мини морковь", type: .vegetables),
                  Vegetables(name: "Мини перец", type: .vegetables),
                  Vegetables(name: "Мирпуа", type: .vegetables),
                  Vegetables(name: "Молодой картофель", type: .vegetables),
                  Vegetables(name: "Молодой чеснок зеленый", type: .vegetables),
                  Vegetables(name: "Морковные палочки", type: .vegetables),
                  Vegetables(name: "Морковь желтая", type: .vegetables),
                  Vegetables(name: "Морковь консервированная", type: .vegetables),
                  Vegetables(name: "Морковь пассерованная", type: .vegetables),
                  Vegetables(name: "Морковь по-корейски", type: .vegetables),
                  Vegetables(name: "Морковь", type: .vegetables),
                  Vegetables(name: "Огурец китайский", type: .vegetables),
                  Vegetables(name: "Огурец", type: .vegetables),
                  Vegetables(name: "Оливки", type: .vegetables),
                  Vegetables(name: "Пастернак", type: .vegetables),
                  Vegetables(name: "Патиссон", type: .vegetables),
                  Vegetables(name: "Патиссоны маринованные", type: .vegetables),
                  Vegetables(name: "Перец горький", type: .vegetables),
                  Vegetables(name: "Перец кайенский", type: .vegetables),
                  Vegetables(name: "Перец пепперони", type: .vegetables),
                  Vegetables(name: "Перец пири-пири", type: .vegetables),
                  Vegetables(name: "Перец ратунда (гогошар)", type: .vegetables),
                  Vegetables(name: "Перец серрано", type: .vegetables),
                  Vegetables(name: "Перец сладкий консервированный", type: .vegetables),
                  Vegetables(name: "Перец хабанеро", type: .vegetables),
                  Vegetables(name: "Перец халапеньо маринованный", type: .vegetables),
                  Vegetables(name: "Перец халапеньо", type: .vegetables),
                  Vegetables(name: "Перец чили маринованный", type: .vegetables),
                  Vegetables(name: "Перец чили", type: .vegetables),
                  Vegetables(name: "Перец чипотле", type: .vegetables),
                  Vegetables(name: "Перец", type: .vegetables),
                  Vegetables(name: "Плоды хлебного дерева", type: .vegetables),
                  Vegetables(name: "Помидор", type: .vegetables),
                  Vegetables(name: "Помидоры черри", type: .vegetables),
                  Vegetables(name: "Ревень", type: .vegetables),
                  Vegetables(name: "Редис маринованный", type: .vegetables),
                  Vegetables(name: "Редис", type: .vegetables),
                  Vegetables(name: "Редька белая", type: .vegetables),
                  Vegetables(name: "Редька зеленая", type: .vegetables),
                  Vegetables(name: "Редька", type: .vegetables),
                  Vegetables(name: "Репа", type: .vegetables),
                  Vegetables(name: "Репчатый лук белый", type: .vegetables),
                  Vegetables(name: "Ростки бобов мунг", type: .vegetables),
                  Vegetables(name: "Ростки сои", type: .vegetables),
                  Vegetables(name: "Ростки фасоли", type: .vegetables),
                  Vegetables(name: "Сахарная свекла", type: .vegetables),
                  Vegetables(name: "Свекла консервированная", type: .vegetables),
                  Vegetables(name: "Свекла по-корейски", type: .vegetables),
                  Vegetables(name: "Свекла", type: .vegetables),
                  Vegetables(name: "Скорцонера", type: .vegetables),
                  Vegetables(name: "Смесь овощная весенняя", type: .vegetables),
                  Vegetables(name: "Соленые огурцы", type: .vegetables),
                  Vegetables(name: "Соленые помидоры", type: .vegetables),
                  Vegetables(name: "Соя", type: .vegetables),
                  Vegetables(name: "Стрелки чеснока маринованные", type: .vegetables),
                  Vegetables(name: "Сушеная капуста", type: .vegetables),
                  Vegetables(name: "Сушеная свекла", type: .vegetables),
                  Vegetables(name: "Сушеные овощи", type: .vegetables),
                  Vegetables(name: "Сушеный картофель", type: .vegetables),
                  Vegetables(name: "Томаты в собственном соку", type: .vegetables),
                  Vegetables(name: "Томаты зеленые", type: .vegetables),
                  Vegetables(name: "Топинамбур", type: .vegetables),
                  Vegetables(name: "Тыква баттернат", type: .vegetables),
                  Vegetables(name: "Тыква люффа", type: .vegetables),
                  Vegetables(name: "Тыква мускатная", type: .vegetables),
                  Vegetables(name: "Тыква", type: .vegetables),
                  Vegetables(name: "Фасоль адзуки", type: .vegetables),
                  Vegetables(name: "Фасоль белая консервированная", type: .vegetables),
                  Vegetables(name: "Фасоль белая", type: .vegetables),
                  Vegetables(name: "Фасоль консервированная", type: .vegetables),
                  Vegetables(name: "Фасоль красная консервированная", type: .vegetables),
                  Vegetables(name: "Фасоль красная", type: .vegetables),
                  Vegetables(name: "Фасоль стручковая", type: .vegetables),
                  Vegetables(name: "Фасоль", type: .vegetables),
                  Vegetables(name: "Физалис", type: .vegetables),
                  Vegetables(name: "Фиолетовая морковь", type: .vegetables),
                  Vegetables(name: "Фиолетовый картофель", type: .vegetables),
                  Vegetables(name: "Хикама", type: .vegetables),
                  Vegetables(name: "Хрен сушеный", type: .vegetables),
                  Vegetables(name: "Цветная капуста консервированная", type: .vegetables),
                  Vegetables(name: "Цукини", type: .vegetables),
                  Vegetables(name: "Черемша маринованная", type: .vegetables),
                  Vegetables(name: "Чёрная редька", type: .vegetables),
                  Vegetables(name: "Черная фасоль", type: .vegetables),
                  Vegetables(name: "Черная чечевица", type: .vegetables),
                  Vegetables(name: "Черный чеснок", type: .vegetables),
                  Vegetables(name: "Чеснок", type: .vegetables),
                  Vegetables(name: "Чечевица вареная", type: .vegetables),
                  Vegetables(name: "Чечевица консервированная", type: .vegetables),
                  Vegetables(name: "Чечевица красная", type: .vegetables),
                  Vegetables(name: "Чечевица", type: .vegetables),
                  Vegetables(name: "Эдамам", type: .vegetables),
                  Vegetables(name: "Якон", type: .vegetables),
                  Vegetables(name: "Ямс", type: .vegetables)
]

let fruitsAndBerries = [FruitsAndBerries(name: "Абрикос", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Авара", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Авокадо", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Адамово яблоко (Маклюра)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Азимина", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Айва", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Аки", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Актинидия", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Алыча", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ананас", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Апельсин бергамот", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Апельсин", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Араза", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Арбуз", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Арбузы консервированные", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Бабако", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Баиль", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Банан", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Бананы мини", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Барбадосская вишня ацерола", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Барбарис", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Билимби (Огуречное дерево)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Боярышник", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Брусника", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Бузина", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Вампи", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Виноград Изабелла", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Виноград Каберне Совиньон (Cabernet Sauvignon)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Виноград кишмиш", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Виноград Мерло (Merlot)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Виноград Мускат", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Виноград Ркацители", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Виноград Шардоне (Chardonnay)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Виноград", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Вишня", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Водяника (шикша)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Войлочная вишня", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Голубика", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Гранадилла", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Гранат", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Грейпфрут", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Груша", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Гуава земляничная", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Гуава", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Гуанабана (Сметанное яблоко)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Гуарана", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Дерево сикомор", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Джаботикаба", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Джекфрут", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Дуриан", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Дыня", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ежевика", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Желтый арбуз", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Жердела", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Жимолость", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Замороженная вишня", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Замороженные фрукты", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Замороженные ягоды", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Звездное яблоко", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Земклуника", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Земляника", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Земляничное дерево", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Зизифус (Унаби)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Икако (Золотая слива)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Илама", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Инжир", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Инжирный персик", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ирга", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Йошта", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Каламондин (Цитрофортунелла)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Калина", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Каму-каму", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Канталупа", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Капулин", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Карамбола", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Каранда", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Кассаба", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Кафир-лайм", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Кепел", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Кивано", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Киви", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Кизил", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Китайская груша (Нэши)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Китайская клубника (восковница красная)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Клементин", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Клубника маринованная", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Клубника", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Клюква", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Княженика", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Консервированная дыня", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Консервированная черешня", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Консервированные бананы", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Консервированные мандарины", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Консервированные сливы", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Консервированные ягоды", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Консервированный виноград", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Корлан", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Костяника", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Красника", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Красный виноград", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Крыжовник зеленый", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Крыжовник", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Кудрания (Клубничное дерево)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Кумкват", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Купуасу", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Лайм", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Лангсат", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Лимон", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Лимонник", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Личи", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Логанова ягода", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Лонган", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Лукума", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маболо", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Магический фрукт", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Малина", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маммея", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Манго консервированное", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Манго", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Мангостин", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Мандарины", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маракуйя", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маранг", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованная вишня", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованная красная смородина", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованные апельсины", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованные груши", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованные лимоны", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованные сливы", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованные яблоки", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованный ананас", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованный арбуз", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованный крыжовник", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Маринованный чернослив", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Марула", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Медовая дыня", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Можжевельник", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Мора", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Морошка", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Морской виноград (Кокколоба ягодоносная)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Мускатная дыня", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Мушмула германская", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Мушмула японская", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Мушмула", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Нансе", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Наранхилла", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Нектарин", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Нойна", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Нони", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Облепиха", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Панданус (кьюра)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Папайя", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Пассифлора голубая (кавалерская звезда)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Пепино", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Персик", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Персики маринованные", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Питахайя", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Платония", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Плоды померанца (чинотто)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Плуот", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Помело", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Рамбутан", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Рука Будды", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Рябина красная", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Салак", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Саподилла", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Сапота (чёрное яблоко)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Сатсума", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Свежемороженая клубника", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Свежемороженая малина", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Свити", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Сереноа", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Сизигиум", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Слива", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Смородина белая", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Смородина красная", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Смородина черная", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Суринамская вишня питанга", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Сушеная малина", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Тамарилло", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Тамаринд", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Танжело", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Танжерин", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Терн", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Толокнянка обыкновенная (медвежье ушко)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Угни (Уньи)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Фалса", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Фейхоа", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ферония (Деревянное яблоко)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Фрукты", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Хурма виргинская", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Хурма", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Цабр", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Цитрон", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Чемпедак", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Черёмуха виргинская", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Черешня", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Черимойя", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Черника сушеная", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Черника", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Черноплодная рябина", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Черный виноград", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Чилибуха (Рвотный орех)", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Чупа-чупа", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Шелковица", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Шефердия серебристая", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Шиповник", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Эмблика лекарственная", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Юдзу", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Айдаред", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Анис", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки антоновка", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки белый налив", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Богатырь", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Гала", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Глостер", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки голден", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Гренни Смит", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Грушовка", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Джонаголд", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Джонатан", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Китайка", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Макинтош", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Мантет", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Медуница", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Мельба", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки моченые", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Пепин", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки ранетки", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Слава победителям", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Спартан", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Флорина", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоки Фуджи", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоко Лобо", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Яблоко", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ягода дереза китайская", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ягода лох", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ягода магония падуболистная", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ягоды асаи", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ягоды годжи", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Ягоды", type: .fruitsAndBerries),
                        FruitsAndBerries(name: "Японский лимон (Юзу)", type: .fruitsAndBerries)
]

let mushrooms = [Mushrooms(name: "Белые грибы маринованные", type: .mushrooms),
                 Mushrooms(name: "Белый гриб сушеный", type: .mushrooms),
                 Mushrooms(name: "Белый гриб", type: .mushrooms),
                 Mushrooms(name: "Белый степной гриб (Еринги)", type: .mushrooms),
                 Mushrooms(name: "Белый трюфель", type: .mushrooms),
                 Mushrooms(name: "Березовый гриб чага", type: .mushrooms),
                 Mushrooms(name: "Вешенки", type: .mushrooms),
                 Mushrooms(name: "Гигрофор", type: .mushrooms),
                 Mushrooms(name: "Гриб говорушка", type: .mushrooms),
                 Mushrooms(name: "Гриб дождевик", type: .mushrooms),
                 Mushrooms(name: "Гриб ежовик", type: .mushrooms),
                 Mushrooms(name: "Гриб майтаке", type: .mushrooms),
                 Mushrooms(name: "Гриб мацутакэ", type: .mushrooms),
                 Mushrooms(name: "Гриб моховик", type: .mushrooms),
                 Mushrooms(name: "Гриб порховка", type: .mushrooms),
                 Mushrooms(name: "Гриб серушка", type: .mushrooms),
                 Mushrooms(name: "Гриб-баран", type: .mushrooms),
                 Mushrooms(name: "Грибная икра", type: .mushrooms),
                 Mushrooms(name: "Грибная капуста (Спарассис курчавый)", type: .mushrooms),
                 Mushrooms(name: "Грибы волнушки", type: .mushrooms),
                 Mushrooms(name: "Грибы мун", type: .mushrooms),
                 Mushrooms(name: "Грибы намеко", type: .mushrooms),
                 Mushrooms(name: "Грибы портобелло", type: .mushrooms),
                 Mushrooms(name: "Грибы рядовки", type: .mushrooms),
                 Mushrooms(name: "Грибы сушеные", type: .mushrooms),
                 Mushrooms(name: "Грибы эноки", type: .mushrooms),
                 Mushrooms(name: "Груздь", type: .mushrooms),
                 Mushrooms(name: "Древесный гриб муэр", type: .mushrooms),
                 Mushrooms(name: "Дубовик обыкновенный", type: .mushrooms),
                 Mushrooms(name: "Ежовик желтый", type: .mushrooms),
                 Mushrooms(name: "Замороженные грибы", type: .mushrooms),
                 Mushrooms(name: "Ивишень (Подвишенник)", type: .mushrooms),
                 Mushrooms(name: "Консервированные белые грибы", type: .mushrooms),
                 Mushrooms(name: "Консервированные грибы", type: .mushrooms),
                 Mushrooms(name: "Королевские опята (Чешуйчатка золотистая)", type: .mushrooms),
                 Mushrooms(name: "Королевский устричный гриб", type: .mushrooms),
                 Mushrooms(name: "Лисички", type: .mushrooms),
                 Mushrooms(name: "Майский гриб", type: .mushrooms),
                 Mushrooms(name: "Маринованное грибное ассорти", type: .mushrooms),
                 Mushrooms(name: "Маринованные вешенки", type: .mushrooms),
                 Mushrooms(name: "Маринованные грибы", type: .mushrooms),
                 Mushrooms(name: "Маринованные грузди", type: .mushrooms),
                 Mushrooms(name: "Маринованные лисички", type: .mushrooms),
                 Mushrooms(name: "Маринованные маслята", type: .mushrooms),
                 Mushrooms(name: "Маринованные рыжики", type: .mushrooms),
                 Mushrooms(name: "Маринованные шампиньоны", type: .mushrooms),
                 Mushrooms(name: "Маслята", type: .mushrooms),
                 Mushrooms(name: "Мокруха пурпуровая", type: .mushrooms),
                 Mushrooms(name: "Опенок зимний", type: .mushrooms),
                 Mushrooms(name: "Опята маринованные", type: .mushrooms),
                 Mushrooms(name: "Опята", type: .mushrooms),
                 Mushrooms(name: "Пецица", type: .mushrooms),
                 Mushrooms(name: "Плютей олений", type: .mushrooms),
                 Mushrooms(name: "Подберёзовик сушеный", type: .mushrooms),
                 Mushrooms(name: "Подберёзовик", type: .mushrooms),
                 Mushrooms(name: "Подосиновик сушеный", type: .mushrooms),
                 Mushrooms(name: "Подосиновик", type: .mushrooms),
                 Mushrooms(name: "Полубелый гриб", type: .mushrooms),
                 Mushrooms(name: "Польский гриб", type: .mushrooms),
                 Mushrooms(name: "Рыжик", type: .mushrooms),
                 Mushrooms(name: "Сморчок", type: .mushrooms),
                 Mushrooms(name: "Соленые рыжики", type: .mushrooms),
                 Mushrooms(name: "Сушеные лисички", type: .mushrooms),
                 Mushrooms(name: "Сушеные шампиньоны", type: .mushrooms),
                 Mushrooms(name: "Сыроежка", type: .mushrooms),
                 Mushrooms(name: "Трюфель", type: .mushrooms),
                 Mushrooms(name: "Цезарский гриб", type: .mushrooms),
                 Mushrooms(name: "Чернушка", type: .mushrooms),
                 Mushrooms(name: "Шампиньоны консервированные", type: .mushrooms),
                 Mushrooms(name: "Шампиньоны", type: .mushrooms),
                 Mushrooms(name: "Шиитаке сушеные", type: .mushrooms),
                 Mushrooms(name: "Шиитаке", type: .mushrooms),
                 Mushrooms(name: "Шимеджи", type: .mushrooms)
]


var allFood = vegitables + fruitsAndBerries + mushrooms 




























